// Code generated by roost servicerpc. DO NOT EDIT.
//
// Generated from the Coordinator interface in this package. The interface is
// the single source of truth: the wire types, the handler table and the client
// are all derived from it, so a method added to the interface cannot be
// forgotten in the transport — the failure this generator exists to make
// impossible rather than merely detectable.
//
// This file is the transport half and depends on roost-core only. The
// assembly half — Server, OwnerCapabilities, ClientMod, which need
// roost-kit/mods for the Mod and capability names — is coordinator_rpc_assembly_gen.go
// beside it. The split is what lets an interface move into a core domain
// package and take its wire types, handler table and BusClient along (M-10).
//
// Regenerate with:
//
//	go run github.com/tjbdwanghaibo/roost-core/codegen/cmd/servicerpc -dir .

package activity

import (
	"context"
	"fmt"
	"time"

	"github.com/tjbdwanghaibo/roost-core/app"
	"github.com/tjbdwanghaibo/roost-core/bus"
	"github.com/tjbdwanghaibo/roost-core/servicerpc"
)

// ServiceType is the bus service type Coordinator answers on. The client and
// the handlers key on it, so it is one constant rather than a string in two
// places.
const ServiceType = "activity"

// The RPC method names, prefixed with the service type so a bus subject is
// unambiguous when several services register handlers on one connection.
const (
	MethodOpenActivity      = "activity.OpenActivity"
	MethodLookupActivity    = "activity.LookupActivity"
	MethodPendingActivities = "activity.PendingActivities"
	MethodNotifyPhase       = "activity.NotifyPhase"
	MethodApplyProgress     = "activity.ApplyProgress"
	MethodLookupParticipant = "activity.LookupParticipant"
	MethodReservation       = "activity.Reservation"
	MethodOwedDispatches    = "activity.OwedDispatches"
	MethodLookupDispatch    = "activity.LookupDispatch"
	MethodAttemptDispatch   = "activity.AttemptDispatch"
	MethodAckDispatch       = "activity.AckDispatch"
)

// Methods is every method on Coordinator, in interface order.
//
// RegisterHandlers iterates it, so a method with no handler fails at startup
// with a name rather than at the first call from another process.
var Methods = []string{
	MethodOpenActivity,
	MethodLookupActivity,
	MethodPendingActivities,
	MethodNotifyPhase,
	MethodApplyProgress,
	MethodLookupParticipant,
	MethodReservation,
	MethodOwedDispatches,
	MethodLookupDispatch,
	MethodAttemptDispatch,
	MethodAckDispatch,
}

// rpcStatus is the envelope every response embeds.
//
// A business failure travels inside the envelope with this package's error
// code; a bus error means the call did not happen. A caller retrying the
// second and not the first is the difference between recovering and
// double-applying, which is why the two are never the same channel.
type rpcStatus struct {
	Code   int32  `json:"code"`
	Reason string `json:"reason,omitempty"`
}

// StatusCode implements servicerpc.ResponseStatusProvider. The methods are
// exported even though the type is not, which is what the assertion in
// servicerpc.CheckResponse needs.
func (s rpcStatus) StatusCode() int32 { return s.Code }

// StatusReason implements servicerpc.ResponseStatusProvider.
func (s rpcStatus) StatusReason() string { return s.Reason }

// statusOf renders an error using this package's Error, so a code that reaches
// a client is the same code a local caller reads off the error.
func statusOf(err error) rpcStatus {
	code, reason := Error(err)
	return rpcStatus{Code: code, Reason: reason}
}

// --- wire types ---

// rpcOpenActivityRequest is the OpenActivity request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcOpenActivityRequest struct {
	Key              Key     `json:"key"`
	ExpectedGameSIDs []int32 `json:"expected_game_si_ds"`
}

// rpcOpenActivityResponse is the OpenActivity response on the wire.
type rpcOpenActivityResponse struct {
	rpcStatus
	Activity Activity `json:"activity"`
}

// rpcLookupActivityRequest is the LookupActivity request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcLookupActivityRequest struct {
	Key Key `json:"key"`
}

// rpcLookupActivityResponse is the LookupActivity response on the wire.
type rpcLookupActivityResponse struct {
	rpcStatus
	Activity Activity `json:"activity"`
	Found    bool     `json:"found"`
}

// rpcPendingActivitiesRequest is the PendingActivities request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcPendingActivitiesRequest struct {
	GroupID string `json:"group_id"`
	Limit   int    `json:"limit"`
}

// rpcPendingActivitiesResponse is the PendingActivities response on the wire.
type rpcPendingActivitiesResponse struct {
	rpcStatus
	Keys []Key `json:"keys"`
}

// rpcNotifyPhaseRequest is the NotifyPhase request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcNotifyPhaseRequest struct {
	Key     Key   `json:"key"`
	GameSID int32 `json:"game_sid"`
}

// rpcNotifyPhaseResponse is the NotifyPhase response on the wire.
type rpcNotifyPhaseResponse struct {
	rpcStatus
	Activity Activity `json:"activity"`
}

// rpcApplyProgressRequest is the ApplyProgress request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcApplyProgressRequest struct {
	Key           Key           `json:"key"`
	ParticipantID string        `json:"participant_id"`
	RequestID     string        `json:"request_id"`
	Delta         ProgressDelta `json:"delta"`
}

// rpcApplyProgressResponse is the ApplyProgress response on the wire.
type rpcApplyProgressResponse struct {
	rpcStatus
	Participant Participant `json:"participant"`
}

// rpcLookupParticipantRequest is the LookupParticipant request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcLookupParticipantRequest struct {
	Key           Key    `json:"key"`
	ParticipantID string `json:"participant_id"`
}

// rpcLookupParticipantResponse is the LookupParticipant response on the wire.
type rpcLookupParticipantResponse struct {
	rpcStatus
	Participant Participant `json:"participant"`
	Found       bool        `json:"found"`
}

// rpcReservationRequest is the Reservation request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcReservationRequest struct {
	Key           Key    `json:"key"`
	ParticipantID string `json:"participant_id"`
	RequestID     string `json:"request_id"`
}

// rpcReservationResponse is the Reservation response on the wire.
type rpcReservationResponse struct {
	rpcStatus
	Reservation ProgressReservation `json:"reservation"`
	Found       bool                `json:"found"`
}

// rpcOwedDispatchesRequest is the OwedDispatches request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcOwedDispatchesRequest struct {
	GroupID string `json:"group_id"`
	GameSID int32  `json:"game_sid"`
	Limit   int    `json:"limit"`
}

// rpcOwedDispatchesResponse is the OwedDispatches response on the wire.
type rpcOwedDispatchesResponse struct {
	rpcStatus
	Keys []Key `json:"keys"`
}

// rpcLookupDispatchRequest is the LookupDispatch request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcLookupDispatchRequest struct {
	Key     Key   `json:"key"`
	GameSID int32 `json:"game_sid"`
}

// rpcLookupDispatchResponse is the LookupDispatch response on the wire.
type rpcLookupDispatchResponse struct {
	rpcStatus
	Dispatch Dispatch `json:"dispatch"`
	Found    bool     `json:"found"`
}

// rpcAttemptDispatchRequest is the AttemptDispatch request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcAttemptDispatchRequest struct {
	Key     Key   `json:"key"`
	GameSID int32 `json:"game_sid"`
}

// rpcAttemptDispatchResponse is the AttemptDispatch response on the wire.
type rpcAttemptDispatchResponse struct {
	rpcStatus
	Dispatch Dispatch `json:"dispatch"`
}

// rpcAckDispatchRequest is the AckDispatch request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcAckDispatchRequest struct {
	Key     Key    `json:"key"`
	GameSID int32  `json:"game_sid"`
	Token   string `json:"token"`
}

// rpcAckDispatchResponse is the AckDispatch response on the wire.
type rpcAckDispatchResponse struct {
	rpcStatus
	Dispatch Dispatch `json:"dispatch"`
}

// --- server ---

// RegisterHandlers publishes Coordinator on a bus.
//
// It is called by the process that OWNS the service. The handlers decode and
// call the local implementation and contain no logic of their own: a check
// that lived here rather than in the service would apply only to remote
// callers, and a local caller would bypass it.
func RegisterHandlers(b bus.IBus, service Coordinator) error {
	if b == nil {
		return fmt.Errorf("activity: bus is nil")
	}
	if service == nil {
		return fmt.Errorf("activity: service is nil")
	}
	handlers := map[string]bus.RpcHandlerFunc{
		MethodOpenActivity: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcOpenActivityRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcOpenActivityResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			activity, err := service.OpenActivity(ctx.Context(), wire.Key, wire.ExpectedGameSIDs)
			return rpcOpenActivityResponse{rpcStatus: statusOf(err), Activity: activity}, nil
		},
		MethodLookupActivity: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcLookupActivityRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcLookupActivityResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			activity, found, err := service.LookupActivity(ctx.Context(), wire.Key)
			return rpcLookupActivityResponse{rpcStatus: statusOf(err), Activity: activity, Found: found}, nil
		},
		MethodPendingActivities: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcPendingActivitiesRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcPendingActivitiesResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			keys, err := service.PendingActivities(ctx.Context(), wire.GroupID, wire.Limit)
			return rpcPendingActivitiesResponse{rpcStatus: statusOf(err), Keys: keys}, nil
		},
		MethodNotifyPhase: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcNotifyPhaseRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcNotifyPhaseResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			activity, err := service.NotifyPhase(ctx.Context(), wire.Key, wire.GameSID)
			return rpcNotifyPhaseResponse{rpcStatus: statusOf(err), Activity: activity}, nil
		},
		MethodApplyProgress: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcApplyProgressRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcApplyProgressResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			participant, err := service.ApplyProgress(ctx.Context(), wire.Key, wire.ParticipantID, wire.RequestID, wire.Delta)
			return rpcApplyProgressResponse{rpcStatus: statusOf(err), Participant: participant}, nil
		},
		MethodLookupParticipant: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcLookupParticipantRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcLookupParticipantResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			participant, found, err := service.LookupParticipant(ctx.Context(), wire.Key, wire.ParticipantID)
			return rpcLookupParticipantResponse{rpcStatus: statusOf(err), Participant: participant, Found: found}, nil
		},
		MethodReservation: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcReservationRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcReservationResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			reservation, found, err := service.Reservation(ctx.Context(), wire.Key, wire.ParticipantID, wire.RequestID)
			return rpcReservationResponse{rpcStatus: statusOf(err), Reservation: reservation, Found: found}, nil
		},
		MethodOwedDispatches: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcOwedDispatchesRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcOwedDispatchesResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			keys, err := service.OwedDispatches(ctx.Context(), wire.GroupID, wire.GameSID, wire.Limit)
			return rpcOwedDispatchesResponse{rpcStatus: statusOf(err), Keys: keys}, nil
		},
		MethodLookupDispatch: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcLookupDispatchRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcLookupDispatchResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			dispatch, found, err := service.LookupDispatch(ctx.Context(), wire.Key, wire.GameSID)
			return rpcLookupDispatchResponse{rpcStatus: statusOf(err), Dispatch: dispatch, Found: found}, nil
		},
		MethodAttemptDispatch: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcAttemptDispatchRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcAttemptDispatchResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			dispatch, err := service.AttemptDispatch(ctx.Context(), wire.Key, wire.GameSID)
			return rpcAttemptDispatchResponse{rpcStatus: statusOf(err), Dispatch: dispatch}, nil
		},
		MethodAckDispatch: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcAckDispatchRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcAckDispatchResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			dispatch, err := service.AckDispatch(ctx.Context(), wire.Key, wire.GameSID, wire.Token)
			return rpcAckDispatchResponse{rpcStatus: statusOf(err), Dispatch: dispatch}, nil
		},
	}
	// Registered against Methods rather than by ranging the map, so a method
	// the interface declares and the table misses fails HERE, with a name.
	for _, method := range Methods {
		handler, ok := handlers[method]
		if !ok {
			return fmt.Errorf("activity: no handler for %s", method)
		}
		if err := b.HandleRpc(method, handler); err != nil {
			return fmt.Errorf("activity: register %s: %w", method, err)
		}
	}
	if len(handlers) != len(Methods) {
		return fmt.Errorf("activity: %d handlers for %d methods", len(handlers), len(Methods))
	}
	return nil
}

// --- client ---

// DefaultCallTimeout bounds one RPC. A call with no timeout is a goroutine
// waiting on a process that may never answer.
const DefaultCallTimeout = 3 * time.Second

// BusClient is Coordinator over a bus, for the processes that do not own this
// service.
//
// Its method signatures are the interface's, identity included: a caller still
// has to say whose identity it is, and the wire types are this type's
// implementation detail.
type BusClient struct {
	rpc *servicerpc.BusClient
}

// NewBusClient builds a client. serviceType empty means ServiceType; timeout
// non-positive means DefaultCallTimeout.
func NewBusClient(b bus.IBus, serviceType string, timeout time.Duration, opts ...servicerpc.Option) (*BusClient, error) {
	if b == nil {
		return nil, fmt.Errorf("activity: bus is nil")
	}
	if serviceType == "" {
		serviceType = ServiceType
	}
	if timeout <= 0 {
		timeout = DefaultCallTimeout
	}
	// At least one method routes by key, so the picker that reads the key is
	// installed here rather than left to each deployment to remember. A
	// caller's own options come after, so it can still override.
	//
	// This matters for a specific reason: a service whose state is partitioned
	// across instances — a queue kept whole in one key, say — has its
	// throughput bounded by contention on that key, and round-robin routing
	// turns that bound into cross-replica contention. Routing by key makes the
	// contention in-process instead. It is the difference between a design
	// cost and a design defect.
	options := append([]servicerpc.Option{
		servicerpc.WithKeyAffinity(servicerpc.AffinityKeyFromContext),
	}, opts...)
	return &BusClient{rpc: servicerpc.NewBusClient(b, serviceType, timeout, options...)}, nil
}

func (c *BusClient) call(ctx context.Context, method string, req any, resp any) error {
	if c == nil || c.rpc == nil {
		return fmt.Errorf("activity: client is not configured")
	}
	return c.rpc.CallChecked(ctx, 0, method, req, resp, "activity call failed")
}

// OpenActivity opens an activity for a named set of game servers. It is
// admitted through the group's pending window, so a group cannot
// accumulate unbounded open activities.
//
// OpenActivity implements Coordinator.
func (c *BusClient) OpenActivity(ctx context.Context, key Key, expectedGameSIDs []int32) (Activity, error) {
	// Routed by key.Group(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, key.Group())
	var resp rpcOpenActivityResponse
	err := c.call(ctx, MethodOpenActivity, rpcOpenActivityRequest{
		Key:              key,
		ExpectedGameSIDs: expectedGameSIDs,
	}, &resp)
	return resp.Activity, err
}

// LookupActivity reads one activity.
//
// LookupActivity implements Coordinator.
func (c *BusClient) LookupActivity(ctx context.Context, key Key) (Activity, bool, error) {
	// Routed by key.Group(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, key.Group())
	var resp rpcLookupActivityResponse
	err := c.call(ctx, MethodLookupActivity, rpcLookupActivityRequest{
		Key: key,
	}, &resp)
	return resp.Activity, resp.Found, err
}

// PendingActivities lists a group's activities that are not finished. It
// is the only enumerable index of them, and it is bounded.
//
// PendingActivities implements Coordinator.
func (c *BusClient) PendingActivities(ctx context.Context, groupID string, limit int) ([]Key, error) {
	// Routed by groupID: every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, groupID)
	var resp rpcPendingActivitiesResponse
	err := c.call(ctx, MethodPendingActivities, rpcPendingActivitiesRequest{
		GroupID: groupID,
		Limit:   limit,
	}, &resp)
	return resp.Keys, err
}

// NotifyPhase records that one game server reached the phase. This
// service never advances an activity from its own clock; a game's
// notification is what starts the grace window.
//
// NotifyPhase implements Coordinator.
func (c *BusClient) NotifyPhase(ctx context.Context, key Key, gameSID int32) (Activity, error) {
	// Routed by key.Group(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, key.Group())
	var resp rpcNotifyPhaseResponse
	err := c.call(ctx, MethodNotifyPhase, rpcNotifyPhaseRequest{
		Key:     key,
		GameSID: gameSID,
	}, &resp)
	return resp.Activity, err
}

// ApplyProgress adds a participant's progress, exactly once per
// requestID. The reservation is claimed insert-only before the score
// moves, so a redelivery cannot count twice.
//
// ApplyProgress implements Coordinator.
func (c *BusClient) ApplyProgress(ctx context.Context, key Key, participantID string, requestID string, delta ProgressDelta) (Participant, error) {
	// Routed by key.Group(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, key.Group())
	var resp rpcApplyProgressResponse
	err := c.call(ctx, MethodApplyProgress, rpcApplyProgressRequest{
		Key:           key,
		ParticipantID: participantID,
		RequestID:     requestID,
		Delta:         delta,
	}, &resp)
	return resp.Participant, err
}

// LookupParticipant reads one participant's accumulated progress.
//
// LookupParticipant implements Coordinator.
func (c *BusClient) LookupParticipant(ctx context.Context, key Key, participantID string) (Participant, bool, error) {
	// Routed by key.Group(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, key.Group())
	var resp rpcLookupParticipantResponse
	err := c.call(ctx, MethodLookupParticipant, rpcLookupParticipantRequest{
		Key:           key,
		ParticipantID: participantID,
	}, &resp)
	return resp.Participant, resp.Found, err
}

// Reservation reads what one requestID already did. It is how a caller
// that lost a response learns whether its progress landed, instead of
// retrying blind or giving up.
//
// Reservation implements Coordinator.
func (c *BusClient) Reservation(ctx context.Context, key Key, participantID string, requestID string) (ProgressReservation, bool, error) {
	// Routed by key.Group(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, key.Group())
	var resp rpcReservationResponse
	err := c.call(ctx, MethodReservation, rpcReservationRequest{
		Key:           key,
		ParticipantID: participantID,
		RequestID:     requestID,
	}, &resp)
	return resp.Reservation, resp.Found, err
}

// OwedDispatches lists the activities whose result this game server still
// owes an ack for, due now, oldest first.
//
// It is the entry point a game server drains on start and on a timer, and
// it exists because the alternative is guessing: before it, a game had to
// compute activity ids from its own clock and look each one up, which
// stops working the moment it is down longer than one window — the
// obligation stays recorded and becomes permanently unreachable
// (RR-20260919-10).
//
// The index is per (group, game), so this routes by group like every
// other call about an activity — a game that belongs to several groups
// drains each of them, and it knows which ones it belongs to because a
// binding is how it got there.
//
// OwedDispatches implements Coordinator.
func (c *BusClient) OwedDispatches(ctx context.Context, groupID string, gameSID int32, limit int) ([]Key, error) {
	// Routed by groupID: every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, groupID)
	var resp rpcOwedDispatchesResponse
	err := c.call(ctx, MethodOwedDispatches, rpcOwedDispatchesRequest{
		GroupID: groupID,
		GameSID: gameSID,
		Limit:   limit,
	}, &resp)
	return resp.Keys, err
}

// LookupDispatch reads the result delivery owed to one game server.
//
// LookupDispatch implements Coordinator.
func (c *BusClient) LookupDispatch(ctx context.Context, key Key, gameSID int32) (Dispatch, bool, error) {
	// Routed by key.Group(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, key.Group())
	var resp rpcLookupDispatchResponse
	err := c.call(ctx, MethodLookupDispatch, rpcLookupDispatchRequest{
		Key:     key,
		GameSID: gameSID,
	}, &resp)
	return resp.Dispatch, resp.Found, err
}

// AttemptDispatch takes the result owed to one game server and spends one
// of the delivery attempts.
//
// It returns the payload and the ack token. A caller that loses the reply
// asks again: the attempt is spent either way (that is what makes the
// budget a budget), but the result is unchanged and the token is the
// same, so nothing is delivered twice.
//
// AttemptDispatch implements Coordinator.
func (c *BusClient) AttemptDispatch(ctx context.Context, key Key, gameSID int32) (Dispatch, error) {
	// Routed by key.Group(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, key.Group())
	var resp rpcAttemptDispatchResponse
	err := c.call(ctx, MethodAttemptDispatch, rpcAttemptDispatchRequest{
		Key:     key,
		GameSID: gameSID,
	}, &resp)
	return resp.Dispatch, err
}

// AckDispatch is a game server confirming it applied the result. The
// token is required, so an ack cannot be forged from the activity key
// alone and a stale ack cannot close a redelivered dispatch.
//
// AckDispatch implements Coordinator.
func (c *BusClient) AckDispatch(ctx context.Context, key Key, gameSID int32, token string) (Dispatch, error) {
	// Routed by key.Group(): every call carrying the same key reaches the
	// same instance, so contention on that key stays in one process.
	ctx = servicerpc.WithAffinityKey(ctx, key.Group())
	var resp rpcAckDispatchResponse
	err := c.call(ctx, MethodAckDispatch, rpcAckDispatchRequest{
		Key:     key,
		GameSID: gameSID,
		Token:   token,
	}, &resp)
	return resp.Dispatch, err
}

// --- capability ---

// capability is what a Mod puts in the registry.
//
// It exists because converting to the interface at the registration call site
// does not do what it looks like it does: `Value: Coordinator(x)` stores an any
// whose dynamic type is still x's — Go does not box an interface inside an
// interface — so an assertion on the concrete type succeeds anyway. Wrapping
// the interface in a struct makes the dynamic type this wrapper, which
// satisfies Coordinator and nothing else.
//
// The consequence is the one that matters: a consumer cannot bind to the local
// implementation and then break on the day this service moves into its own
// process.
//
// It forwards each method explicitly rather than embedding the interface, and
// that is not style. Embedding names the field after the type, so an interface
// with a method of its own name — Rank.Rank, Match.Match — would have the
// field shadow the method and the wrapper would not satisfy the interface at
// all. The second service this generator ran against had exactly that shape.
type capability struct{ inner Coordinator }

func (c capability) OpenActivity(ctx context.Context, key Key, expectedGameSIDs []int32) (Activity, error) {
	return c.inner.OpenActivity(ctx, key, expectedGameSIDs)
}

func (c capability) LookupActivity(ctx context.Context, key Key) (Activity, bool, error) {
	return c.inner.LookupActivity(ctx, key)
}

func (c capability) PendingActivities(ctx context.Context, groupID string, limit int) ([]Key, error) {
	return c.inner.PendingActivities(ctx, groupID, limit)
}

func (c capability) NotifyPhase(ctx context.Context, key Key, gameSID int32) (Activity, error) {
	return c.inner.NotifyPhase(ctx, key, gameSID)
}

func (c capability) ApplyProgress(ctx context.Context, key Key, participantID string, requestID string, delta ProgressDelta) (Participant, error) {
	return c.inner.ApplyProgress(ctx, key, participantID, requestID, delta)
}

func (c capability) LookupParticipant(ctx context.Context, key Key, participantID string) (Participant, bool, error) {
	return c.inner.LookupParticipant(ctx, key, participantID)
}

func (c capability) Reservation(ctx context.Context, key Key, participantID string, requestID string) (ProgressReservation, bool, error) {
	return c.inner.Reservation(ctx, key, participantID, requestID)
}

func (c capability) OwedDispatches(ctx context.Context, groupID string, gameSID int32, limit int) ([]Key, error) {
	return c.inner.OwedDispatches(ctx, groupID, gameSID, limit)
}

func (c capability) LookupDispatch(ctx context.Context, key Key, gameSID int32) (Dispatch, bool, error) {
	return c.inner.LookupDispatch(ctx, key, gameSID)
}

func (c capability) AttemptDispatch(ctx context.Context, key Key, gameSID int32) (Dispatch, error) {
	return c.inner.AttemptDispatch(ctx, key, gameSID)
}

func (c capability) AckDispatch(ctx context.Context, key Key, gameSID int32, token string) (Dispatch, error) {
	return c.inner.AckDispatch(ctx, key, gameSID, token)
}

// Capability wraps a Coordinator for registration. Both Mods use it, so the
// capability's dynamic type is the same whichever process published it.
func Capability(service Coordinator) Coordinator { return capability{inner: service} }

// --- capability name ---

// CapabilityName is the registry key both Mods publish under.
//
// It is declared here, from the interface's marker, so the name and the
// transport that depends on it are one fact. A repository that also keeps a
// central table of capability names should assert equality against this
// constant rather than repeat the string — two literals of the same name is
// how a Mod ends up ordered by one and looked up by the other.
const CapabilityName app.ModName = "service.global.activity"

// LocalCapabilityName is published ONLY by the owning Mod, and it is how a
// process knows it owns this service.
//
// The alternative was to look up CapabilityName and ask whether the value is a
// *BusClient. That does not work, and finding out why is worth recording: the
// capability is deliberately wrapped so its dynamic type satisfies the
// interface and nothing else, which is exactly what defeats the assertion. The
// first version of this generator shipped that check, and the unit test for it
// passed only because it registered an unwrapped client — not what a Mod does.
//
// Asking "is the local implementation published here" is also the question
// that was actually meant. Type-sniffing for one particular remote
// implementation is a proxy for it, and a proxy that a wrapper, a test double
// or a future in-process forwarder each break differently.
const LocalCapabilityName app.ModName = "service.global.activity.local"

var (
	_ Coordinator = (*BusClient)(nil)
	_ Coordinator = capability{}
)
