// Code generated by roost-codegen. DO NOT EDIT.
package Game

import (
	"fmt"

	"github.com/tjbdwanghaibo/roost-core/app"
	svcaccount "github.com/tjbdwanghaibo/roost-core/kit/service/account"
	svcchat "github.com/tjbdwanghaibo/roost-core/kit/service/chat"
	svcglobal "github.com/tjbdwanghaibo/roost-core/kit/service/global"
	svcactivity "github.com/tjbdwanghaibo/roost-core/kit/service/global/activity"
	svcmail "github.com/tjbdwanghaibo/roost-core/kit/service/mail"
	svcmatch "github.com/tjbdwanghaibo/roost-core/kit/service/match"
	svcplatform "github.com/tjbdwanghaibo/roost-core/kit/service/platform"
	svcrank "github.com/tjbdwanghaibo/roost-core/kit/service/rank"
	svcsession "github.com/tjbdwanghaibo/roost-core/kit/service/session"
)

// Account returns the account service this process reaches through account.NewClientMod
// (roost.yaml: services.game.uses). Call it from Init and keep the result.
func Account(r *app.Registry) (svcaccount.Accounts, error) {
	service, ok := app.Lookup[svcaccount.Accounts](r, svcaccount.CapabilityName)
	if !ok || service == nil {
		return nil, fmt.Errorf("game: capability %q not found; is the account process running and reachable over the bus?", svcaccount.CapabilityName)
	}
	return service, nil
}

// Activity returns the activity service this process reaches through activity.NewClientMod
// (roost.yaml: services.game.uses). Call it from Init and keep the result.
func Activity(r *app.Registry) (svcactivity.Coordinator, error) {
	service, ok := app.Lookup[svcactivity.Coordinator](r, svcactivity.CapabilityName)
	if !ok || service == nil {
		return nil, fmt.Errorf("game: capability %q not found; is the activity process running and reachable over the bus?", svcactivity.CapabilityName)
	}
	return service, nil
}

// Chat returns the chat service this process reaches through chat.NewClientMod
// (roost.yaml: services.game.uses). Call it from Init and keep the result.
func Chat(r *app.Registry) (svcchat.Messaging, error) {
	service, ok := app.Lookup[svcchat.Messaging](r, svcchat.CapabilityName)
	if !ok || service == nil {
		return nil, fmt.Errorf("game: capability %q not found; is the chat process running and reachable over the bus?", svcchat.CapabilityName)
	}
	return service, nil
}

// Global returns the global service this process reaches through global.NewClientMod
// (roost.yaml: services.game.uses). Call it from Init and keep the result.
func Global(r *app.Registry) (svcglobal.Routing, error) {
	service, ok := app.Lookup[svcglobal.Routing](r, svcglobal.CapabilityName)
	if !ok || service == nil {
		return nil, fmt.Errorf("game: capability %q not found; is the global process running and reachable over the bus?", svcglobal.CapabilityName)
	}
	return service, nil
}

// Mail returns the mail service this process reaches through mail.NewClientMod
// (roost.yaml: services.game.uses). Call it from Init and keep the result.
func Mail(r *app.Registry) (svcmail.Mail, error) {
	service, ok := app.Lookup[svcmail.Mail](r, svcmail.CapabilityName)
	if !ok || service == nil {
		return nil, fmt.Errorf("game: capability %q not found; is the mail process running and reachable over the bus?", svcmail.CapabilityName)
	}
	return service, nil
}

// Match returns the match service this process reaches through match.NewClientMod
// (roost.yaml: services.game.uses). Call it from Init and keep the result.
func Match(r *app.Registry) (svcmatch.Matchmaker, error) {
	service, ok := app.Lookup[svcmatch.Matchmaker](r, svcmatch.CapabilityName)
	if !ok || service == nil {
		return nil, fmt.Errorf("game: capability %q not found; is the match process running and reachable over the bus?", svcmatch.CapabilityName)
	}
	return service, nil
}

// Platform returns the platform service this process reaches through platform.NewClientMod
// (roost.yaml: services.game.uses). Call it from Init and keep the result.
func Platform(r *app.Registry) (svcplatform.Platform, error) {
	service, ok := app.Lookup[svcplatform.Platform](r, svcplatform.CapabilityName)
	if !ok || service == nil {
		return nil, fmt.Errorf("game: capability %q not found; is the platform process running and reachable over the bus?", svcplatform.CapabilityName)
	}
	return service, nil
}

// Rank returns the rank service this process reaches through rank.NewClientMod
// (roost.yaml: services.game.uses). Call it from Init and keep the result.
func Rank(r *app.Registry) (svcrank.Rank, error) {
	service, ok := app.Lookup[svcrank.Rank](r, svcrank.CapabilityName)
	if !ok || service == nil {
		return nil, fmt.Errorf("game: capability %q not found; is the rank process running and reachable over the bus?", svcrank.CapabilityName)
	}
	return service, nil
}

// Session returns the session service this process reaches through session.NewClientMod
// (roost.yaml: services.game.uses). Call it from Init and keep the result.
func Session(r *app.Registry) (svcsession.Session, error) {
	service, ok := app.Lookup[svcsession.Session](r, svcsession.CapabilityName)
	if !ok || service == nil {
		return nil, fmt.Errorf("game: capability %q not found; is the session process running and reachable over the bus?", svcsession.CapabilityName)
	}
	return service, nil
}
