// Code generated by roost servicerpc. DO NOT EDIT.
//
// Generated from the Session interface in this package. The interface is
// the single source of truth: the wire types, the handler table and the client
// are all derived from it, so a method added to the interface cannot be
// forgotten in the transport — the failure this generator exists to make
// impossible rather than merely detectable.
//
// This file is the transport half and depends on roost-core only. The
// assembly half — Server, OwnerCapabilities, ClientMod, which need
// roost-kit/mods for the Mod and capability names — is session_rpc_assembly_gen.go
// beside it. The split is what lets an interface move into a core domain
// package and take its wire types, handler table and BusClient along (M-10).
//
// Regenerate with:
//
//	go run github.com/tjbdwanghaibo/roost-codegen/cmd/servicerpc -dir .

package session

import (
	"context"
	"fmt"
	"time"

	"github.com/tjbdwanghaibo/roost-core/app"
	"github.com/tjbdwanghaibo/roost-core/bus"
	"github.com/tjbdwanghaibo/roost-core/servicerpc"
)

// ServiceType is the bus service type Session answers on. The client and
// the handlers key on it, so it is one constant rather than a string in two
// places.
const ServiceType = "session"

// The RPC method names, prefixed with the service type so a bus subject is
// unambiguous when several services register handlers on one connection.
const (
	MethodEnter   = "session.Enter"
	MethodAttach  = "session.Attach"
	MethodFinish  = "session.Finish"
	MethodLeave   = "session.Leave"
	MethodGet     = "session.Get"
	MethodCurrent = "session.Current"
)

// Methods is every method on Session, in interface order.
//
// RegisterHandlers iterates it, so a method with no handler fails at startup
// with a name rather than at the first call from another process.
var Methods = []string{
	MethodEnter,
	MethodAttach,
	MethodFinish,
	MethodLeave,
	MethodGet,
	MethodCurrent,
}

// rpcStatus is the envelope every response embeds.
//
// A business failure travels inside the envelope with this package's error
// code; a bus error means the call did not happen. A caller retrying the
// second and not the first is the difference between recovering and
// double-applying, which is why the two are never the same channel.
type rpcStatus struct {
	Code   int32  `json:"code"`
	Reason string `json:"reason,omitempty"`
}

// StatusCode implements servicerpc.ResponseStatusProvider. The methods are
// exported even though the type is not, which is what the assertion in
// servicerpc.CheckResponse needs.
func (s rpcStatus) StatusCode() int32 { return s.Code }

// StatusReason implements servicerpc.ResponseStatusProvider.
func (s rpcStatus) StatusReason() string { return s.Reason }

// statusOf renders an error using this package's Error, so a code that reaches
// a client is the same code a local caller reads off the error.
func statusOf(err error) rpcStatus {
	code, reason := Error(err)
	return rpcStatus{Code: code, Reason: reason}
}

// --- wire types ---

// rpcEnterRequest is the Enter request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcEnterRequest struct {
	OwnerID int64        `json:"owner_id"`
	Req     EnterRequest `json:"req"`
}

// rpcEnterResponse is the Enter response on the wire.
type rpcEnterResponse struct {
	rpcStatus
	Run Run `json:"run"`
}

// rpcAttachRequest is the Attach request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcAttachRequest struct {
	OwnerID  int64    `json:"owner_id"`
	RunID    string   `json:"run_id"`
	Resource Resource `json:"resource"`
}

// rpcAttachResponse is the Attach response on the wire.
type rpcAttachResponse struct {
	rpcStatus
	Run Run `json:"run"`
}

// rpcFinishRequest is the Finish request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcFinishRequest struct {
	OwnerID int64  `json:"owner_id"`
	RunID   string `json:"run_id"`
	State   State  `json:"state"`
	Outcome string `json:"outcome"`
}

// rpcFinishResponse is the Finish response on the wire.
type rpcFinishResponse struct {
	rpcStatus
	Run Run `json:"run"`
}

// rpcLeaveRequest is the Leave request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcLeaveRequest struct {
	OwnerID int64  `json:"owner_id"`
	RunID   string `json:"run_id"`
	Reason  string `json:"reason"`
}

// rpcLeaveResponse is the Leave response on the wire.
type rpcLeaveResponse struct {
	rpcStatus
	Run Run `json:"run"`
}

// rpcGetRequest is the Get request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcGetRequest struct {
	OwnerID int64  `json:"owner_id"`
	RunID   string `json:"run_id"`
}

// rpcGetResponse is the Get response on the wire.
type rpcGetResponse struct {
	rpcStatus
	Run   Run  `json:"run"`
	Found bool `json:"found"`
}

// rpcCurrentRequest is the Current request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcCurrentRequest struct {
	OwnerID int64 `json:"owner_id"`
}

// rpcCurrentResponse is the Current response on the wire.
type rpcCurrentResponse struct {
	rpcStatus
	Run   Run  `json:"run"`
	Found bool `json:"found"`
}

// --- server ---

// RegisterHandlers publishes Session on a bus.
//
// It is called by the process that OWNS the service. The handlers decode and
// call the local implementation and contain no logic of their own: a check
// that lived here rather than in the service would apply only to remote
// callers, and a local caller would bypass it.
func RegisterHandlers(b bus.IBus, service Session) error {
	if b == nil {
		return fmt.Errorf("session: bus is nil")
	}
	if service == nil {
		return fmt.Errorf("session: service is nil")
	}
	handlers := map[string]bus.RpcHandlerFunc{
		MethodEnter: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcEnterRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcEnterResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, err := service.Enter(ctx.Context(), wire.OwnerID, wire.Req)
			return rpcEnterResponse{rpcStatus: statusOf(err), Run: run}, nil
		},
		MethodAttach: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcAttachRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcAttachResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, err := service.Attach(ctx.Context(), wire.OwnerID, wire.RunID, wire.Resource)
			return rpcAttachResponse{rpcStatus: statusOf(err), Run: run}, nil
		},
		MethodFinish: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcFinishRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcFinishResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, err := service.Finish(ctx.Context(), wire.OwnerID, wire.RunID, wire.State, wire.Outcome)
			return rpcFinishResponse{rpcStatus: statusOf(err), Run: run}, nil
		},
		MethodLeave: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcLeaveRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcLeaveResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, err := service.Leave(ctx.Context(), wire.OwnerID, wire.RunID, wire.Reason)
			return rpcLeaveResponse{rpcStatus: statusOf(err), Run: run}, nil
		},
		MethodGet: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcGetRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcGetResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, found, err := service.Get(ctx.Context(), wire.OwnerID, wire.RunID)
			return rpcGetResponse{rpcStatus: statusOf(err), Run: run, Found: found}, nil
		},
		MethodCurrent: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcCurrentRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcCurrentResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			run, found, err := service.Current(ctx.Context(), wire.OwnerID)
			return rpcCurrentResponse{rpcStatus: statusOf(err), Run: run, Found: found}, nil
		},
	}
	// Registered against Methods rather than by ranging the map, so a method
	// the interface declares and the table misses fails HERE, with a name.
	for _, method := range Methods {
		handler, ok := handlers[method]
		if !ok {
			return fmt.Errorf("session: no handler for %s", method)
		}
		if err := b.HandleRpc(method, handler); err != nil {
			return fmt.Errorf("session: register %s: %w", method, err)
		}
	}
	if len(handlers) != len(Methods) {
		return fmt.Errorf("session: %d handlers for %d methods", len(handlers), len(Methods))
	}
	return nil
}

// --- client ---

// DefaultCallTimeout bounds one RPC. A call with no timeout is a goroutine
// waiting on a process that may never answer.
const DefaultCallTimeout = 3 * time.Second

// BusClient is Session over a bus, for the processes that do not own this
// service.
//
// Its method signatures are the interface's, identity included: a caller still
// has to say whose identity it is, and the wire types are this type's
// implementation detail.
type BusClient struct {
	rpc *servicerpc.BusClient
}

// NewBusClient builds a client. serviceType empty means ServiceType; timeout
// non-positive means DefaultCallTimeout.
func NewBusClient(b bus.IBus, serviceType string, timeout time.Duration, opts ...servicerpc.Option) (*BusClient, error) {
	if b == nil {
		return nil, fmt.Errorf("session: bus is nil")
	}
	if serviceType == "" {
		serviceType = ServiceType
	}
	if timeout <= 0 {
		timeout = DefaultCallTimeout
	}
	return &BusClient{rpc: servicerpc.NewBusClient(b, serviceType, timeout, opts...)}, nil
}

func (c *BusClient) call(ctx context.Context, method string, req any, resp any) error {
	if c == nil || c.rpc == nil {
		return fmt.Errorf("session: client is not configured")
	}
	return c.rpc.CallChecked(ctx, 0, method, req, resp, "session call failed")
}

// Enter opens a run for an owner. Idempotent per RequestID, which is
// required: without it a retry allocates a second run, and the older one
// becomes unreachable.
// Enter implements Session.
func (c *BusClient) Enter(ctx context.Context, ownerID int64, req EnterRequest) (Run, error) {
	var resp rpcEnterResponse
	err := c.call(ctx, MethodEnter, rpcEnterRequest{
		OwnerID: ownerID,
		Req:     req,
	}, &resp)
	return resp.Run, err
}

// Attach records an external resource on a run, so releasing it later is
// walking a list rather than a hand-written unwind per failure path.
// Attach implements Session.
func (c *BusClient) Attach(ctx context.Context, ownerID int64, runID string, resource Resource) (Run, error) {
	var resp rpcAttachResponse
	err := c.call(ctx, MethodAttach, rpcAttachRequest{
		OwnerID:  ownerID,
		RunID:    runID,
		Resource: resource,
	}, &resp)
	return resp.Run, err
}

// Finish resolves a run to a terminal state the caller chooses and
// releases its resources.
// Finish implements Session.
func (c *BusClient) Finish(ctx context.Context, ownerID int64, runID string, state State, outcome string) (Run, error) {
	var resp rpcFinishResponse
	err := c.call(ctx, MethodFinish, rpcFinishRequest{
		OwnerID: ownerID,
		RunID:   runID,
		State:   state,
		Outcome: outcome,
	}, &resp)
	return resp.Run, err
}

// Leave abandons a run.
// Leave implements Session.
func (c *BusClient) Leave(ctx context.Context, ownerID int64, runID string, reason string) (Run, error) {
	var resp rpcLeaveResponse
	err := c.call(ctx, MethodLeave, rpcLeaveRequest{
		OwnerID: ownerID,
		RunID:   runID,
		Reason:  reason,
	}, &resp)
	return resp.Run, err
}

// Get reads a run. An elapsed deadline reads as expired before anything
// sweeps, so a caller never sees a run that is only open because nothing
// has resolved it yet.
// Get implements Session.
func (c *BusClient) Get(ctx context.Context, ownerID int64, runID string) (Run, bool, error) {
	var resp rpcGetResponse
	err := c.call(ctx, MethodGet, rpcGetRequest{
		OwnerID: ownerID,
		RunID:   runID,
	}, &resp)
	return resp.Run, resp.Found, err
}

// Current returns an owner's live run, if any. This is the index whose
// absence made a leaked run unreachable in the implementation this
// replaces.
// Current implements Session.
func (c *BusClient) Current(ctx context.Context, ownerID int64) (Run, bool, error) {
	var resp rpcCurrentResponse
	err := c.call(ctx, MethodCurrent, rpcCurrentRequest{
		OwnerID: ownerID,
	}, &resp)
	return resp.Run, resp.Found, err
}

// --- capability ---

// capability is what a Mod puts in the registry.
//
// It exists because converting to the interface at the registration call site
// does not do what it looks like it does: `Value: Session(x)` stores an any
// whose dynamic type is still x's — Go does not box an interface inside an
// interface — so an assertion on the concrete type succeeds anyway. Wrapping
// the interface in a struct makes the dynamic type this wrapper, which
// satisfies Session and nothing else.
//
// The consequence is the one that matters: a consumer cannot bind to the local
// implementation and then break on the day this service moves into its own
// process.
//
// It forwards each method explicitly rather than embedding the interface, and
// that is not style. Embedding names the field after the type, so an interface
// with a method of its own name — Rank.Rank, Match.Match — would have the
// field shadow the method and the wrapper would not satisfy the interface at
// all. The second service this generator ran against had exactly that shape.
type capability struct{ inner Session }

func (c capability) Enter(ctx context.Context, ownerID int64, req EnterRequest) (Run, error) {
	return c.inner.Enter(ctx, ownerID, req)
}

func (c capability) Attach(ctx context.Context, ownerID int64, runID string, resource Resource) (Run, error) {
	return c.inner.Attach(ctx, ownerID, runID, resource)
}

func (c capability) Finish(ctx context.Context, ownerID int64, runID string, state State, outcome string) (Run, error) {
	return c.inner.Finish(ctx, ownerID, runID, state, outcome)
}

func (c capability) Leave(ctx context.Context, ownerID int64, runID string, reason string) (Run, error) {
	return c.inner.Leave(ctx, ownerID, runID, reason)
}

func (c capability) Get(ctx context.Context, ownerID int64, runID string) (Run, bool, error) {
	return c.inner.Get(ctx, ownerID, runID)
}

func (c capability) Current(ctx context.Context, ownerID int64) (Run, bool, error) {
	return c.inner.Current(ctx, ownerID)
}

// Capability wraps a Session for registration. Both Mods use it, so the
// capability's dynamic type is the same whichever process published it.
func Capability(service Session) Session { return capability{inner: service} }

// --- capability name ---

// CapabilityName is the registry key both Mods publish under.
//
// It is declared here, from the interface's marker, so the name and the
// transport that depends on it are one fact. A repository that also keeps a
// central table of capability names should assert equality against this
// constant rather than repeat the string — two literals of the same name is
// how a Mod ends up ordered by one and looked up by the other.
const CapabilityName app.ModName = "service.session"

// LocalCapabilityName is published ONLY by the owning Mod, and it is how a
// process knows it owns this service.
//
// The alternative was to look up CapabilityName and ask whether the value is a
// *BusClient. That does not work, and finding out why is worth recording: the
// capability is deliberately wrapped so its dynamic type satisfies the
// interface and nothing else, which is exactly what defeats the assertion. The
// first version of this generator shipped that check, and the unit test for it
// passed only because it registered an unwrapped client — not what a Mod does.
//
// Asking "is the local implementation published here" is also the question
// that was actually meant. Type-sniffing for one particular remote
// implementation is a proxy for it, and a proxy that a wrapper, a test double
// or a future in-process forwarder each break differently.
const LocalCapabilityName app.ModName = "service.session.local"

var (
	_ Session = (*BusClient)(nil)
	_ Session = capability{}
)
