// Code generated by roost-codegen cfggen. DO NOT EDIT.
//
// Source: the cfggen schema meta file. Regenerate with:
//
//	cfggen -meta <schema> -out <this directory>
package cfg

import (
	"strconv"

	"github.com/tjbdwanghaibo/roost-core/configdata"
)

type DropItem struct {
	ItemID int32 `json:"item_id"`
	Weight int32 `json:"weight"`
}

// DropCfg is 掉落组.
type DropCfg struct {
	ID    int32      `json:"id" cfg:"key"`
	Items []DropItem `json:"items"`
}

// MonsterCfg is 怪物表.
type MonsterCfg struct {
	ID      int32  `json:"id" cfg:"key"`
	Name    string `json:"name"`
	SceneID int32  `json:"scene_id" cfg:"index"`
	DropID  int32  `json:"drop_id" cfg:"ref=drop"`
}

// WorldCfg is the world global singleton config.
type WorldCfg struct {
	Width  int32 `json:"width"`
	Height int32 `json:"height"`
}

// RegisterGeneratedConfigData registers every table and object defined in
// the schema meta file on the given registry.
func RegisterGeneratedConfigData(r *configdata.Registry) error {
	if err := configdata.RegisterAutoTable[int32, DropCfg](r, configdata.WithAutoName("drop"), configdata.WithAutoFile("drop.json")); err != nil {
		return err
	}
	if err := configdata.RegisterAutoTable[int32, MonsterCfg](r, configdata.WithAutoName("monster"), configdata.WithAutoFile("monster.json")); err != nil {
		return err
	}
	if err := configdata.RegisterObject(r, configdata.ObjectDef[WorldCfg]{Name: "world", File: "world.json"}); err != nil {
		return err
	}
	return nil
}

// MustRegisterGeneratedConfigData is RegisterGeneratedConfigData panicking on error.
func MustRegisterGeneratedConfigData(r *configdata.Registry) {
	if err := RegisterGeneratedConfigData(r); err != nil {
		panic(err)
	}
}

// DropTableFrom returns table drop from a snapshot.
func DropTableFrom(snap *configdata.Snapshot) (*configdata.Table[int32, DropCfg], bool) {
	return configdata.TableFrom[int32, DropCfg](snap, "drop")
}

// MonsterTableFrom returns table monster from a snapshot.
func MonsterTableFrom(snap *configdata.Snapshot) (*configdata.Table[int32, MonsterCfg], bool) {
	return configdata.TableFrom[int32, MonsterCfg](snap, "monster")
}

// MonsterBySceneID returns the monster rows whose scene_id equals sceneID.
func MonsterBySceneID(snap *configdata.Snapshot, sceneID int32) []MonsterCfg {
	table, ok := MonsterTableFrom(snap)
	if !ok {
		return nil
	}
	return table.GetByIndex("scene_id", strconv.FormatInt(int64(sceneID), 10))
}

// WorldFrom returns the world global singleton config from a snapshot.
func WorldFrom(snap *configdata.Snapshot) (WorldCfg, bool) {
	return configdata.ObjectFrom[WorldCfg](snap, "world")
}
