// Code generated by tool/entity. DO NOT EDIT.
package player

import (
	"fmt"
	"sync"

	db "example.com/planet/db"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var registerPlayerEntityOnce sync.Once

// RegisterEntity registers every entity generated in this package
// (Player). It is the package's single registry entry point;
// each entity keeps its own once-guarded registration below.
//
//roost:register phase=entity
func RegisterEntity() {
	registerPlayerEntity()
}

// registerPlayerEntity registers the Player entity builder.
func registerPlayerEntity() {
	registerPlayerEntityOnce.Do(func() {
		entity.RegisterEntityBuilder(&entity.EntityBuilderParam{
			Category: entity.EntityCategoryPlayer,
			Kind:     EntityKindPlayer,
			Builder: func(param *entity.EntityCreateParam) (entity.IThreadSafeEntity, error) {
				return NewPlayer(param)
			},
			DaoBuilders: []entity.DaoBuilderFunc{
				func() entity.DaoInterface { return db.NewPlayerDao() },
			},
			NoPersist:    false,
			RemotePolicy: entity.RemotePolicyNone,
			Lifetime:     entity.EntityLifetimePersistedHotCold,
			Sync: entity.EntitySyncBuilderParam{
				Enabled:       true,
				Namespace:     "player",
				PackerFactory: NewPlayerSyncPacker,
			},
		})
	})
}

func NewPlayer(param *entity.EntityCreateParam) (*Player, error) {
	e := &Player{}
	if err := param.NormalizeID(EntityKindPlayer); err != nil {
		return nil, err
	}

	// EntityBase
	e.EntityBase = entity.NewEntityBaseWithMutex(param.Id, param.Category, false, param.Mutex, param.Kind)
	e.EntityBase.SetHooks(e.generatedOnClear, e.generatedOnDestroy)

	// ComponentManager
	e.ComponentManager = entity.NewComponentManager()

	// DaoManager
	e.DaoManager = entity.NewDaoManager()

	// DAO: dao
	if raw, ok := param.Dao[db.PlayerDaoCollection]; ok {
		e.dao = raw.(*db.PlayerDao)
	} else {
		e.dao = db.NewPlayerDao()
		e.dao.SetId(param.StorageID())
	}
	if e.dao != nil {
		e.DaoManager.Set(db.PlayerDaoCollection, e.dao)
	}

	// Component: profile
	if comp, err := entity.CreateComponent(CompTypeProfile, e, param); err != nil {
		return nil, err
	} else {
		e.profile = comp.(*ProfileComponent)
	}
	e.ComponentManager.Set(CompTypeProfile, e.profile)

	// Component: bag
	if comp, err := entity.CreateComponent(CompTypeBag, e, param); err != nil {
		return nil, err
	} else {
		e.bag = comp.(*BagComponent)
	}
	e.ComponentManager.Set(CompTypeBag, e.bag)

	// Component: attr
	if comp, err := entity.CreateComponent(CompTypeAttribute, e, param); err != nil {
		return nil, err
	} else {
		e.attr = comp.(*AttributeComponent)
	}
	e.ComponentManager.Set(CompTypeAttribute, e.attr)

	// Component: mapComp
	if comp, err := entity.CreateComponent(CompTypeMap, e, param); err != nil {
		return nil, err
	} else {
		e.mapComp = comp.(*MapComponent)
	}
	e.ComponentManager.Set(CompTypeMap, e.mapComp)

	// Component: gear
	if comp, err := entity.CreateComponent(CompTypeEquipment, e, param); err != nil {
		return nil, err
	} else {
		e.gear = comp.(*EquipmentComponent)
	}
	e.ComponentManager.Set(CompTypeEquipment, e.gear)

	// Initialize all components in dependency order
	if err := e.ComponentManager.InitAll(param, param.IsCreate); err != nil {
		return nil, err
	}

	return e, nil
}
func (e *Player) Base() *entity.EntityBase { return e.EntityBase }

func (e *Player) ProfileComp() *ProfileComponent { return e.profile }

func (e *Player) BagComp() *BagComponent { return e.bag }

func (e *Player) AttributeComp() *AttributeComponent { return e.attr }

func (e *Player) MapComp() *MapComponent { return e.mapComp }

func (e *Player) EquipmentComp() *EquipmentComponent { return e.gear }

func (e *Player) Dao() *db.PlayerDao { return e.dao }

// TakeEntitySyncChanges 由 Nest 在成功准入且仍持锁时调用；服务间同步保留独立掩码。
func (e *Player) TakeEntitySyncChanges() uint64 {
	var mask uint64
	if e.dao != nil {
		mask |= entity.MapDAOSyncChanges(e, db.PlayerDaoCollection, e.dao.DirtyTracker().TakeEntitySyncDirty(), true)
	}
	return mask
}

func (e *Player) generatedOnClear() {
	e.ComponentManager.Clear()
	e.DaoManager.Clear()
	e.profile = nil
	e.bag = nil
	e.attr = nil
	e.mapComp = nil
	e.gear = nil
	e.dao = nil
}

func (e *Player) generatedOnDestroy(reason entity.EntityDestroyReason) {
	e.ComponentManager.DestroyAll(reason)
}

// PrepareDelete registers versioned tombstones in the active Nest transaction.
func (e *Player) PrepareDelete(tx *nest.RollbackTx) error {
	if tx == nil {
		return nest.ErrTransactionClosed
	}
	if e.dao != nil {
		participant, ok := any(e.dao).(nest.MutationParticipant)
		if !ok {
			return fmt.Errorf("Player: DAO player does not implement nest.MutationParticipant")
		}
		if err := tx.MarkPersistDelete(participant); err != nil {
			return err
		}
	}
	return nil
}
