# Code generated by roost-codegen. DO NOT EDIT.
APP_NAME := planet
CODEGEN_MODULE := github.com/tjbdwanghaibo/roost-core/codegen
CODEGEN_VERSION ?= latest
ROOST := go run $(CODEGEN_MODULE)/cmd/roost@$(CODEGEN_VERSION)
SERVICE ?= account
ENTITY ?=
COMPONENT ?=
HANDLER ?=
PROTOCOL ?=
NEST_HANDLER ?=
NEXT_WORKFLOW ?=
SID ?= 1000
CONFIG ?= configs/service/config.$(SERVICE).yaml
VERSION ?= dev
ENV ?= staging
IMAGE ?=
ENV_FILE ?= deploy/docker/.env.production
WORKLOAD ?=
COMMIT := $(shell git rev-parse --short HEAD)
BUILD_TIME := $(shell git show -s --format=%cI HEAD)
DIRTY := $(shell git status --porcelain)
LDFLAGS := -X github.com/tjbdwanghaibo/roost-core/app/buildinfo.Version=$(VERSION) -X github.com/tjbdwanghaibo/roost-core/app/buildinfo.Commit=$(COMMIT) -X github.com/tjbdwanghaibo/roost-core/app/buildinfo.BuildTime=$(BUILD_TIME) -X github.com/tjbdwanghaibo/roost-core/app/buildinfo.Dirty=$(DIRTY)

LOADTEST_ENDPOINT ?= 127.0.0.1:7000
LOADTEST_COUNT ?= 10
LOADTEST_METRICS_ADDR ?= 127.0.0.1:9300
LOADTEST_ACCOUNT_NATS ?= nats://127.0.0.1:4222

.PHONY: help sync project-upgrade deps-update roost-up codegen-up next doctor fmt fmt-check vet glsvet test test-race build run loadtest generate generate-changed check-generated config-check config-check-all player-tcp-enable player-tcp-disable id-check ci cicd-check release-check image-build compose-check k8s-render k8s-check deploy-shell rollback-shell deploy-docker rollback-docker deploy-k8s rollback-k8s dev-up dev-down dev-logs dev-run dev-stop dev-status dev-smoke clean
.PHONY: new-service add-mod new-access new-transport new-module new-protocol new-entity new-component new-handler new-lifecycle new-endpoint new-skill new-event new-table new-dao new-webroute new-errcode new-saga new-rpc

help:
	$(ROOST) help-make
sync:
	$(ROOST) project sync
project-upgrade:
	go run $(CODEGEN_MODULE)/cmd/roost@latest project upgrade --root . -core latest -kit latest -codegen latest
deps-update:
	$(ROOST) project deps
roost-up:
	GOWORK=off go get -u ./...
	GOWORK=off go mod tidy
codegen-up:
	go install $(CODEGEN_MODULE)/cmd/roost@latest
next:
	$(ROOST) project next $(if $(NEXT_WORKFLOW),--workflow $(NEXT_WORKFLOW),)
doctor:
	$(ROOST) project doctor
fmt:
	go fmt ./...
fmt-check:
	$(ROOST) format check
vet:
	go vet ./...
glsvet:
	go run github.com/tjbdwanghaibo/roost-core/cmd/glsvet ./...
test:
	go test ./...
test-race:
	go test -race ./...
build:
	go build -ldflags "$(LDFLAGS)" ./...
run:
	go run . $(SERVICE) --sid $(SID) --config $(CONFIG)
loadtest:
	@test -d cmd/loadtest || { echo "cmd/loadtest is not part of this project: generate with 'roost project new ... -template game-demo', or add your own robots under cmd/loadtest"; exit 1; }
	go run ./cmd/loadtest -endpoint $(LOADTEST_ENDPOINT) -count $(LOADTEST_COUNT) -metrics-addr $(LOADTEST_METRICS_ADDR) -account-nats $(LOADTEST_ACCOUNT_NATS) $(LOADTEST_ARGS)
generate:
	$(ROOST) generate
generate-changed:
	$(ROOST) generate --changed
check-generated:
	$(ROOST) generate --check
config-check:
	$(ROOST) config check --service $(SERVICE)
config-check-all:
	$(ROOST) config check --all
player-tcp-enable:
	$(ROOST) config enable player-tcp --service $(SERVICE)
player-tcp-disable:
	$(ROOST) config disable player-tcp --service $(SERVICE)
id-check:
	$(ROOST) id check
new-service:
	$(ROOST) add service $(NAME) -mods $(MODS)
add-mod:
	$(ROOST) add mod $(NAME) -service $(SERVICE)
new-access:
	$(ROOST) add access $(NAME) -service $(SERVICE)
new-transport:
	$(ROOST) add transport $(NAME) -service $(SERVICE)
new-module:
	$(ROOST) add module $(NAME)
new-protocol:
	$(ROOST) add protocol $(NAME) -group $(GROUP) $(if $(HANDLER),--handler $(HANDLER),)
new-entity:
	$(ROOST) add entity $(NAME)
new-component:
	$(ROOST) add component $(NAME) $(if $(ENTITY),--entity $(ENTITY),)
new-handler:
	$(ROOST) add handler $(NAME) --entity $(ENTITY) --component $(COMPONENT)
new-lifecycle:
	$(ROOST) add lifecycle $(NAME) $(if $(ENTITY),--entity $(ENTITY),) -service $(SERVICE)
new-endpoint:
	$(ROOST) add endpoint $(NAME) --handler $(HANDLER) $(if $(PROTOCOL),--protocol $(PROTOCOL),) $(if $(NEST_HANDLER),--nest-handler $(NEST_HANDLER),)
new-skill:
	$(ROOST) add skill $(NAME)
new-event:
	$(ROOST) add event $(NAME)
new-table:
	$(ROOST) add table $(NAME)
new-dao:
	$(ROOST) add dao $(NAME) $(if $(ENTITY),--entity $(ENTITY),)
new-webroute:
	$(ROOST) add webroute $(NAME)
new-errcode:
	$(ROOST) add errcode $(NAME)
new-saga:
	$(ROOST) add saga $(NAME) -service $(SERVICE) -steps $(STEPS)
new-rpc:
	$(ROOST) add rpc $(NAME) -service $(SERVICE)
ci: fmt-check vet glsvet test test-race check-generated config-check-all id-check
cicd-check: ci compose-check k8s-check
release-check: cicd-check
	@test -z "$(DIRTY)" || (echo "release requires a clean worktree"; exit 1)
	@echo "$(VERSION)" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$$' || (echo "VERSION must be vMAJOR.MINOR.PATCH"; exit 1)
image-build:
	docker build --build-arg VERSION=$(VERSION) --build-arg COMMIT=$(COMMIT) --build-arg BUILD_TIME=$(BUILD_TIME) -t $(APP_NAME):$(VERSION) .
compose-check:
	ROOST_IMAGE=ghcr.io/example/$(APP_NAME)@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ROOST_CONFIG_ROOT=$(CURDIR)/configs/service docker compose -f deploy/docker/docker-compose.prod.yaml config --quiet
k8s-render:
	kubectl kustomize deploy/k8s/overlays/$(ENV)
k8s-check:
	kubectl kustomize deploy/k8s/overlays/staging >/dev/null
	kubectl kustomize deploy/k8s/overlays/production >/dev/null
deploy-shell:
	sudo sh deploy/shell/install.sh $(SERVICE) $(SID) $(VERSION) $(CONFIG)
rollback-shell:
	sudo sh deploy/shell/rollback.sh $(SERVICE) $(SID) $(VERSION)
deploy-docker:
	ROOST_IMAGE=$(IMAGE) ROOST_ENV_FILE=$(ENV_FILE) sh deploy/docker/deploy.sh
rollback-docker:
	ROOST_ENV_FILE=$(ENV_FILE) sh deploy/docker/rollback.sh
deploy-k8s:
	ENVIRONMENT=$(ENV) ROOST_IMAGE=$(IMAGE) sh deploy/k8s/deploy.sh
rollback-k8s:
	kubectl -n roost rollout undo $(WORKLOAD)
dev-up:
	docker compose -f deploy/dev/docker-compose.yaml up -d
dev-down:
	docker compose -f deploy/dev/docker-compose.yaml down
dev-logs:
	docker compose -f deploy/dev/docker-compose.yaml logs -f
dev-run:
	sh deploy/dev/run.sh start
dev-stop:
	sh deploy/dev/run.sh stop
dev-status:
	sh deploy/dev/run.sh status
dev-smoke:
	@test -d cmd/loadtest || { echo "cmd/loadtest is not part of this project (game-demo template); run your own client against the services started by make dev-run"; exit 1; }
	go run ./cmd/loadtest -endpoint $(LOADTEST_ENDPOINT) -count 2 -account-nats $(LOADTEST_ACCOUNT_NATS) $(LOADTEST_ARGS)
clean:
	go clean
