// Code generated by roost-codegen. DO NOT EDIT.
package docker

// The production compose file is validated by `docker compose config --quiet`
// in CI, which only proves the YAML parses. A value that parses as the wrong
// shape — tmpfs: [/tmp:rw,noexec,nosuid,size=64m] splitting into four mounts
// at the commas (RR-20260927-33) — passes it and fails at compose up. This
// test reads what compose actually resolved and pins the fields the
// deployment relies on (RR-20260930-17).
//
// It runs only with ROOST_COMPOSE_CHECK set (make compose-check and the
// generated-and-deployment CI job set it), so go test ./... on a machine
// without docker is not blocked; with it set, a missing docker is a failure.

import (
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const (
	composeFile     = "docker-compose.prod.yaml"
	composeImage    = "ghcr.io/example/planet@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	configMountPath = "/etc/roost/config.yaml"
	tmpfsMount      = "/tmp:rw,noexec,nosuid,size=64m"
	runtimeUser     = "65532:65532"
	healthProbePath = "/app/healthprobe"
)

type composeProject struct {
	Services map[string]composeService  `json:"services"`
	Volumes  map[string]json.RawMessage `json:"volumes"`
}

type composeService struct {
	ReadOnly        bool     `json:"read_only"`
	User            string   `json:"user"`
	CapDrop         []string `json:"cap_drop"`
	SecurityOpt     []string `json:"security_opt"`
	Tmpfs           []string `json:"tmpfs"`
	StopGracePeriod string   `json:"stop_grace_period"`
	Healthcheck     struct {
		Test []string `json:"test"`
	} `json:"healthcheck"`
	Volumes []composeMount `json:"volumes"`
}

type composeMount struct {
	Type     string `json:"type"`
	Source   string `json:"source"`
	Target   string `json:"target"`
	ReadOnly bool   `json:"read_only"`
}

func TestProductionComposeResolvesToTheShapeTheDeploymentReliesOn(t *testing.T) {
	if os.Getenv("ROOST_COMPOSE_CHECK") == "" {
		t.Skip("set ROOST_COMPOSE_CHECK=1 (make compose-check does) to check the production compose through docker compose config")
	}
	configRoot, err := filepath.Abs(filepath.Join("..", "..", "configs", "service"))
	if err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("docker", "compose", "-f", composeFile, "config", "--format", "json")
	cmd.Env = append(os.Environ(), "ROOST_IMAGE="+composeImage, "ROOST_CONFIG_ROOT="+configRoot)
	out, err := cmd.Output()
	if err != nil {
		var exit *exec.ExitError
		if errors.As(err, &exit) {
			t.Fatalf("docker compose config: %v\n%s", err, exit.Stderr)
		}
		t.Fatalf("docker compose config: %v (docker with the compose plugin is required when ROOST_COMPOSE_CHECK is set)", err)
	}
	var project composeProject
	if err := json.Unmarshal(out, &project); err != nil {
		t.Fatalf("decode docker compose config --format json: %v\n%s", err, out)
	}
	if len(project.Services) == 0 {
		t.Fatalf("docker compose config resolved no services:\n%s", out)
	}
	for name, service := range project.Services {
		t.Run(name, func(t *testing.T) { checkComposeService(t, name, service, project.Volumes) })
	}
}

func checkComposeService(t *testing.T, name string, service composeService, declared map[string]json.RawMessage) {
	t.Helper()
	if !service.ReadOnly {
		t.Errorf("read_only is not true")
	}
	if service.User != runtimeUser {
		t.Errorf("user = %q, want %q (the distroless nonroot uid the image's writable directories belong to)", service.User, runtimeUser)
	}
	if len(service.CapDrop) != 1 || service.CapDrop[0] != "ALL" {
		t.Errorf("cap_drop = %q, want [ALL]", service.CapDrop)
	}
	if len(service.SecurityOpt) != 1 || service.SecurityOpt[0] != "no-new-privileges:true" {
		t.Errorf("security_opt = %q, want [no-new-privileges:true]", service.SecurityOpt)
	}
	// One mount with its options in the same item. An unquoted flow sequence
	// splits at the commas into "/tmp:rw", "noexec", "nosuid", "size=64m",
	// and compose up refuses "noexec" as a mount path (RR-20260927-33).
	switch {
	case len(service.Tmpfs) != 1:
		t.Errorf("tmpfs resolved to %d mounts %q, want exactly one (an unquoted flow sequence splits at the commas, RR-20260927-33)", len(service.Tmpfs), service.Tmpfs)
	case !strings.HasPrefix(service.Tmpfs[0], "/"):
		t.Errorf("tmpfs mount %q is not an absolute path", service.Tmpfs[0])
	case service.Tmpfs[0] != tmpfsMount:
		t.Errorf("tmpfs = %q, want %q", service.Tmpfs[0], tmpfsMount)
	}
	if grace, err := time.ParseDuration(service.StopGracePeriod); err != nil || grace <= 0 {
		t.Errorf("stop_grace_period = %q, want a positive duration (shutdown.total_timeout + 5s)", service.StopGracePeriod)
	}
	if test := service.Healthcheck.Test; len(test) < 3 || test[0] != "CMD" || test[1] != healthProbePath {
		t.Errorf("healthcheck.test = %q, want [CMD %s <url>] (the readiness probe the deploy scripts wait on)", test, healthProbePath)
	}
	configMounts := 0
	targets := map[string]bool{}
	for _, mount := range service.Volumes {
		if targets[mount.Target] {
			t.Errorf("two mounts at %s", mount.Target)
		}
		targets[mount.Target] = true
		if !strings.HasPrefix(mount.Target, "/") {
			t.Errorf("mount target %q is not absolute", mount.Target)
		}
		switch mount.Type {
		case "bind":
			if mount.Target != configMountPath {
				t.Errorf("unexpected bind mount %s -> %s; the only bind is the service config at %s", mount.Source, mount.Target, configMountPath)
				continue
			}
			configMounts++
			if !mount.ReadOnly {
				t.Errorf("the config mount at %s is not read-only", configMountPath)
			}
			if want := "config." + name + ".yaml"; filepath.Base(mount.Source) != want {
				t.Errorf("the config mount source is %q, want ROOST_CONFIG_ROOT/%s", mount.Source, want)
			}
		case "volume":
			if _, ok := declared[mount.Source]; !ok {
				t.Errorf("named volume %q at %s is not declared under top-level volumes", mount.Source, mount.Target)
			}
			if mount.ReadOnly {
				t.Errorf("named volume %q at %s is read-only; the process writes there", mount.Source, mount.Target)
			}
		default:
			t.Errorf("mount at %s has type %q, want bind (config) or volume", mount.Target, mount.Type)
		}
	}
	if configMounts != 1 {
		t.Errorf("%d bind mounts at %s, want exactly one (the service config)", configMounts, configMountPath)
	}
}
