// Code generated by roost servicerpc. DO NOT EDIT.
//
// Generated from the Rank interface in this package. The interface is
// the single source of truth: the wire types, the handler table and the client
// are all derived from it, so a method added to the interface cannot be
// forgotten in the transport — the failure this generator exists to make
// impossible rather than merely detectable.
//
// This file is the transport half and depends on roost-core only. The
// assembly half — Server, OwnerCapabilities, ClientMod, which need
// roost-kit/mods for the Mod and capability names — is rank_rpc_assembly_gen.go
// beside it. The split is what lets an interface move into a core domain
// package and take its wire types, handler table and BusClient along (M-10).
//
// Regenerate with:
//
//	go run github.com/tjbdwanghaibo/roost-core/codegen/cmd/servicerpc -dir .

package rank

import (
	"context"
	"fmt"
	"time"

	"github.com/tjbdwanghaibo/roost-core/app"
	"github.com/tjbdwanghaibo/roost-core/bus"
	"github.com/tjbdwanghaibo/roost-core/servicerpc"
)

// ServiceType is the bus service type Rank answers on. The client and
// the handlers key on it, so it is one constant rather than a string in two
// places.
const ServiceType = "rank"

// The RPC method names, prefixed with the service type so a bus subject is
// unambiguous when several services register handlers on one connection.
const (
	MethodSubmit = "rank.Submit"
	MethodRemove = "rank.Remove"
	MethodPage   = "rank.Page"
	MethodRank   = "rank.Rank"
	MethodAround = "rank.Around"
	MethodSize   = "rank.Size"
)

// Methods is every method on Rank, in interface order.
//
// RegisterHandlers iterates it, so a method with no handler fails at startup
// with a name rather than at the first call from another process.
var Methods = []string{
	MethodSubmit,
	MethodRemove,
	MethodPage,
	MethodRank,
	MethodAround,
	MethodSize,
}

// rpcStatus is the envelope every response embeds.
//
// A business failure travels inside the envelope with this package's error
// code; a bus error means the call did not happen. A caller retrying the
// second and not the first is the difference between recovering and
// double-applying, which is why the two are never the same channel.
type rpcStatus struct {
	Code   int32  `json:"code"`
	Reason string `json:"reason,omitempty"`
}

// StatusCode implements servicerpc.ResponseStatusProvider. The methods are
// exported even though the type is not, which is what the assertion in
// servicerpc.CheckResponse needs.
func (s rpcStatus) StatusCode() int32 { return s.Code }

// StatusReason implements servicerpc.ResponseStatusProvider.
func (s rpcStatus) StatusReason() string { return s.Reason }

// statusOf renders an error using this package's Error, so a code that reaches
// a client is the same code a local caller reads off the error.
func statusOf(err error) rpcStatus {
	code, reason := Error(err)
	return rpcStatus{Code: code, Reason: reason}
}

// --- wire types ---

// rpcSubmitRequest is the Submit request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcSubmitRequest struct {
	Board     Board      `json:"board"`
	Score     Score      `json:"score"`
	Mode      UpdateMode `json:"mode"`
	RequestID string     `json:"request_id"`
}

// rpcSubmitResponse is the Submit response on the wire.
type rpcSubmitResponse struct {
	rpcStatus
	Entry Entry `json:"entry"`
}

// rpcRemoveRequest is the Remove request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcRemoveRequest struct {
	Board   Board `json:"board"`
	OwnerID int64 `json:"owner_id"`
}

// rpcRemoveResponse is the Remove response on the wire.
type rpcRemoveResponse struct {
	rpcStatus
}

// rpcPageRequest is the Page request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcPageRequest struct {
	Board  Board `json:"board"`
	Offset int   `json:"offset"`
	Limit  int   `json:"limit"`
}

// rpcPageResponse is the Page response on the wire.
type rpcPageResponse struct {
	rpcStatus
	Page Page `json:"page"`
}

// rpcRankRequest is the Rank request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcRankRequest struct {
	Board   Board `json:"board"`
	OwnerID int64 `json:"owner_id"`
}

// rpcRankResponse is the Rank response on the wire.
type rpcRankResponse struct {
	rpcStatus
	Entry Entry `json:"entry"`
	Found bool  `json:"found"`
}

// rpcAroundRequest is the Around request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcAroundRequest struct {
	Board   Board `json:"board"`
	OwnerID int64 `json:"owner_id"`
	Radius  int   `json:"radius"`
}

// rpcAroundResponse is the Around response on the wire.
type rpcAroundResponse struct {
	rpcStatus
	Page Page `json:"page"`
}

// rpcSizeRequest is the Size request on the wire.
//
// Its fields are named after the interface method's PARAMETERS, so a payload
// says what the method says. The client takes those parameters as arguments,
// which is what keeps a caller's identity something the compiler asks for
// rather than a struct field whose zero value looks valid.
type rpcSizeRequest struct {
	Board Board `json:"board"`
}

// rpcSizeResponse is the Size response on the wire.
type rpcSizeResponse struct {
	rpcStatus
	Size int64 `json:"size"`
}

// --- server ---

// RegisterHandlers publishes Rank on a bus.
//
// It is called by the process that OWNS the service. The handlers decode and
// call the local implementation and contain no logic of their own: a check
// that lived here rather than in the service would apply only to remote
// callers, and a local caller would bypass it.
func RegisterHandlers(b bus.IBus, service Rank) error {
	if b == nil {
		return fmt.Errorf("rank: bus is nil")
	}
	if service == nil {
		return fmt.Errorf("rank: service is nil")
	}
	handlers := map[string]bus.RpcHandlerFunc{
		MethodSubmit: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcSubmitRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcSubmitResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			entry, err := service.Submit(ctx.Context(), wire.Board, wire.Score, wire.Mode, wire.RequestID)
			return rpcSubmitResponse{rpcStatus: statusOf(err), Entry: entry}, nil
		},
		MethodRemove: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcRemoveRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcRemoveResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			err := service.Remove(ctx.Context(), wire.Board, wire.OwnerID)
			return rpcRemoveResponse{rpcStatus: statusOf(err)}, nil
		},
		MethodPage: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcPageRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcPageResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			page, err := service.Page(ctx.Context(), wire.Board, wire.Offset, wire.Limit)
			return rpcPageResponse{rpcStatus: statusOf(err), Page: page}, nil
		},
		MethodRank: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcRankRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcRankResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			entry, found, err := service.Rank(ctx.Context(), wire.Board, wire.OwnerID)
			return rpcRankResponse{rpcStatus: statusOf(err), Entry: entry, Found: found}, nil
		},
		MethodAround: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcAroundRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcAroundResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			page, err := service.Around(ctx.Context(), wire.Board, wire.OwnerID, wire.Radius)
			return rpcAroundResponse{rpcStatus: statusOf(err), Page: page}, nil
		},
		MethodSize: func(ctx *bus.RpcContext) (any, error) {
			var wire rpcSizeRequest
			if err := ctx.Decode(&wire); err != nil {
				return rpcSizeResponse{rpcStatus: statusOf(fmt.Errorf("%w: %s", ErrRequestInvalid, err))}, nil
			}
			size, err := service.Size(ctx.Context(), wire.Board)
			return rpcSizeResponse{rpcStatus: statusOf(err), Size: size}, nil
		},
	}
	// Registered against Methods rather than by ranging the map, so a method
	// the interface declares and the table misses fails HERE, with a name.
	for _, method := range Methods {
		handler, ok := handlers[method]
		if !ok {
			return fmt.Errorf("rank: no handler for %s", method)
		}
		if err := b.HandleRpc(method, handler); err != nil {
			return fmt.Errorf("rank: register %s: %w", method, err)
		}
	}
	if len(handlers) != len(Methods) {
		return fmt.Errorf("rank: %d handlers for %d methods", len(handlers), len(Methods))
	}
	return nil
}

// --- client ---

// DefaultCallTimeout bounds one RPC. A call with no timeout is a goroutine
// waiting on a process that may never answer.
const DefaultCallTimeout = 3 * time.Second

// BusClient is Rank over a bus, for the processes that do not own this
// service.
//
// Its method signatures are the interface's, identity included: a caller still
// has to say whose identity it is, and the wire types are this type's
// implementation detail.
type BusClient struct {
	rpc *servicerpc.BusClient
}

// NewBusClient builds a client. serviceType empty means ServiceType; timeout
// non-positive means DefaultCallTimeout.
func NewBusClient(b bus.IBus, serviceType string, timeout time.Duration, opts ...servicerpc.Option) (*BusClient, error) {
	if b == nil {
		return nil, fmt.Errorf("rank: bus is nil")
	}
	if serviceType == "" {
		serviceType = ServiceType
	}
	if timeout <= 0 {
		timeout = DefaultCallTimeout
	}
	return &BusClient{rpc: servicerpc.NewBusClient(b, serviceType, timeout, opts...)}, nil
}

func (c *BusClient) call(ctx context.Context, method string, req any, resp any) error {
	if c == nil || c.rpc == nil {
		return fmt.Errorf("rank: client is not configured")
	}
	return c.rpc.CallChecked(ctx, 0, method, req, resp, "rank call failed")
}

// Submit applies one score under mode and returns the entry as stored.
// requestID makes the call idempotent, which is what makes UpdateAdd safe
// under at-least-once delivery — the confirmed defect it answers added
// the same battle's delta 2 to 20 times.
// Submit implements Rank.
func (c *BusClient) Submit(ctx context.Context, board Board, score Score, mode UpdateMode, requestID string) (Entry, error) {
	var resp rpcSubmitResponse
	err := c.call(ctx, MethodSubmit, rpcSubmitRequest{
		Board:     board,
		Score:     score,
		Mode:      mode,
		RequestID: requestID,
	}, &resp)
	return resp.Entry, err
}

// Remove deletes an owner's entry. Idempotent.
// Remove implements Rank.
func (c *BusClient) Remove(ctx context.Context, board Board, ownerID int64) error {
	var resp rpcRemoveResponse
	err := c.call(ctx, MethodRemove, rpcRemoveRequest{
		Board:   board,
		OwnerID: ownerID,
	}, &resp)
	return err
}

// Page reads a bounded window. limit must be in [1, MaxPageSize] — a
// non-positive limit is an error, never "unlimited".
// Page implements Rank.
func (c *BusClient) Page(ctx context.Context, board Board, offset int, limit int) (Page, error) {
	var resp rpcPageResponse
	err := c.call(ctx, MethodPage, rpcPageRequest{
		Board:  board,
		Offset: offset,
		Limit:  limit,
	}, &resp)
	return resp.Page, err
}

// Rank reads one owner's entry.
// Rank implements Rank.
func (c *BusClient) Rank(ctx context.Context, board Board, ownerID int64) (Entry, bool, error) {
	var resp rpcRankResponse
	err := c.call(ctx, MethodRank, rpcRankRequest{
		Board:   board,
		OwnerID: ownerID,
	}, &resp)
	return resp.Entry, resp.Found, err
}

// Around reads the window centred on one owner.
// Around implements Rank.
func (c *BusClient) Around(ctx context.Context, board Board, ownerID int64, radius int) (Page, error) {
	var resp rpcAroundResponse
	err := c.call(ctx, MethodAround, rpcAroundRequest{
		Board:   board,
		OwnerID: ownerID,
		Radius:  radius,
	}, &resp)
	return resp.Page, err
}

// Size reports how many entries a board holds.
// Size implements Rank.
func (c *BusClient) Size(ctx context.Context, board Board) (int64, error) {
	var resp rpcSizeResponse
	err := c.call(ctx, MethodSize, rpcSizeRequest{
		Board: board,
	}, &resp)
	return resp.Size, err
}

// --- capability ---

// capability is what a Mod puts in the registry.
//
// It exists because converting to the interface at the registration call site
// does not do what it looks like it does: `Value: Rank(x)` stores an any
// whose dynamic type is still x's — Go does not box an interface inside an
// interface — so an assertion on the concrete type succeeds anyway. Wrapping
// the interface in a struct makes the dynamic type this wrapper, which
// satisfies Rank and nothing else.
//
// The consequence is the one that matters: a consumer cannot bind to the local
// implementation and then break on the day this service moves into its own
// process.
//
// It forwards each method explicitly rather than embedding the interface, and
// that is not style. Embedding names the field after the type, so an interface
// with a method of its own name — Rank.Rank, Match.Match — would have the
// field shadow the method and the wrapper would not satisfy the interface at
// all. The second service this generator ran against had exactly that shape.
type capability struct{ inner Rank }

func (c capability) Submit(ctx context.Context, board Board, score Score, mode UpdateMode, requestID string) (Entry, error) {
	return c.inner.Submit(ctx, board, score, mode, requestID)
}

func (c capability) Remove(ctx context.Context, board Board, ownerID int64) error {
	return c.inner.Remove(ctx, board, ownerID)
}

func (c capability) Page(ctx context.Context, board Board, offset int, limit int) (Page, error) {
	return c.inner.Page(ctx, board, offset, limit)
}

func (c capability) Rank(ctx context.Context, board Board, ownerID int64) (Entry, bool, error) {
	return c.inner.Rank(ctx, board, ownerID)
}

func (c capability) Around(ctx context.Context, board Board, ownerID int64, radius int) (Page, error) {
	return c.inner.Around(ctx, board, ownerID, radius)
}

func (c capability) Size(ctx context.Context, board Board) (int64, error) {
	return c.inner.Size(ctx, board)
}

// Capability wraps a Rank for registration. Both Mods use it, so the
// capability's dynamic type is the same whichever process published it.
func Capability(service Rank) Rank { return capability{inner: service} }

// --- capability name ---

// CapabilityName is the registry key both Mods publish under.
//
// It is declared here, from the interface's marker, so the name and the
// transport that depends on it are one fact. A repository that also keeps a
// central table of capability names should assert equality against this
// constant rather than repeat the string — two literals of the same name is
// how a Mod ends up ordered by one and looked up by the other.
const CapabilityName app.ModName = "service.rank"

// LocalCapabilityName is published ONLY by the owning Mod, and it is how a
// process knows it owns this service.
//
// The alternative was to look up CapabilityName and ask whether the value is a
// *BusClient. That does not work, and finding out why is worth recording: the
// capability is deliberately wrapped so its dynamic type satisfies the
// interface and nothing else, which is exactly what defeats the assertion. The
// first version of this generator shipped that check, and the unit test for it
// passed only because it registered an unwrapped client — not what a Mod does.
//
// Asking "is the local implementation published here" is also the question
// that was actually meant. Type-sniffing for one particular remote
// implementation is a proxy for it, and a proxy that a wrapper, a test double
// or a future in-process forwarder each break differently.
const LocalCapabilityName app.ModName = "service.rank.local"

var (
	_ Rank = (*BusClient)(nil)
	_ Rank = capability{}
)
