// Code generated by roost-codegen. DO NOT EDIT.
package bootstrap

import (
	accessplayer "example.com/planet/internal/access/player"
	accessplayertcp "example.com/planet/internal/access/player/tcp"
	registry "example.com/planet/internal/registry"
	serviceAccount "example.com/planet/internal/service/account"
	serviceActivity "example.com/planet/internal/service/activity"
	serviceChat "example.com/planet/internal/service/chat"
	serviceGame "example.com/planet/internal/service/game"
	serviceGlobal "example.com/planet/internal/service/global"
	serviceMail "example.com/planet/internal/service/mail"
	serviceMatch "example.com/planet/internal/service/match"
	servicePlatform "example.com/planet/internal/service/platform"
	serviceRank "example.com/planet/internal/service/rank"
	serviceSession "example.com/planet/internal/service/session"
	sagaGiftItem "example.com/planet/saga/gift_item"
	"github.com/tjbdwanghaibo/roost-core/app"
	"github.com/tjbdwanghaibo/roost-core/app/buildinfo"
	"github.com/tjbdwanghaibo/roost-core/entity"
	kitconfigdata "github.com/tjbdwanghaibo/roost-core/kit/configdata"
	kitdataengine "github.com/tjbdwanghaibo/roost-core/kit/dataengine"
	kitlock "github.com/tjbdwanghaibo/roost-core/kit/lock"
	kitmongo "github.com/tjbdwanghaibo/roost-core/kit/mongo"
	kitnats "github.com/tjbdwanghaibo/roost-core/kit/nats"
	kitnest "github.com/tjbdwanghaibo/roost-core/kit/nest"
	kitops "github.com/tjbdwanghaibo/roost-core/kit/ops"
	kitredis "github.com/tjbdwanghaibo/roost-core/kit/redis"
	kitremoteentity "github.com/tjbdwanghaibo/roost-core/kit/remoteentity"
	kitsaga "github.com/tjbdwanghaibo/roost-core/kit/saga"
	svcaccount "github.com/tjbdwanghaibo/roost-core/kit/service/account"
	svcchat "github.com/tjbdwanghaibo/roost-core/kit/service/chat"
	svcglobal "github.com/tjbdwanghaibo/roost-core/kit/service/global"
	svcactivity "github.com/tjbdwanghaibo/roost-core/kit/service/global/activity"
	svcmail "github.com/tjbdwanghaibo/roost-core/kit/service/mail"
	svcmatch "github.com/tjbdwanghaibo/roost-core/kit/service/match"
	svcplatform "github.com/tjbdwanghaibo/roost-core/kit/service/platform"
	svcrank "github.com/tjbdwanghaibo/roost-core/kit/service/rank"
	svcsession "github.com/tjbdwanghaibo/roost-core/kit/service/session"
	kitstatslog "github.com/tjbdwanghaibo/roost-core/kit/statslog"
	kitsyncbus "github.com/tjbdwanghaibo/roost-core/kit/syncbus"
)

var EntityManager = entity.NewEntityManager()
var EntityAccess = entity.NewManagerAccess(EntityManager)

func New() (*app.App, error) {
	if err := registry.RegisterAll(); err != nil {
		return nil, err
	}
	a := app.New("planet", buildinfo.VersionString())
	a.Mods(
		kitlock.NewLockMod(),
		kitops.NewOpsMod(),
		kitstatslog.NewStatsLogMod(),
	)
	a.RegisterServer(app.ServiceName(svcaccount.ServiceType), svcaccount.NewServer(),
		kitredis.NewRedisMod(),
		kitnats.NewNatsMod(nil),
		svcaccount.NewMod(serviceAccount.Verifier(), serviceAccount.Allocator(), serviceAccount.NameRules(), serviceAccount.Metrics()))
	a.RegisterServer(app.ServiceName(svcactivity.ServiceType), svcactivity.NewServer(),
		kitredis.NewRedisMod(),
		kitnats.NewNatsMod(nil),
		svcactivity.NewMod(serviceActivity.Metrics()))
	a.RegisterServer(app.ServiceName(svcchat.ServiceType), svcchat.NewServer(),
		kitredis.NewRedisMod(),
		kitnats.NewNatsMod(nil),
		svcchat.NewMod(serviceChat.Policy(), serviceChat.Bodies(), serviceChat.System(), serviceChat.Rules(), serviceChat.Metrics()))
	a.RegisterServer(app.ServiceName("game"), serviceGame.New(),
		kitconfigdata.NewConfigDataMod(),
		kitmongo.NewMongoMod(),
		kitnats.NewNatsMod(nil),
		kitdataengine.NewMod(kitdataengine.WithEntityAccess(EntityAccess), kitdataengine.WithRemoteProjection(true)),
		kitnest.NewMod(EntityAccess),
		kitredis.NewRedisMod(),
		kitsyncbus.NewSyncBusMod(0),
		kitremoteentity.NewRemoteEntityMod(0, kitremoteentity.WithMongoStorage(EntityAccess)),
		kitsaga.NewMod(kitsaga.CombineDefinitions(sagaGiftItem.Definitions())...),
		svcaccount.NewClientMod(),
		svcactivity.NewClientMod(),
		svcchat.NewClientMod(),
		svcglobal.NewClientMod(),
		svcmail.NewClientMod(),
		svcmatch.NewClientMod(),
		svcplatform.NewClientMod(),
		svcrank.NewClientMod(),
		svcsession.NewClientMod(),
		accessplayer.NewMod(),
		accessplayertcp.NewMod())
	a.RegisterServer(app.ServiceName(svcglobal.ServiceType), svcglobal.NewServer(),
		kitredis.NewRedisMod(),
		kitnats.NewNatsMod(nil),
		svcglobal.NewMod(serviceGlobal.Metrics()))
	a.RegisterServer(app.ServiceName(svcmail.ServiceType), svcmail.NewServer(),
		kitredis.NewRedisMod(),
		kitnats.NewNatsMod(nil),
		svcmail.NewMod(serviceMail.Broadcast(), serviceMail.Metrics()))
	a.RegisterServer(app.ServiceName(svcmatch.ServiceType), svcmatch.NewServer(),
		kitredis.NewRedisMod(),
		kitnats.NewNatsMod(nil),
		svcmatch.NewMod(serviceMatch.Metrics()))
	a.RegisterServer(app.ServiceName(svcplatform.ServiceType), svcplatform.NewServer(),
		kitredis.NewRedisMod(),
		kitnats.NewNatsMod(nil),
		svcplatform.NewMod(servicePlatform.Verify(), servicePlatform.Players(), servicePlatform.Deliver(), servicePlatform.Metrics()).WithPendingOrders(servicePlatform.Pending()))
	a.RegisterServer(app.ServiceName(svcrank.ServiceType), svcrank.NewServer(),
		kitredis.NewRedisMod(),
		kitnats.NewNatsMod(nil),
		svcrank.NewMod(serviceRank.Metrics()))
	a.RegisterServer(app.ServiceName(svcsession.ServiceType), svcsession.NewServer(),
		kitredis.NewRedisMod(),
		kitnats.NewNatsMod(nil),
		svcsession.NewMod(serviceSession.Release(), serviceSession.Metrics()))
	return a, nil
}
