package protocol

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/tjbdwanghaibo/roost-codegen/internal/genutil"
	"go/format"
	"path/filepath"
	"sort"
	"strings"
)

func writeIfChanged(path string, content []byte, force bool) (bool, error) {
	return genutil.WriteIfChanged(path, content, force)
}

func generateProto(defs *Definitions) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "syntax = \"proto3\";\n\n")
	fmt.Fprintf(&b, "package %s;\n\n", defs.ProtoPackage)
	fmt.Fprintf(&b, "option go_package = %q;\n\n", defs.GoPackage)
	for _, enum := range defs.Enums {
		fmt.Fprintf(&b, "// roost:source=go_def\n")
		fmt.Fprintf(&b, "enum %s {\n", enum.Name)
		for _, value := range enum.Values {
			fmt.Fprintf(&b, "  %s = %d;\n", value.Name, value.Value)
		}
		fmt.Fprintf(&b, "}\n\n")
	}
	for _, st := range defs.Structs {
		fmt.Fprintf(&b, "// roost:source=go_def\n")
		fmt.Fprintf(&b, "message %s {\n", st.Name)
		writtenOneofs := make(map[string]bool)
		for _, f := range st.Fields {
			if f.Oneof == "" {
				fmt.Fprintf(&b, "  %s %s = %d;\n", f.ProtoType, f.ProtoName, f.Number)
				continue
			}
			if writtenOneofs[f.Oneof] {
				continue
			}
			writtenOneofs[f.Oneof] = true
			fmt.Fprintf(&b, "  oneof %s {\n", f.Oneof)
			for _, item := range st.Fields {
				if item.Oneof == f.Oneof {
					fmt.Fprintf(&b, "    %s %s = %d;\n", item.ProtoType, item.ProtoName, item.Number)
				}
			}
			fmt.Fprintf(&b, "  }\n")
		}
		fmt.Fprintf(&b, "}\n\n")
	}
	return b.Bytes(), nil
}

func generateMsgIDGo(defs *Definitions) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tool/protocol. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package msgid\n\n")
	fmt.Fprintf(&b, "const (\n")
	for _, msg := range defs.Messages {
		base := msgName(msg)
		fmt.Fprintf(&b, "\tMsg%s uint32 = %d\n", base, msg.ReqID)
	}
	for _, push := range defs.Pushes {
		base := pushName(push)
		fmt.Fprintf(&b, "\tMsg%s uint32 = %d\n", base, push.MsgID)
	}
	fmt.Fprintf(&b, ")\n")

	tags := collectProtocolTags(defs)
	if len(tags) > 0 {
		fmt.Fprintf(&b, "\nconst (\n")
		for _, tag := range tags {
			fmt.Fprintf(&b, "\t%s = %q\n", tagConstName(tag), tag)
		}
		fmt.Fprintf(&b, ")\n")
	}
	fmt.Fprintf(&b, "\nvar msgTags = map[uint32][]string{\n")
	for _, msg := range defs.Messages {
		if len(msg.Tags) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\tMsg%s: %s,\n", msgName(msg), tagConstList(msg.Tags))
	}
	for _, push := range defs.Pushes {
		if len(push.Tags) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\tMsg%s: %s,\n", pushName(push), tagConstList(push.Tags))
	}
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "func MsgTags(msgID uint32) []string {\n")
	fmt.Fprintf(&b, "\ttags := msgTags[msgID]\n")
	fmt.Fprintf(&b, "\tif len(tags) == 0 {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(&b, "\tout := make([]string, len(tags))\n")
	fmt.Fprintf(&b, "\tcopy(out, tags)\n")
	fmt.Fprintf(&b, "\treturn out\n")
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "func MsgHasTag(msgID uint32, tag string) bool {\n")
	fmt.Fprintf(&b, "\tfor _, cur := range msgTags[msgID] {\n")
	fmt.Fprintf(&b, "\t\tif cur == tag {\n\t\t\treturn true\n\t\t}\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn false\n")
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "func MsgHasAnyTag(msgID uint32, tags ...string) bool {\n")
	fmt.Fprintf(&b, "\tif len(tags) == 0 {\n\t\treturn false\n\t}\n")
	fmt.Fprintf(&b, "\tfor _, tag := range tags {\n")
	fmt.Fprintf(&b, "\t\tif MsgHasTag(msgID, tag) {\n\t\t\treturn true\n\t\t}\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn false\n")
	fmt.Fprintf(&b, "}\n")
	return formatGo(b.Bytes())
}

func generateBindGo(defs *Definitions) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tool/protocol. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package player_bind\n\n")
	if len(defs.Messages) == 0 && len(defs.Pushes) == 0 {
		return formatGo(b.Bytes())
	}
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t%q\n", defs.ModulePath+PlayerAgentImportSuffix)
	fmt.Fprintf(&b, "\t%q\n", defs.ModulePath+"/protocol/msgid")
	fmt.Fprintf(&b, "\t%q\n", defs.ModulePath+PBImportSuffix)
	fmt.Fprintf(&b, ")\n\n")
	for _, msg := range defs.Messages {
		name := msgName(msg)
		if msg.Resp != "" {
			fmt.Fprintf(&b, "func Register%s(reg *player_agent.ProtocolRegistry, handler func(*player_agent.Context, *pb.%s) (*pb.%s, error)) error {\n", name, msg.Req, msg.Resp)
			fmt.Fprintf(&b, "\treturn player_agent.RegisterProtocol[*pb.%s, *pb.%s](reg, msgid.Msg%s, msgid.Msg%s, pb.Unmarshal%s, pb.Marshal%s, handler)\n", msg.Req, msg.Resp, name, name, msg.Req, msg.Resp)
			fmt.Fprintf(&b, "}\n\n")
		} else {
			fmt.Fprintf(&b, "func Register%s(reg *player_agent.ProtocolRegistry, handler func(*player_agent.Context, *pb.%s) error) error {\n", name, msg.Req)
			fmt.Fprintf(&b, "\treturn player_agent.RegisterNotify[*pb.%s](reg, msgid.Msg%s, pb.Unmarshal%s, handler)\n", msg.Req, name, msg.Req)
			fmt.Fprintf(&b, "}\n\n")
		}
	}
	for _, push := range defs.Pushes {
		name := pushName(push)
		fmt.Fprintf(&b, "func Register%sEncoder(reg *player_agent.ProtocolRegistry) error {\n", name)
		fmt.Fprintf(&b, "\treturn player_agent.RegisterTypedEncoder[*pb.%s](reg, msgid.Msg%s, pb.Marshal%s)\n", push.Msg, name, push.Msg)
		fmt.Fprintf(&b, "}\n\n")
	}
	return formatGo(b.Bytes())
}

func generateRobotProtocolGo(defs *Definitions) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tool/protocol. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package protocol\n\n")
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t%q\n", defs.ModulePath+"/protocol/msgid")
	fmt.Fprintf(&b, "\t%q\n", defs.ModulePath+PBImportSuffix)
	fmt.Fprintf(&b, ")\n\n")
	fmt.Fprintf(&b, "func RegisterDefaults(r *Registry) {\n")
	fmt.Fprintf(&b, "\tif r == nil {\n")
	fmt.Fprintf(&b, "\t\treturn\n")
	fmt.Fprintf(&b, "\t}\n")

	messages := append([]MsgDef(nil), defs.Messages...)
	sort.Slice(messages, func(i, j int) bool { return messages[i].ReqID < messages[j].ReqID })
	for _, msg := range messages {
		name := msgName(msg)
		fmt.Fprintf(&b, "\tr.MustRegisterEncoder(msgid.Msg%s, encodeTyped[*pb.%s](msgid.Msg%s, pb.Marshal%s))\n", name, msg.Req, name, msg.Req)
		if msg.Resp != "" {
			fmt.Fprintf(&b, "\tr.MustRegisterDecoder(msgid.Msg%s, decodeTyped(msgid.Msg%s, pb.Unmarshal%s))\n", name, name, msg.Resp)
		}
	}

	pushes := append([]PushDef(nil), defs.Pushes...)
	sort.Slice(pushes, func(i, j int) bool { return pushes[i].MsgID < pushes[j].MsgID })
	for _, push := range pushes {
		name := pushName(push)
		fmt.Fprintf(&b, "\tr.MustRegisterDecoder(msgid.Msg%s, decodeTyped(msgid.Msg%s, pb.Unmarshal%s))\n", name, name, push.Msg)
	}
	fmt.Fprintf(&b, "}\n")
	return formatGo(b.Bytes())
}

func generateProtocolHandlerFiles(defs *Definitions) (map[string][]byte, error) {
	groups := make(map[string][]MsgDef)
	for _, msg := range defs.Messages {
		if msg.Handler == "" {
			continue
		}
		groups[msg.Handler] = append(groups[msg.Handler], msg)
	}
	if len(groups) == 0 {
		return nil, nil
	}

	domains := make([]string, 0, len(groups))
	for domain := range groups {
		domains = append(domains, domain)
	}
	sort.Strings(domains)

	files := make(map[string][]byte, len(domains))
	for _, domain := range domains {
		content, err := generateProtocolHandlerGo(defs.ModulePath, domain, groups[domain])
		if err != nil {
			return nil, err
		}
		files[filepath.Join(domain, "protocol_gen.go")] = content
	}
	return files, nil
}

func generateProtocolHandlerGo(modulePath string, domain string, messages []MsgDef) ([]byte, error) {
	sort.Slice(messages, func(i, j int) bool { return messages[i].ReqID < messages[j].ReqID })

	displayName := protocolHandlerDisplayName(domain)
	packageName := protocolHandlerPackageName(domain)
	controllerAlias := protocolControllerAlias(domain)
	controllerType := displayName + "Controller"
	registerName := "Register" + displayName + "PlayerProtocols"

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tool/protocol. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t\"github.com/tjbdwanghaibo/roost-core/app\"\n")
	fmt.Fprintf(&b, "\t%s %q\n", controllerAlias, modulePath+"/game/controllers/"+domain)
	fmt.Fprintf(&b, "\t%q\n", modulePath+PlayerAgentImportSuffix)
	fmt.Fprintf(&b, "\t%q\n", modulePath+PBImportSuffix)
	fmt.Fprintf(&b, "\tplayerbind %q\n", modulePath+"/protocol/player_bind")
	fmt.Fprintf(&b, ")\n\n")

	fmt.Fprintf(&b, "type %s interface {\n", controllerType)
	for _, msg := range messages {
		name := msgName(msg)
		if msg.Resp != "" {
			fmt.Fprintf(&b, "\tHandle%s(ctx *player_agent.Context, req *pb.%s) (*pb.%s, error)\n", name, msg.Req, msg.Resp)
			continue
		}
		fmt.Fprintf(&b, "\tHandle%s(ctx *player_agent.Context, req *pb.%s) error\n", name, msg.Req)
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func %s(reg *player_agent.ProtocolRegistry, r *app.Registry) error {\n", registerName)
	fmt.Fprintf(&b, "\tctl, err := %s.FromRegistry(r)\n", controllerAlias)
	fmt.Fprintf(&b, "\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn err\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\treturn %sWith(reg, ctl)\n", registerName)
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "func %sWith(reg *player_agent.ProtocolRegistry, ctl %s) error {\n", registerName, controllerType)
	for i, msg := range messages {
		name := msgName(msg)
		if i == len(messages)-1 {
			fmt.Fprintf(&b, "\treturn playerbind.Register%s(reg, ctl.Handle%s)\n", name, name)
			continue
		}
		fmt.Fprintf(&b, "\tif err := playerbind.Register%s(reg, ctl.Handle%s); err != nil {\n", name, name)
		fmt.Fprintf(&b, "\t\treturn err\n")
		fmt.Fprintf(&b, "\t}\n")
	}
	fmt.Fprintf(&b, "}\n")

	return formatGo(b.Bytes())
}

func generateProtocolBootstrap(defs *Definitions, handlerImportBase string) ([]byte, error) {
	domainsSet := make(map[string]bool)
	for _, message := range defs.Messages {
		if message.Handler != "" {
			domainsSet[message.Handler] = true
		}
	}
	domains := make([]string, 0, len(domainsSet))
	for domain := range domainsSet {
		domains = append(domains, domain)
	}
	sort.Strings(domains)
	if len(domains) > 0 && strings.TrimSpace(handlerImportBase) == "" {
		return nil, fmt.Errorf("protocol bootstrap: handler import base is required for controller domains %s", strings.Join(domains, ","))
	}

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by tool/protocol. DO NOT EDIT.")
	fmt.Fprintln(&b, "package protocol_bootstrap")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, "\t\"fmt\"")
	fmt.Fprintln(&b, "\t\"github.com/tjbdwanghaibo/roost-core/app\"")
	fmt.Fprintf(&b, "\t%q\n", defs.ModulePath+PlayerAgentImportSuffix)
	if len(defs.Pushes) > 0 {
		fmt.Fprintf(&b, "\tplayerbind %q\n", defs.ModulePath+"/protocol/player_bind")
	}
	for _, domain := range domains {
		alias := protocolControllerAlias(domain) + "protocol"
		fmt.Fprintf(&b, "\t%s %q\n", alias, strings.TrimSuffix(handlerImportBase, "/")+"/"+domain)
	}
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func RegisterPlayerProtocols(protocols *player_agent.ProtocolRegistry, registry *app.Registry) error {")
	fmt.Fprintln(&b, "\tif protocols == nil || registry == nil {")
	fmt.Fprintln(&b, "\t\treturn fmt.Errorf(\"player protocol bootstrap: protocols and registry are required\")")
	fmt.Fprintln(&b, "\t}")
	for _, domain := range domains {
		alias := protocolControllerAlias(domain) + "protocol"
		fmt.Fprintf(&b, "\tif err := %s.Register%sPlayerProtocols(protocols, registry); err != nil {\n\t\treturn err\n\t}\n", alias, protocolHandlerDisplayName(domain))
	}
	for _, push := range defs.Pushes {
		fmt.Fprintf(&b, "\tif err := playerbind.Register%sEncoder(protocols); err != nil {\n\t\treturn err\n\t}\n", pushName(push))
	}
	fmt.Fprintln(&b, "\treturn nil")
	fmt.Fprintln(&b, "}")
	return formatGo(b.Bytes())
}

func protocolHandlerPackageName(domain string) string {
	return strings.ReplaceAll(domain, "_", "") + "handler"
}

func protocolControllerAlias(domain string) string {
	return strings.ReplaceAll(domain, "_", "") + "controller"
}

func protocolHandlerDisplayName(domain string) string {
	if name := protocolHandlerDisplayNames[domain]; name != "" {
		return name
	}
	return exportName(domain)
}

var protocolHandlerDisplayNames = map[string]string{
	"battlereport":       "BattleReport",
	"challenge_template": "ChallengeTemplate",
	"homecity":           "HomeCity",
	"login":              "Login",
	"mapexplore":         "MapExplore",
	"mapops":             "MapOps",
	"mapview":            "MapView",
	"systementry":        "SystemEntry",
	"vip":                "VIP",
	"warwarn":            "WarWarn",
	"world":              "BigWorld",
	"worldboss":          "WorldBoss",
	"worldstage":         "WorldStage",
}

func generateManifest(defs *Definitions) ([]byte, error) {
	type manifestMsg struct {
		Name            string   `json:"name"`
		Mode            string   `json:"mode"`
		Req             string   `json:"req"`
		ReqID           uint32   `json:"req_id"`
		Resp            string   `json:"resp,omitempty"`
		RespID          uint32   `json:"resp_id,omitempty"`
		Tags            []string `json:"tags,omitempty"`
		Handler         string   `json:"handler,omitempty"`
		Group           string   `json:"group,omitempty"`
		SourceFile      string   `json:"source_file,omitempty"`
		SourceInterface string   `json:"source_interface,omitempty"`
	}
	type manifestPush struct {
		Name            string   `json:"name"`
		Mode            string   `json:"mode"`
		Msg             string   `json:"msg"`
		MsgID           uint32   `json:"msg_id"`
		Tags            []string `json:"tags,omitempty"`
		Group           string   `json:"group,omitempty"`
		SourceFile      string   `json:"source_file,omitempty"`
		SourceInterface string   `json:"source_interface,omitempty"`
	}
	type manifestStruct struct {
		Name       string `json:"name"`
		Group      string `json:"group,omitempty"`
		SourceKind string `json:"source_kind,omitempty"`
		SourceFile string `json:"source_file,omitempty"`
	}
	out := struct {
		Package  string           `json:"package"`
		Structs  []manifestStruct `json:"structs,omitempty"`
		Messages []manifestMsg    `json:"messages"`
		Pushes   []manifestPush   `json:"pushes,omitempty"`
	}{
		Package: defs.ProtoPackage,
	}
	for _, st := range defs.Structs {
		out.Structs = append(out.Structs, manifestStruct{
			Name:       st.Name,
			Group:      st.Group,
			SourceKind: st.SourceKind,
			SourceFile: st.SourceFile,
		})
	}
	for _, msg := range defs.Messages {
		out.Messages = append(out.Messages, manifestMsg{
			Name:            msgName(msg),
			Mode:            msgMode(msg),
			Req:             msg.Req,
			ReqID:           msg.ReqID,
			Resp:            msg.Resp,
			RespID:          msg.RespID,
			Tags:            msg.Tags,
			Handler:         msg.Handler,
			Group:           msg.Group,
			SourceFile:      msg.SourceFile,
			SourceInterface: msg.SourceInterface,
		})
	}
	for _, push := range defs.Pushes {
		out.Pushes = append(out.Pushes, manifestPush{
			Name:            pushName(push),
			Mode:            "ntf",
			Msg:             push.Msg,
			MsgID:           push.MsgID,
			Tags:            push.Tags,
			Group:           push.Group,
			SourceFile:      push.SourceFile,
			SourceInterface: push.SourceInterface,
		})
	}
	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

func collectProtocolTags(defs *Definitions) []string {
	seen := make(map[string]struct{})
	for _, msg := range defs.Messages {
		for _, tag := range msg.Tags {
			seen[tag] = struct{}{}
		}
	}
	for _, push := range defs.Pushes {
		for _, tag := range push.Tags {
			seen[tag] = struct{}{}
		}
	}
	tags := make([]string, 0, len(seen))
	for tag := range seen {
		tags = append(tags, tag)
	}
	sort.Strings(tags)
	return tags
}

func tagConstList(tags []string) string {
	if len(tags) == 0 {
		return "nil"
	}
	var b bytes.Buffer
	b.WriteByte('{')
	for i, tag := range tags {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(tagConstName(tag))
	}
	b.WriteByte('}')
	return b.String()
}

func msgMode(msg MsgDef) string {
	if msg.Resp == "" {
		return "psh"
	}
	return "req_resp"
}

func generatePBGo(defs *Definitions) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tool/protocol. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package pb\n\n")
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t\"fmt\"\n")
	fmt.Fprintf(&b, "\t\"math\"\n")
	if needsSort(defs) {
		fmt.Fprintf(&b, "\t\"sort\"\n")
	}
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "\t\"google.golang.org/protobuf/encoding/protowire\"\n")
	fmt.Fprintf(&b, ")\n\n")
	for _, enum := range defs.Enums {
		emitEnum(&b, enum)
	}
	for _, st := range defs.Structs {
		emitStruct(&b, st)
	}
	for _, st := range defs.Structs {
		emitMarshal(&b, st)
		emitUnmarshal(&b, st)
	}
	fmt.Fprintf(&b, "var _ = math.Float32bits\n")
	return formatGo(b.Bytes())
}

func formatGo(data []byte) ([]byte, error) {
	out, err := format.Source(data)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func emitEnum(b *bytes.Buffer, enum EnumDef) {
	underlying := enum.Underlying
	if underlying == "" {
		underlying = "int32"
	}
	fmt.Fprintf(b, "type %s %s\n\n", enum.Name, underlying)
	fmt.Fprintf(b, "const (\n")
	for _, value := range enum.Values {
		fmt.Fprintf(b, "\t%s %s = %d\n", value.Name, enum.Name, value.Value)
	}
	fmt.Fprintf(b, ")\n\n")
}

func emitStruct(b *bytes.Buffer, st StructDef) {
	fmt.Fprintf(b, "type %s struct {\n", st.Name)
	writtenOneofs := make(map[string]bool)
	for _, f := range st.Fields {
		if f.Oneof == "" {
			fmt.Fprintf(b, "\t%s %s `json:%q`\n", f.Name, f.GoType, f.ProtoName+",omitempty")
			continue
		}
		if writtenOneofs[f.Oneof] {
			continue
		}
		writtenOneofs[f.Oneof] = true
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", exportName(f.Oneof), oneofInterfaceName(st.Name, f.Oneof), f.Oneof+",omitempty")
	}
	fmt.Fprintf(b, "}\n\n")
	for _, group := range oneofGroups(st) {
		fmt.Fprintf(b, "type %s interface {\n", group.iface)
		fmt.Fprintf(b, "\t%s()\n", group.method)
		fmt.Fprintf(b, "}\n\n")
		for _, f := range group.fields {
			fmt.Fprintf(b, "type %s struct {\n", oneofWrapperName(st.Name, f.Name))
			fmt.Fprintf(b, "\t%s %s `json:%q`\n", f.Name, f.GoType, f.ProtoName+",omitempty")
			fmt.Fprintf(b, "}\n\n")
			fmt.Fprintf(b, "func (*%s) %s() {}\n\n", oneofWrapperName(st.Name, f.Name), group.method)
		}
		fmt.Fprintf(b, "func Set%s%s(m *%s, body any) error {\n", st.Name, group.field, st.Name)
		fmt.Fprintf(b, "\tif m == nil {\n\t\treturn nil\n\t}\n")
		fmt.Fprintf(b, "\tswitch v := body.(type) {\n")
		fmt.Fprintf(b, "\tcase nil:\n\t\tm.%s = nil\n", group.field)
		for _, f := range group.fields {
			fmt.Fprintf(b, "\tcase *%s:\n\t\tm.%s = v\n", oneofWrapperName(st.Name, f.Name), group.field)
		}
		fmt.Fprintf(b, "\tdefault:\n\t\treturn fmt.Errorf(\"unknown %s oneof %s type %%T\", body)\n", st.Name, group.name)
		fmt.Fprintf(b, "\t}\n")
		fmt.Fprintf(b, "\treturn nil\n")
		fmt.Fprintf(b, "}\n\n")
		fmt.Fprintf(b, "func Get%s%s(m *%s) any {\n", st.Name, group.field, st.Name)
		fmt.Fprintf(b, "\tif m == nil {\n\t\treturn nil\n\t}\n")
		fmt.Fprintf(b, "\treturn m.%s\n", group.field)
		fmt.Fprintf(b, "}\n\n")
	}
}

func emitMarshal(b *bytes.Buffer, st StructDef) {
	fmt.Fprintf(b, "func Marshal%s(m *%s) ([]byte, error) {\n", st.Name, st.Name)
	fmt.Fprintf(b, "\tif m == nil {\n\t\treturn nil, nil\n\t}\n")
	fmt.Fprintf(b, "\tvar b []byte\n")
	for _, f := range st.Fields {
		if f.Oneof != "" {
			continue
		}
		emitMarshalField(b, f, "m."+f.Name, "b", "\t")
	}
	emitMarshalOneofs(b, st)
	fmt.Fprintf(b, "\treturn b, nil\n")
	fmt.Fprintf(b, "}\n\n")
}

func emitUnmarshal(b *bytes.Buffer, st StructDef) {
	fmt.Fprintf(b, "func Unmarshal%s(data []byte) (*%s, error) {\n", st.Name, st.Name)
	fmt.Fprintf(b, "\tm := &%s{}\n", st.Name)
	fmt.Fprintf(b, "\tfor len(data) > 0 {\n")
	fmt.Fprintf(b, "\t\tnum, typ, n := protowire.ConsumeTag(data)\n")
	fmt.Fprintf(b, "\t\tif n < 0 {\n\t\t\treturn nil, protowire.ParseError(n)\n\t\t}\n")
	fmt.Fprintf(b, "\t\tdata = data[n:]\n")
	fmt.Fprintf(b, "\t\tswitch num {\n")
	for _, f := range st.Fields {
		fmt.Fprintf(b, "\t\tcase %d:\n", f.Number)
		if f.Oneof != "" {
			emitDecodeOneofField(b, st, f, "\t\t\t")
		} else {
			emitDecodeField(b, f, "m."+f.Name, "\t\t\t")
		}
	}
	fmt.Fprintf(b, "\t\tdefault:\n")
	fmt.Fprintf(b, "\t\t\tn = protowire.ConsumeFieldValue(num, typ, data)\n")
	fmt.Fprintf(b, "\t\t\tif n < 0 {\n\t\t\t\treturn nil, protowire.ParseError(n)\n\t\t\t}\n")
	fmt.Fprintf(b, "\t\t\tdata = data[n:]\n")
	fmt.Fprintf(b, "\t\t}\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\treturn m, nil\n")
	fmt.Fprintf(b, "}\n\n")
}

type oneofGroup struct {
	name   string
	field  string
	iface  string
	method string
	fields []FieldDef
}

func oneofGroups(st StructDef) []oneofGroup {
	byName := make(map[string]int)
	var ret []oneofGroup
	for _, f := range st.Fields {
		if f.Oneof == "" {
			continue
		}
		idx, ok := byName[f.Oneof]
		if !ok {
			ret = append(ret, oneofGroup{
				name:   f.Oneof,
				field:  exportName(f.Oneof),
				iface:  oneofInterfaceName(st.Name, f.Oneof),
				method: oneofMethodName(st.Name, f.Oneof),
			})
			idx = len(ret) - 1
			byName[f.Oneof] = idx
		}
		ret[idx].fields = append(ret[idx].fields, f)
	}
	return ret
}

func emitMarshalOneofs(b *bytes.Buffer, st StructDef) {
	for _, group := range oneofGroups(st) {
		fmt.Fprintf(b, "\tswitch body := m.%s.(type) {\n", group.field)
		fmt.Fprintf(b, "\tcase nil:\n")
		for _, f := range group.fields {
			fmt.Fprintf(b, "\tcase *%s:\n", oneofWrapperName(st.Name, f.Name))
			if guard := oneofMarshalGuard(f, "body."+f.Name); guard != "" {
				fmt.Fprintf(b, "\t\tif %s {\n", guard)
				emitMarshalSingle(b, f, "body."+f.Name, f.Number, "b", "\t\t\t")
				fmt.Fprintf(b, "\t\t}\n")
			} else {
				emitMarshalSingle(b, f, "body."+f.Name, f.Number, "b", "\t\t")
			}
		}
		fmt.Fprintf(b, "\tdefault:\n")
		fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"unknown %s oneof %s type %%T\", body)\n", st.Name, group.name)
		fmt.Fprintf(b, "\t}\n")
	}
}

func emitDecodeOneofField(b *bytes.Buffer, st StructDef, f FieldDef, ind string) {
	target := lower1(f.Name)
	emitDecodeSingle(b, f, target, ind, true, "data")
	fmt.Fprintf(b, "%sm.%s = &%s{%s: %s}\n", ind, exportName(f.Oneof), oneofWrapperName(st.Name, f.Name), f.Name, target)
}

func oneofMarshalGuard(f FieldDef, expr string) string {
	if f.Kind == KindMessage && f.IsPtr {
		return expr + " != nil"
	}
	return ""
}

func emitMarshalField(b *bytes.Buffer, f FieldDef, expr, bvar, ind string) {
	switch f.Kind {
	case KindRepeated:
		fmt.Fprintf(b, "%sif len(%s) > 0 {\n", ind, expr)
		if isPackableScalar(*f.SliceElem) {
			fmt.Fprintf(b, "%s\tvar packed []byte\n", ind)
			fmt.Fprintf(b, "%s\tfor _, item := range %s {\n", ind, expr)
			emitMarshalPackedScalar(b, *f.SliceElem, "item", "packed", ind+"\t\t")
			fmt.Fprintf(b, "%s\t}\n", ind)
			fmt.Fprintf(b, "%s\t%s = protowire.AppendTag(%s, %d, protowire.BytesType)\n", ind, bvar, bvar, f.Number)
			fmt.Fprintf(b, "%s\t%s = protowire.AppendBytes(%s, packed)\n", ind, bvar, bvar)
		} else {
			fmt.Fprintf(b, "%s\tfor _, item := range %s {\n", ind, expr)
			emitMarshalSingle(b, *f.SliceElem, "item", f.Number, bvar, ind+"\t\t")
			fmt.Fprintf(b, "%s\t}\n", ind)
		}
		fmt.Fprintf(b, "%s}\n", ind)
	case KindMap:
		fmt.Fprintf(b, "%sif len(%s) > 0 {\n", ind, expr)
		keys := sortedMapKeys(f)
		if keys {
			fmt.Fprintf(b, "%s\tkeys := make([]%s, 0, len(%s))\n", ind, f.MapKey.GoType, expr)
			fmt.Fprintf(b, "%s\tfor key := range %s { keys = append(keys, key) }\n", ind, expr)
			fmt.Fprintf(b, "%s\tsort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })\n", ind)
			fmt.Fprintf(b, "%s\tfor _, key := range keys {\n", ind)
			fmt.Fprintf(b, "%s\t\tval := %s[key]\n", ind, expr)
		} else {
			fmt.Fprintf(b, "%s\tfor key, val := range %s {\n", ind, expr)
		}
		fmt.Fprintf(b, "%s\t\tvar entry []byte\n", ind)
		emitMarshalSingle(b, *f.MapKey, "key", 1, "entry", ind+"\t\t\t")
		emitMarshalSingle(b, *f.MapVal, "val", 2, "entry", ind+"\t\t\t")
		fmt.Fprintf(b, "%s\t\t%s = protowire.AppendTag(%s, %d, protowire.BytesType)\n", ind, bvar, bvar, f.Number)
		fmt.Fprintf(b, "%s\t\t%s = protowire.AppendBytes(%s, entry)\n", ind, bvar, bvar)
		fmt.Fprintf(b, "%s\t}\n", ind)
		fmt.Fprintf(b, "%s}\n", ind)
	default:
		if z := zeroCond(f, expr); z != "" {
			fmt.Fprintf(b, "%sif %s {\n", ind, z)
			emitMarshalSingle(b, f, expr, f.Number, bvar, ind+"\t")
			fmt.Fprintf(b, "%s}\n", ind)
		} else {
			emitMarshalSingle(b, f, expr, f.Number, bvar, ind)
		}
	}
}

func emitMarshalPackedScalar(b *bytes.Buffer, f FieldDef, expr string, bvar, ind string) {
	switch f.Scalar {
	case ScalarBool:
		fmt.Fprintf(b, "%sif %s { %s = protowire.AppendVarint(%s, 1) } else { %s = protowire.AppendVarint(%s, 0) }\n", ind, expr, bvar, bvar, bvar, bvar)
	case ScalarFloat32:
		fmt.Fprintf(b, "%s%s = protowire.AppendFixed32(%s, math.Float32bits(%s))\n", ind, bvar, bvar, expr)
	case ScalarFloat64:
		fmt.Fprintf(b, "%s%s = protowire.AppendFixed64(%s, math.Float64bits(%s))\n", ind, bvar, bvar, expr)
	default:
		fmt.Fprintf(b, "%s%s = protowire.AppendVarint(%s, uint64(%s))\n", ind, bvar, bvar, expr)
	}
}

func emitMarshalSingle(b *bytes.Buffer, f FieldDef, expr string, num int, bvar, ind string) {
	wire := protoWireType(f)
	switch f.Kind {
	case KindBytes:
		fmt.Fprintf(b, "%s%s = protowire.AppendTag(%s, %d, %s)\n", ind, bvar, bvar, num, wire)
		fmt.Fprintf(b, "%s%s = protowire.AppendBytes(%s, %s)\n", ind, bvar, bvar, expr)
	case KindMessage:
		arg := expr
		if !f.IsPtr {
			arg = "&" + expr
		}
		fmt.Fprintf(b, "%s{\n", ind)
		fmt.Fprintf(b, "%s\tpayload, err := Marshal%s(%s)\n", ind, f.TypeName, arg)
		fmt.Fprintf(b, "%s\tif err != nil { return nil, err }\n", ind)
		fmt.Fprintf(b, "%s\t%s = protowire.AppendTag(%s, %d, protowire.BytesType)\n", ind, bvar, bvar, num)
		fmt.Fprintf(b, "%s\t%s = protowire.AppendBytes(%s, payload)\n", ind, bvar, bvar)
		fmt.Fprintf(b, "%s}\n", ind)
	case KindScalar, KindEnum:
		fmt.Fprintf(b, "%s%s = protowire.AppendTag(%s, %d, %s)\n", ind, bvar, bvar, num, wire)
		switch f.Scalar {
		case ScalarString:
			fmt.Fprintf(b, "%s%s = protowire.AppendString(%s, %s)\n", ind, bvar, bvar, expr)
		case ScalarBool:
			fmt.Fprintf(b, "%sif %s { %s = protowire.AppendVarint(%s, 1) } else { %s = protowire.AppendVarint(%s, 0) }\n", ind, expr, bvar, bvar, bvar, bvar)
		case ScalarFloat32:
			fmt.Fprintf(b, "%s%s = protowire.AppendFixed32(%s, math.Float32bits(%s))\n", ind, bvar, bvar, expr)
		case ScalarFloat64:
			fmt.Fprintf(b, "%s%s = protowire.AppendFixed64(%s, math.Float64bits(%s))\n", ind, bvar, bvar, expr)
		default:
			fmt.Fprintf(b, "%s%s = protowire.AppendVarint(%s, uint64(%s))\n", ind, bvar, bvar, expr)
		}
	}
}

func emitDecodeField(b *bytes.Buffer, f FieldDef, target, ind string) {
	switch f.Kind {
	case KindRepeated:
		if isPackableScalar(*f.SliceElem) {
			fmt.Fprintf(b, "%sif typ == protowire.BytesType {\n", ind)
			fmt.Fprintf(b, "%s\tpacked, n := protowire.ConsumeBytes(data)\n", ind)
			fmt.Fprintf(b, "%s\tif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
			fmt.Fprintf(b, "%s\tdata = data[n:]\n", ind)
			fmt.Fprintf(b, "%s\tfor len(packed) > 0 {\n", ind)
			emitDecodePackedScalar(b, *f.SliceElem, "item", ind+"\t\t", true, "packed")
			fmt.Fprintf(b, "%s\t\t%s = append(%s, item)\n", ind, target, target)
			fmt.Fprintf(b, "%s\t}\n", ind)
			fmt.Fprintf(b, "%s} else {\n", ind)
			emitDecodeSingle(b, *f.SliceElem, "item", ind+"\t", true, "data")
			fmt.Fprintf(b, "%s\t%s = append(%s, item)\n", ind, target, target)
			fmt.Fprintf(b, "%s}\n", ind)
			return
		}
		emitDecodeSingle(b, *f.SliceElem, "item", ind, true, "data")
		fmt.Fprintf(b, "%s%s = append(%s, item)\n", ind, target, target)
	case KindMap:
		fmt.Fprintf(b, "%sif typ != protowire.BytesType { return nil, fmt.Errorf(\"field %s: expected bytes\") }\n", ind, f.Name)
		fmt.Fprintf(b, "%sentry, n := protowire.ConsumeBytes(data)\n", ind)
		fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
		fmt.Fprintf(b, "%sdata = data[n:]\n", ind)
		fmt.Fprintf(b, "%svar key %s\n", ind, f.MapKey.GoType)
		fmt.Fprintf(b, "%svar val %s\n", ind, f.MapVal.GoType)
		fmt.Fprintf(b, "%sfor len(entry) > 0 {\n", ind)
		fmt.Fprintf(b, "%s\tnum, typ, n := protowire.ConsumeTag(entry)\n", ind)
		fmt.Fprintf(b, "%s\tif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
		fmt.Fprintf(b, "%s\tentry = entry[n:]\n", ind)
		fmt.Fprintf(b, "%s\tswitch num {\n", ind)
		fmt.Fprintf(b, "%s\tcase 1:\n", ind)
		emitDecodeSingle(b, *f.MapKey, "key", ind+"\t\t", false, "entry")
		fmt.Fprintf(b, "%s\tcase 2:\n", ind)
		emitDecodeSingle(b, *f.MapVal, "val", ind+"\t\t", false, "entry")
		fmt.Fprintf(b, "%s\tdefault:\n", ind)
		fmt.Fprintf(b, "%s\t\tn = protowire.ConsumeFieldValue(num, typ, entry)\n", ind)
		fmt.Fprintf(b, "%s\t\tif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
		fmt.Fprintf(b, "%s\t\tentry = entry[n:]\n", ind)
		fmt.Fprintf(b, "%s\t}\n", ind)
		fmt.Fprintf(b, "%s}\n", ind)
		fmt.Fprintf(b, "%sif %s == nil { %s = make(%s) }\n", ind, target, target, f.GoType)
		fmt.Fprintf(b, "%s%s[key] = val\n", ind, target)
	default:
		emitDecodeSingle(b, f, target, ind, false, "data")
	}
}

func emitDecodePackedScalar(b *bytes.Buffer, f FieldDef, target, ind string, declare bool, src string) {
	if declare {
		fmt.Fprintf(b, "%svar %s %s\n", ind, target, f.GoType)
	}
	switch f.Scalar {
	case ScalarBool:
		fmt.Fprintf(b, "%sv, n := protowire.ConsumeVarint(%s)\n", ind, src)
		fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
		fmt.Fprintf(b, "%s%s = v != 0\n", ind, target)
	case ScalarFloat32:
		fmt.Fprintf(b, "%sv, n := protowire.ConsumeFixed32(%s)\n", ind, src)
		fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
		fmt.Fprintf(b, "%s%s = math.Float32frombits(v)\n", ind, target)
	case ScalarFloat64:
		fmt.Fprintf(b, "%sv, n := protowire.ConsumeFixed64(%s)\n", ind, src)
		fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
		fmt.Fprintf(b, "%s%s = math.Float64frombits(v)\n", ind, target)
	default:
		fmt.Fprintf(b, "%sv, n := protowire.ConsumeVarint(%s)\n", ind, src)
		fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
		fmt.Fprintf(b, "%s%s = %s(v)\n", ind, target, f.GoType)
	}
	fmt.Fprintf(b, "%s%s = %s[n:]\n", ind, src, src)
}

func emitDecodeSingle(b *bytes.Buffer, f FieldDef, target, ind string, declare bool, src string) {
	if declare {
		fmt.Fprintf(b, "%svar %s %s\n", ind, target, f.GoType)
	}
	switch f.Kind {
	case KindBytes:
		fmt.Fprintf(b, "%sif typ != protowire.BytesType { return nil, fmt.Errorf(\"expected bytes\") }\n", ind)
		fmt.Fprintf(b, "%sv, n := protowire.ConsumeBytes(%s)\n", ind, src)
		fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
		fmt.Fprintf(b, "%s%s = append(%s[:0], v...)\n", ind, target, target)
		fmt.Fprintf(b, "%s%s = %s[n:]\n", ind, src, src)
	case KindMessage:
		fmt.Fprintf(b, "%sif typ != protowire.BytesType { return nil, fmt.Errorf(\"expected message bytes\") }\n", ind)
		fmt.Fprintf(b, "%sv, n := protowire.ConsumeBytes(%s)\n", ind, src)
		fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
		fmt.Fprintf(b, "%smsg, err := Unmarshal%s(v)\n", ind, f.TypeName)
		fmt.Fprintf(b, "%sif err != nil { return nil, err }\n", ind)
		if f.IsPtr {
			fmt.Fprintf(b, "%s%s = msg\n", ind, target)
		} else {
			fmt.Fprintf(b, "%sif msg != nil { %s = *msg }\n", ind, target)
		}
		fmt.Fprintf(b, "%s%s = %s[n:]\n", ind, src, src)
	case KindScalar, KindEnum:
		switch f.Scalar {
		case ScalarString:
			fmt.Fprintf(b, "%sif typ != protowire.BytesType { return nil, fmt.Errorf(\"expected string\") }\n", ind)
			fmt.Fprintf(b, "%sv, n := protowire.ConsumeString(%s)\n", ind, src)
			fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
			fmt.Fprintf(b, "%s%s = v\n", ind, target)
		case ScalarBool:
			fmt.Fprintf(b, "%sif typ != protowire.VarintType { return nil, fmt.Errorf(\"expected bool\") }\n", ind)
			fmt.Fprintf(b, "%sv, n := protowire.ConsumeVarint(%s)\n", ind, src)
			fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
			fmt.Fprintf(b, "%s%s = v != 0\n", ind, target)
		case ScalarFloat32:
			fmt.Fprintf(b, "%sif typ != protowire.Fixed32Type { return nil, fmt.Errorf(\"expected float\") }\n", ind)
			fmt.Fprintf(b, "%sv, n := protowire.ConsumeFixed32(%s)\n", ind, src)
			fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
			fmt.Fprintf(b, "%s%s = math.Float32frombits(v)\n", ind, target)
		case ScalarFloat64:
			fmt.Fprintf(b, "%sif typ != protowire.Fixed64Type { return nil, fmt.Errorf(\"expected double\") }\n", ind)
			fmt.Fprintf(b, "%sv, n := protowire.ConsumeFixed64(%s)\n", ind, src)
			fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
			fmt.Fprintf(b, "%s%s = math.Float64frombits(v)\n", ind, target)
		default:
			fmt.Fprintf(b, "%sif typ != protowire.VarintType { return nil, fmt.Errorf(\"expected varint\") }\n", ind)
			fmt.Fprintf(b, "%sv, n := protowire.ConsumeVarint(%s)\n", ind, src)
			fmt.Fprintf(b, "%sif n < 0 { return nil, protowire.ParseError(n) }\n", ind)
			fmt.Fprintf(b, "%s%s = %s(v)\n", ind, target, f.GoType)
		}
		fmt.Fprintf(b, "%s%s = %s[n:]\n", ind, src, src)
	}
}

func zeroCond(f FieldDef, expr string) string {
	switch f.Kind {
	case KindBytes, KindRepeated, KindMap:
		return "len(" + expr + ") > 0"
	case KindMessage:
		if f.IsPtr {
			return expr + " != nil"
		}
		return ""
	case KindScalar, KindEnum:
		switch f.Scalar {
		case ScalarString:
			return expr + " != \"\""
		case ScalarBool:
			return expr
		default:
			return expr + " != 0"
		}
	default:
		return ""
	}
}

func protoWireType(f FieldDef) string {
	switch f.WireType {
	case "fixed32":
		return "protowire.Fixed32Type"
	case "fixed64":
		return "protowire.Fixed64Type"
	case "bytes":
		return "protowire.BytesType"
	default:
		return "protowire.VarintType"
	}
}

func sortedMapKeys(f FieldDef) bool {
	switch f.MapKey.Scalar {
	case ScalarString, ScalarInt32, ScalarInt64, ScalarUint32, ScalarUint64:
		return true
	default:
		return false
	}
}

func needsSort(defs *Definitions) bool {
	for _, st := range defs.Structs {
		for _, f := range st.Fields {
			if f.Kind == KindMap && sortedMapKeys(f) {
				return true
			}
		}
	}
	return false
}

func isPackableScalar(f FieldDef) bool {
	if f.Kind != KindScalar && f.Kind != KindEnum {
		return false
	}
	return f.Scalar != ScalarString
}
