package protocol

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

const protocolGeneratedHeader = "// Code generated by tool/protocol. DO NOT EDIT."

type protocolOutputPaths struct {
	proto, pb, msgID, bind, robot, manifest, handlers, csharp string
}

// IsGeneratedArtifact recognizes the two default protocol products without a
// Go generated header. The roost staging planner and -check need the same
// ownership test as the protocol generator's retirement path.
func IsGeneratedArtifact(rel string, raw []byte) bool {
	switch filepath.ToSlash(rel) {
	case "protocol/proto/protocol.proto":
		return isGeneratedProto(raw)
	case "protocol/protocol_manifest.json":
		return isProtocolManifest(raw)
	default:
		return false
	}
}

// retireProtocolOutputs removes only recognizable products of a previous
// generation. In a staged `roost generate`, these removals become guarded
// changes in the real project rather than silently leaving obsolete IDs live.
func retireProtocolOutputs(paths protocolOutputPaths, stdout io.Writer) error {
	files := []struct{ path, kind string }{
		{paths.proto, "proto"},
		{paths.pb, "go"},
		{paths.msgID, "go"},
		{paths.manifest, "manifest"},
	}
	if paths.bind != "" {
		files = append(files, struct{ path, kind string }{filepath.Join(paths.bind, "bind_gen.go"), "go"})
	}
	if paths.robot != "" {
		files = append(files, struct{ path, kind string }{paths.robot, "go"})
	}
	if paths.csharp != "" {
		files = append(files, struct{ path, kind string }{paths.csharp, "go"})
	}
	for _, file := range files {
		removed, err := retireProtocolFile(file.path, file.kind)
		if err != nil {
			return err
		}
		if removed {
			_, _ = fmt.Fprintf(stdout, "removed orphan: %s\n", file.path)
		}
	}
	return retireProtocolHandlers(paths.handlers, nil, stdout)
}

func retireProtocolHandlers(dir string, expected map[string][]byte, stdout io.Writer) error {
	if dir == "" {
		return nil
	}
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("scan protocol handlers %s: %w", dir, err)
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		rel := filepath.Join(entry.Name(), "protocol_gen.go")
		if _, ok := expected[rel]; ok {
			continue
		}
		path := filepath.Join(dir, rel)
		removed, err := retireProtocolFile(path, "go")
		if err != nil {
			return err
		}
		if removed {
			_, _ = fmt.Fprintf(stdout, "removed orphan: %s\n", path)
		}
	}
	return nil
}

func retireProtocolFile(path, kind string) (bool, error) {
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("inspect protocol output %s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return false, nil
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("read protocol output %s: %w", path, err)
	}
	owned := false
	switch kind {
	case "go":
		owned = bytes.HasPrefix(raw, []byte(protocolGeneratedHeader))
	case "proto":
		owned = isGeneratedProto(raw)
	case "manifest":
		owned = isProtocolManifest(raw)
	}
	if !owned {
		return false, nil
	}
	if err := os.Remove(path); err != nil {
		return false, fmt.Errorf("remove protocol output %s: %w", path, err)
	}
	return true, nil
}

func isGeneratedProto(raw []byte) bool {
	return bytes.HasPrefix(raw, []byte("syntax = \"proto3\";")) && bytes.Contains(raw, []byte("// roost:source=go_def"))
}

// The old JSON manifest has no comment header. Accept only its known shape;
// arbitrary JSON at a user-supplied -manifest path is not ours to remove.
func isProtocolManifest(raw []byte) bool {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(raw, &fields); err != nil || len(fields) < 2 {
		return false
	}
	for key := range fields {
		switch key {
		case "package", "structs", "messages", "pushes":
		default:
			return false
		}
	}
	var packageName string
	if err := json.Unmarshal(fields["package"], &packageName); err != nil || packageName == "" {
		return false
	}
	var messages []json.RawMessage
	return len(fields["messages"]) > 0 && json.Unmarshal(fields["messages"], &messages) == nil
}
