package nest

import (
	"bytes"
	"crypto/md5"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"unicode"
)

type bootstrapRegistration struct {
	ImportPath   string
	RegisterFunc string
}

type bootstrapPackage struct {
	Alias         string
	ImportPath    string
	RegisterFuncs []string
}

func generateBootstrapNest(regs []bootstrapRegistration, outFile string, force bool) (bool, error) {
	packages := bootstrapPackages(regs)
	tmpl, err := template.New("bootstrap_nest").Parse(bootstrapNestTemplate)
	if err != nil {
		return false, fmt.Errorf("template parse: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, packages); err != nil {
		return false, fmt.Errorf("template exec: %w", err)
	}
	content, err := format.Source(buf.Bytes())
	if err != nil {
		return false, fmt.Errorf("format generated source: %w", err)
	}
	if !force {
		existing, err := os.ReadFile(outFile)
		if err == nil {
			existingHash := fmt.Sprintf("%x", md5.Sum(existing))
			newHash := fmt.Sprintf("%x", md5.Sum(content))
			if existingHash == newHash {
				return false, nil
			}
		}
	}
	if err := os.WriteFile(outFile, content, 0644); err != nil {
		return false, err
	}
	return true, nil
}

func bootstrapPackages(regs []bootstrapRegistration) []bootstrapPackage {
	byPath := make(map[string]map[string]struct{})
	for _, reg := range regs {
		if reg.ImportPath == "" || reg.RegisterFunc == "" {
			continue
		}
		funcs := byPath[reg.ImportPath]
		if funcs == nil {
			funcs = make(map[string]struct{})
			byPath[reg.ImportPath] = funcs
		}
		funcs[reg.RegisterFunc] = struct{}{}
	}
	paths := make([]string, 0, len(byPath))
	for path := range byPath {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	usedAliases := make(map[string]string, len(paths))
	packages := make([]bootstrapPackage, 0, len(paths))
	for _, path := range paths {
		funcs := make([]string, 0, len(byPath[path]))
		for fn := range byPath[path] {
			funcs = append(funcs, fn)
		}
		sort.Strings(funcs)
		alias := uniqueBootstrapAlias(path, usedAliases)
		usedAliases[alias] = path
		packages = append(packages, bootstrapPackage{
			Alias:         alias,
			ImportPath:    path,
			RegisterFuncs: funcs,
		})
	}
	return packages
}

func uniqueBootstrapAlias(importPath string, used map[string]string) string {
	base := bootstrapImportAlias(importPath)
	if base == "" {
		base = "nesthandler"
	}
	alias := base
	for i := 2; ; i++ {
		if usedPath, ok := used[alias]; !ok || usedPath == importPath {
			return alias
		}
		alias = fmt.Sprintf("%s%d", base, i)
	}
}

func bootstrapImportAlias(importPath string) string {
	parts := strings.Split(importPath, "/")
	for i, part := range parts {
		if part != "game" {
			continue
		}
		if i+3 < len(parts) && (parts[i+1] == "components" || parts[i+1] == "entities") && parts[len(parts)-1] == "handler" {
			return sanitizeBootstrapAliasPart(parts[i+2]) + "handler"
		}
		break
	}
	if len(parts) >= 2 {
		return sanitizeBootstrapAliasPart(parts[len(parts)-2]) + sanitizeBootstrapAliasPart(parts[len(parts)-1])
	}
	if len(parts) == 1 {
		return sanitizeBootstrapAliasPart(parts[0])
	}
	return ""
}

func sanitizeBootstrapAliasPart(raw string) string {
	var b strings.Builder
	for _, r := range raw {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToLower(r))
		}
	}
	return b.String()
}

func findModuleInfo(start string) (string, string, error) {
	dir := start
	for {
		goMod := filepath.Join(dir, "go.mod")
		raw, err := os.ReadFile(goMod)
		if err == nil {
			for _, line := range strings.Split(string(raw), "\n") {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "module ") {
					modulePath := strings.TrimSpace(strings.TrimPrefix(line, "module "))
					if modulePath == "" {
						return "", "", fmt.Errorf("empty module path in %s", goMod)
					}
					return dir, modulePath, nil
				}
			}
			return "", "", fmt.Errorf("module directive not found in %s", goMod)
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", "", fmt.Errorf("go.mod not found from %s", start)
		}
		dir = parent
	}
}

func importPathForDir(moduleRoot string, modulePath string, dir string) (string, error) {
	rel, err := filepath.Rel(moduleRoot, dir)
	if err != nil {
		return "", err
	}
	if rel == "." {
		return modulePath, nil
	}
	if strings.HasPrefix(rel, "..") {
		return "", fmt.Errorf("%s is outside module root %s", dir, moduleRoot)
	}
	return modulePath + "/" + filepath.ToSlash(rel), nil
}

const bootstrapNestTemplate = `// Code generated by tool/nest. DO NOT EDIT.

package registry

{{- if . }}

import (
{{- range . }}
	{{ .Alias }} "{{ .ImportPath }}"
{{- end }}
)
{{- end }}

// RegisterNestHandlers registers every generated nest handler. It runs once
// via RegisterAll, which owns the sync.Once for all static registration.
//
//roost:register phase=nest
func RegisterNestHandlers() {
{{- range . }}
{{- $alias := .Alias }}
{{- range .RegisterFuncs }}
	{{ $alias }}.{{ . }}()
{{- end }}
{{- end }}
}
`
