package attribute

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func Run(args []string, stdout io.Writer) error {
	flags := flag.NewFlagSet("attribute", flag.ContinueOnError)
	flags.SetOutput(stdout)
	dir := flags.String("dir", ".", "directory to scan")
	output := flags.String("output", "", "output file (default: gen_<profile>_attribute.go)")
	force := flags.Bool("force", false, "force regeneration")
	if err := flags.Parse(args); err != nil {
		return err
	}

	scanDir, err := filepath.Abs(*dir)
	if err != nil {
		return fmt.Errorf("resolve dir: %w", err)
	}
	profiles, err := parseDir(scanDir)
	if err != nil {
		return fmt.Errorf("parse attribute profiles: %w", err)
	}
	if *output != "" && len(profiles) > 1 {
		return fmt.Errorf("-output requires a single attribute profile, found %d", len(profiles))
	}
	if len(profiles) == 0 {
		_, _ = fmt.Fprintf(stdout, "no attribute markers found in %s\n", scanDir)
	}
	expected := make(map[string]bool, len(profiles))
	for _, profile := range profiles {
		outFile := *output
		if outFile == "" {
			outFile = filepath.Join(scanDir, fmt.Sprintf("gen_%s_attribute.go", toSnake(profile.Name)))
		}
		expected[filepath.Clean(outFile)] = true
		content, err := generate(profile)
		if err != nil {
			return fmt.Errorf("generate %s: %w", profile.Name, err)
		}
		changed, err := writeIfChanged(outFile, content, *force)
		if err != nil {
			return fmt.Errorf("write %s: %w", outFile, err)
		}
		if changed {
			_, _ = fmt.Fprintf(stdout, "generated: %s\n", outFile)
		} else {
			_, _ = fmt.Fprintf(stdout, "unchanged: %s\n", outFile)
		}
	}
	if *output != "" {
		if !expected[filepath.Clean(*output)] {
			return retireAttributeFile(*output, stdout)
		}
		return nil
	}
	entries, err := os.ReadDir(scanDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasPrefix(name, "gen_") || !strings.HasSuffix(name, "_attribute.go") {
			continue
		}
		path := filepath.Join(scanDir, name)
		if !expected[path] {
			if err := retireAttributeFile(path, stdout); err != nil {
				return err
			}
		}
	}
	return nil
}

func retireAttributeFile(path string, stdout io.Writer) error {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !bytes.HasPrefix(raw, []byte("// Code generated by tool/attribute. DO NOT EDIT.\n")) {
		return nil
	}
	if err := os.Remove(path); err != nil {
		return err
	}
	_, _ = fmt.Fprintf(stdout, "retired: %s\n", path)
	return nil
}
