// Code generated by tool/protocol. DO NOT EDIT.
package playerhandler

import (
	playercontroller "example.com/planet/game/controllers/player"
	"example.com/planet/game/player_agent"
	"example.com/planet/protocol/pb"
	playerbind "example.com/planet/protocol/player_bind"
	"github.com/tjbdwanghaibo/roost-core/app"
)

type PlayerController interface {
	HandleAddItem(ctx *player_agent.Context, req *pb.AddItemRequest) (*pb.AddItemResponse, error)
	HandleAddExp(ctx *player_agent.Context, req *pb.AddExpRequest) (*pb.AddExpResponse, error)
	HandleEnterGame(ctx *player_agent.Context, req *pb.EnterGameRequest) (*pb.EnterGameResponse, error)
	HandleJoinQueue(ctx *player_agent.Context, req *pb.JoinQueueRequest) (*pb.JoinQueueResponse, error)
	HandlePollMatch(ctx *player_agent.Context, req *pb.PollMatchRequest) (*pb.PollMatchResponse, error)
	HandleWorldStats(ctx *player_agent.Context, req *pb.WorldStatsRequest) (*pb.WorldStatsResponse, error)
	HandleSendChat(ctx *player_agent.Context, req *pb.SendChatRequest) (*pb.SendChatResponse, error)
	HandleChatHistory(ctx *player_agent.Context, req *pb.ChatHistoryRequest) (*pb.ChatHistoryResponse, error)
	HandleListMail(ctx *player_agent.Context, req *pb.ListMailRequest) (*pb.ListMailResponse, error)
	HandleClaimMail(ctx *player_agent.Context, req *pb.ClaimMailRequest) (*pb.ClaimMailResponse, error)
	HandleEnterDungeon(ctx *player_agent.Context, req *pb.EnterDungeonRequest) (*pb.EnterDungeonResponse, error)
	HandleFinishDungeon(ctx *player_agent.Context, req *pb.FinishDungeonRequest) (*pb.FinishDungeonResponse, error)
	HandleSkillCatalog(ctx *player_agent.Context, req *pb.SkillCatalogRequest) (*pb.SkillCatalogResponse, error)
	HandleSendGift(ctx *player_agent.Context, req *pb.SendGiftRequest) (*pb.SendGiftResponse, error)
	HandleGiftStatus(ctx *player_agent.Context, req *pb.GiftStatusRequest) (*pb.GiftStatusResponse, error)
	HandleBattleInput(ctx *player_agent.Context, req *pb.BattleInputRequest) (*pb.BattleInputResponse, error)
	HandleRankTop(ctx *player_agent.Context, req *pb.RankTopRequest) (*pb.RankTopResponse, error)
	HandleMove(ctx *player_agent.Context, req *pb.MoveRequest) (*pb.MoveResponse, error)
	HandleEquip(ctx *player_agent.Context, req *pb.EquipRequest) (*pb.EquipResponse, error)
	HandlePurchase(ctx *player_agent.Context, req *pb.PurchaseRequest) (*pb.PurchaseResponse, error)
	HandleActivityStanding(ctx *player_agent.Context, req *pb.ActivityStandingRequest) (*pb.ActivityStandingResponse, error)
	HandleFoundGuild(ctx *player_agent.Context, req *pb.FoundGuildRequest) (*pb.GuildResponse, error)
	HandleJoinGuild(ctx *player_agent.Context, req *pb.JoinGuildRequest) (*pb.GuildResponse, error)
	HandleGuildInfo(ctx *player_agent.Context, req *pb.GuildInfoRequest) (*pb.GuildResponse, error)
	HandleSceneReady(ctx *player_agent.Context, req *pb.SceneReadyRequest) (*pb.SceneReadyResponse, error)
}

func RegisterPlayerPlayerProtocols(reg *player_agent.ProtocolRegistry, r *app.Registry) error {
	ctl, err := playercontroller.FromRegistry(r)
	if err != nil {
		return err
	}
	return RegisterPlayerPlayerProtocolsWith(reg, ctl)
}

func RegisterPlayerPlayerProtocolsWith(reg *player_agent.ProtocolRegistry, ctl PlayerController) error {
	if err := playerbind.RegisterAddItem(reg, ctl.HandleAddItem); err != nil {
		return err
	}
	if err := playerbind.RegisterAddExp(reg, ctl.HandleAddExp); err != nil {
		return err
	}
	if err := playerbind.RegisterEnterGame(reg, ctl.HandleEnterGame); err != nil {
		return err
	}
	if err := playerbind.RegisterJoinQueue(reg, ctl.HandleJoinQueue); err != nil {
		return err
	}
	if err := playerbind.RegisterPollMatch(reg, ctl.HandlePollMatch); err != nil {
		return err
	}
	if err := playerbind.RegisterWorldStats(reg, ctl.HandleWorldStats); err != nil {
		return err
	}
	if err := playerbind.RegisterSendChat(reg, ctl.HandleSendChat); err != nil {
		return err
	}
	if err := playerbind.RegisterChatHistory(reg, ctl.HandleChatHistory); err != nil {
		return err
	}
	if err := playerbind.RegisterListMail(reg, ctl.HandleListMail); err != nil {
		return err
	}
	if err := playerbind.RegisterClaimMail(reg, ctl.HandleClaimMail); err != nil {
		return err
	}
	if err := playerbind.RegisterEnterDungeon(reg, ctl.HandleEnterDungeon); err != nil {
		return err
	}
	if err := playerbind.RegisterFinishDungeon(reg, ctl.HandleFinishDungeon); err != nil {
		return err
	}
	if err := playerbind.RegisterSkillCatalog(reg, ctl.HandleSkillCatalog); err != nil {
		return err
	}
	if err := playerbind.RegisterSendGift(reg, ctl.HandleSendGift); err != nil {
		return err
	}
	if err := playerbind.RegisterGiftStatus(reg, ctl.HandleGiftStatus); err != nil {
		return err
	}
	if err := playerbind.RegisterBattleInput(reg, ctl.HandleBattleInput); err != nil {
		return err
	}
	if err := playerbind.RegisterRankTop(reg, ctl.HandleRankTop); err != nil {
		return err
	}
	if err := playerbind.RegisterMove(reg, ctl.HandleMove); err != nil {
		return err
	}
	if err := playerbind.RegisterEquip(reg, ctl.HandleEquip); err != nil {
		return err
	}
	if err := playerbind.RegisterPurchase(reg, ctl.HandlePurchase); err != nil {
		return err
	}
	if err := playerbind.RegisterActivityStanding(reg, ctl.HandleActivityStanding); err != nil {
		return err
	}
	if err := playerbind.RegisterFoundGuild(reg, ctl.HandleFoundGuild); err != nil {
		return err
	}
	if err := playerbind.RegisterJoinGuild(reg, ctl.HandleJoinGuild); err != nil {
		return err
	}
	if err := playerbind.RegisterGuildInfo(reg, ctl.HandleGuildInfo); err != nil {
		return err
	}
	return playerbind.RegisterSceneReady(reg, ctl.HandleSceneReady)
}
