package entity

import (
	"bytes"
	"crypto/md5"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"

	"github.com/tjbdwanghaibo/roost-codegen/internal/genutil"
)

const generatorVersion = "v2"

// generate produces the wiring file for an entity that is alone in its
// package. Returns true if the file was written (changed).
func generate(ent EntityDef, pkg string, outFile string, force bool) (bool, error) {
	return generateInPackage(ent, []string{ent.Name}, pkg, outFile, force)
}

// generateInPackage produces the wiring file for one entity of a package that
// holds siblings (sorted entity names, ent.Name among them). Every file declares
// its own register<Name>Entity and once-guard; the package-level RegisterEntity
// that carries the //roost:register marker is emitted once, into the file of
// the first sibling, and calls each of them. Two entities in one package used
// to get two RegisterEntity / registerEntityOnce declarations — generation
// succeeded and the consumer failed to compile (RR-20260909-04).
func generateInPackage(ent EntityDef, siblings []string, pkg string, outFile string, force bool) (bool, error) {
	if len(siblings) == 0 {
		siblings = []string{ent.Name}
	}
	remoteV2 := ent.RemotePolicy == "entity.RemotePolicyManaged"
	if remoteV2 && !ent.RemoteBase {
		return false, fmt.Errorf("entity %s: remote=managed requires embedding *entity.RemoteEntityBase", ent.Name)
	}
	var buf bytes.Buffer

	data := templateData{
		Package:  pkg,
		Entity:   ent,
		Siblings: siblings,
		Primary:  ent.Name == siblings[0],
		HasDaos:  len(ent.Daos) > 0,
		HasComps: len(ent.Components) > 0,
		HasDirty: hasDirtyDao(ent),
		RemoteV2: remoteV2,
	}
	data.NeedsRemove = data.HasDirty && !ent.NoPersist && !data.RemoteV2 && !hasMethod(ent, "PrepareDelete")
	data.ImportBlock = buildImportBlock(ent, data.RemoteV2 || data.NeedsRemove, data.RemoteV2, data.NeedsRemove)

	tmpl, err := template.New("entity_wire").Funcs(template.FuncMap{
		"deref":              derefType,
		"ctor":               constructorName,
		"quote":              quoteString,
		"syncTopic":          syncTopicExpr,
		"syncPackerFactory":  syncPackerFactoryExpr,
		"daoCollectionConst": daoCollectionConstExpr,
		"hasMethod":          hasMethod,
		"join":               strings.Join,
	}).Parse(wireTemplate)
	if err != nil {
		return false, fmt.Errorf("template parse: %w", err)
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return false, fmt.Errorf("template exec: %w", err)
	}

	content, err := format.Source(buf.Bytes())
	if err != nil {
		return false, fmt.Errorf("format generated source: %w", err)
	}

	// Check if file exists and content is unchanged. The companion guard test
	// is reconciled either way, so a project generated before it existed gets
	// it on the next plain run.
	changed := true
	if !force {
		existing, err := os.ReadFile(outFile)
		if err == nil {
			existingHash := fmt.Sprintf("%x", md5.Sum(existing))
			newHash := fmt.Sprintf("%x", md5.Sum(content))
			if existingHash == newHash {
				changed = false
			}
		}
	}
	if changed {
		if err := os.WriteFile(outFile, content, 0644); err != nil {
			return false, err
		}
	}
	testChanged, err := generateGuardTests(data, outFile, force)
	if err != nil {
		return changed, err
	}
	return changed || testChanged, nil
}

// guardTestFile is the generated companion test for a remote-managed entity's
// wiring: guardTestFileFor("x_gen_wire.go") == "x_gen_wire_test.go".
func guardTestFileFor(outFile string) string {
	return strings.TrimSuffix(outFile, ".go") + "_test.go"
}

// generateGuardTests writes (or removes) the companion test that pins the
// remote-commit guards inside the generated wiring. Those guards live in
// generated code, so the generator's own unit tests cannot reach them; a test
// generated into the business project runs them where they are compiled
// (HANDOFF §4.4 / U-0124). Entities that are not remote-managed, or whose DAOs
// are all cold, get no test — and a stale one from an earlier shape is removed
// so it cannot fail to compile against the new wiring.
func generateGuardTests(data templateData, outFile string, force bool) (bool, error) {
	testFile := guardTestFileFor(outFile)
	hasHotDao := false
	for _, dao := range data.Entity.Daos {
		if !dao.Cold {
			hasHotDao = true
		}
	}
	if !data.RemoteV2 || !hasHotDao {
		if existing, err := os.ReadFile(testFile); err == nil && bytes.HasPrefix(existing, []byte("// Code generated by tool/entity.")) {
			return true, os.Remove(testFile)
		}
		return false, nil
	}
	tmpl, err := template.New("entity_guard_tests").Funcs(template.FuncMap{"firstToLower": firstToLower}).Parse(guardTestTemplate)
	if err != nil {
		return false, fmt.Errorf("guard test template parse: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return false, fmt.Errorf("guard test template exec: %w", err)
	}
	content, err := format.Source(buf.Bytes())
	if err != nil {
		return false, fmt.Errorf("format generated guard tests: %w", err)
	}
	return genutil.WriteIfChanged(testFile, content, force)
}

func firstToLower(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

var guardTestTemplate = `// Code generated by tool/entity. DO NOT EDIT.
package {{.Package}}

import (
	"strings"
	"testing"

	"github.com/tjbdwanghaibo/roost-core/entity"
)

// {{firstToLower .Entity.Name}}DeleteChangeSource reports a DAO-level delete for every
// participant, which the remote commit must refuse: a DAO cannot be deleted
// without removing the entity.
type {{firstToLower .Entity.Name}}DeleteChangeSource struct{}

func ({{firstToLower .Entity.Name}}DeleteChangeSource) RemotePersistChangeFor(any) (entity.RemotePersistChange, bool) {
	return entity.RemotePersistChange{Delete: true}, true
}

// Test{{.Entity.Name}}RemoteCommitGuards pins the remote-commit contract of the generated
// wiring where it is compiled: a commit without transaction-local persistence
// changes, a DAO-level delete, and an acknowledgement for another entity are
// each refused instead of producing a partial or misattributed commit.
func Test{{.Entity.Name}}RemoteCommitGuards(t *testing.T) {
	RegisterEntity()
	e, err := New{{.Entity.Name}}(&entity.EntityCreateParam{IsCreate: true, UniqueID: 1, Kind: {{.Entity.EntityKind}}})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := e.BuildRemoteCommitLocked(entity.RemoteWriteLease{}, entity.RemoteTransactionOutcome{}); err == nil || !strings.Contains(err.Error(), "missing transaction-local remote persistence changes") {
		t.Fatalf("BuildRemoteCommitLocked without persistence changes = %v", err)
	}
	if _, err := e.BuildRemoteCommitLocked(entity.RemoteWriteLease{}, entity.RemoteTransactionOutcome{PersistChanges: {{firstToLower .Entity.Name}}DeleteChangeSource{}}); err == nil || !strings.Contains(err.Error(), "DAO-level remote delete requires entity removal") {
		t.Fatalf("BuildRemoteCommitLocked with a DAO-level delete = %v", err)
	}
	if err := e.AcknowledgeRemoteCommit(entity.RemoteCommit{EntityID: e.GUId() + 1}); err == nil || !strings.Contains(err.Error(), "remote acknowledgement identity mismatch") {
		t.Fatalf("AcknowledgeRemoteCommit for another entity = %v", err)
	}
}
`

func derefType(s string) string {
	if len(s) > 0 && s[0] == '*' {
		return s[1:]
	}
	return s
}

func constructorName(typeName string) string {
	name := derefType(typeName)
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		return name[:idx+1] + "New" + name[idx+1:]
	}
	return "New" + name
}

func quoteString(s string) string {
	return fmt.Sprintf("%q", s)
}

// syncPackerFactoryExpr resolves the one packer factory Core's
// EntitySyncBuilderParam takes. Two marker spellings reach it: `subjectPacker`
// (current) and `syncPacker` (kept working for projects written before the
// two collapsed into one). They name the same thing — a
// `func(entity.IThreadSafeEntity) entity.SubjectSyncPacker` — so a marker
// that sets both is refused at parse time rather than silently picking one
// (RR-20260918-01).
func syncPackerFactoryExpr(e EntityDef) string {
	if e.SubjectPacker != "" {
		return e.SubjectPacker
	}
	return e.SyncPacker
}

// syncTopicExpr renders the marker's value. Three spellings reach here, and
// parse.go has already refused the fourth (a bare identifier, which used to be
// quoted into the string of its own name — RR-20260918-07):
//
//	syncTopic=player               → "player"
//	syncTopic="Player"             → "Player"      (already a literal)
//	syncTopic=clientsync.Topic     → clientsync.Topic
func syncTopicExpr(s string) string {
	if s == "" {
		return `""`
	}
	if quoted, ok := unquoteGoString(s); ok {
		return quoteString(quoted)
	}
	if isConstExpr(s) {
		return s
	}
	return quoteString(s)
}

// unquoteGoString reports whether the marker value was written as a quoted
// literal and returns its contents.
func unquoteGoString(s string) (string, bool) {
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1], true
	}
	return "", false
}

func daoCollectionConstExpr(typeName string) string {
	name := derefType(typeName)
	qualifier := ""
	if idx := strings.LastIndex(name, "."); idx >= 0 {
		qualifier = name[:idx+1]
		name = name[idx+1:]
	}
	return qualifier + name + "Collection"
}

func isConstExpr(s string) bool {
	if strings.ContainsAny(s, "\"'`") {
		return false
	}
	idx := strings.Index(s, ".")
	if idx <= 0 || idx == len(s)-1 {
		return false
	}
	first := s[0]
	if (first < 'A' || first > 'Z') && (first < 'a' || first > 'z') && first != '_' {
		return false
	}
	for _, r := range s[:idx] {
		if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '_' {
			return false
		}
	}
	afterDot := s[idx+1]
	return afterDot >= 'A' && afterDot <= 'Z'
}

func hasDirtyDao(ent EntityDef) bool {
	return len(ent.Daos) > 0
}

func hasMethod(ent EntityDef, name string) bool {
	return ent.ExistingMethods != nil && ent.ExistingMethods[name]
}

func buildImportBlock(ent EntityDef, needsFmt, needsDataEngine, needsNest bool) string {
	var groups [][]string
	std := []string{`"sync"`}
	if needsFmt {
		std = append([]string{`"fmt"`}, std...)
	}
	groups = append(groups, std)

	local := make([]string, 0, len(ent.Imports)+2)
	for _, imp := range ent.Imports {
		if imp.Explicit {
			local = append(local, fmt.Sprintf(`%s "%s"`, imp.Alias, imp.Path))
		} else {
			local = append(local, fmt.Sprintf(`"%s"`, imp.Path))
		}
	}
	if needsDataEngine {
		local = append(local, `"github.com/tjbdwanghaibo/roost-core/dataengine"`)
	}
	if needsNest {
		local = append(local, `"github.com/tjbdwanghaibo/roost-core/nest"`)
	}
	local = append(local, `"github.com/tjbdwanghaibo/roost-core/entity"`)
	groups = append(groups, local)

	var b strings.Builder
	for i, group := range groups {
		if i > 0 {
			b.WriteByte('\n')
		}
		for _, line := range group {
			b.WriteByte('\t')
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	return b.String()
}

type templateData struct {
	Package     string
	Entity      EntityDef
	Siblings    []string // every entity of the package, sorted by name
	Primary     bool     // this file carries the package-level RegisterEntity
	ImportBlock string
	HasDaos     bool
	HasComps    bool
	HasDirty    bool
	RemoteV2    bool
	NeedsRemove bool
}

var wireTemplate = `// Code generated by tool/entity. DO NOT EDIT.
package {{.Package}}

import (
{{.ImportBlock -}}
)

var register{{.Entity.Name}}EntityOnce sync.Once
{{if .Primary}}
// RegisterEntity registers every entity generated in this package
// ({{join .Siblings ", "}}). It is the package's single registry entry point;
// each entity keeps its own once-guarded registration below.
//
//roost:register phase=entity
func RegisterEntity() {
{{- range .Siblings}}
	register{{.}}Entity()
{{- end}}
}
{{end}}
// register{{.Entity.Name}}Entity registers the {{.Entity.Name}} entity builder.
func register{{.Entity.Name}}Entity() {
	register{{.Entity.Name}}EntityOnce.Do(func() {
		entity.RegisterEntityBuilder(&entity.EntityBuilderParam{
{{- if .Entity.Category}}
			Category: {{.Entity.Category}},
{{- else}}
			Category: entity.MustEntityCategoryOfKind({{.Entity.EntityKind}}),
{{- end}}
			Kind: {{.Entity.EntityKind}},
			Builder: func(param *entity.EntityCreateParam) (entity.IThreadSafeEntity, error) {
				return New{{.Entity.Name}}(param)
			},
{{- if .HasDaos}}
			DaoBuilders: []entity.DaoBuilderFunc{
{{- range .Entity.Daos}}
				func() entity.DaoInterface { return {{ctor .TypeName}}() },
{{- end}}
			},
{{- end}}
			NoPersist: {{.Entity.NoPersist}},
{{- if .Entity.RemotePolicy}}
			RemotePolicy: {{.Entity.RemotePolicy}},
{{- end}}
{{- if .Entity.Lifetime}}
			Lifetime: {{.Entity.Lifetime}},
{{- end}}
{{- if .Entity.Sync}}
			Sync: entity.EntitySyncBuilderParam{
				Enabled: true,
				Topic:   {{syncTopic .Entity.SyncTopic}},
{{- if syncPackerFactory .Entity}}
				PackerFactory: {{syncPackerFactory .Entity}},
{{- end}}
			},
{{- end}}
		})
{{- if .RemoteV2}}
{{- range .Entity.Daos}}
		entity.MustRegisterRemoteSnapshotDecoder(
			entity.RemoteSnapshotSchema({{$.Entity.EntityKind}}, entity.RemoteSnapshotScope({{daoCollectionConst .TypeName}})),
			func(data []byte) (any, error) {
				dao := {{ctor .TypeName}}()
				decoder, ok := any(dao).(interface{ ApplySync([]byte) error })
				if !ok {
					return nil, fmt.Errorf("{{$.Entity.Name}}: remote snapshot DAO {{.CollName}} does not implement ApplySync")
				}
				if err := decoder.ApplySync(data); err != nil {
					return nil, err
				}
				return dao, nil
			},
		)
{{- end}}
{{- end}}
	})
}

func New{{.Entity.Name}}(param *entity.EntityCreateParam) (*{{.Entity.Name}}, error) {
	e := &{{.Entity.Name}}{}
	if err := param.NormalizeID({{.Entity.EntityKind}}); err != nil {
		return nil, err
	}

	// EntityBase
{{- if .RemoteV2}}
	e.RemoteEntityBase = entity.NewRemoteEntityBaseWithMutex(param.Id, param.Category, {{.Entity.NoPersist}}, param.Mutex, param.Kind)
{{- else}}
	e.EntityBase = entity.NewEntityBaseWithMutex(param.Id, param.Category, {{.Entity.NoPersist}}, param.Mutex, param.Kind)
{{- end}}
	e.EntityBase.SetHooks(e.generatedOnClear, e.generatedOnDestroy)

{{- if .HasComps}}

	// ComponentManager
	e.ComponentManager = entity.NewComponentManager()
{{- end}}
{{- if .HasDaos}}

	// DaoManager
	e.DaoManager = entity.NewDaoManager()
{{- end}}

{{- range .Entity.Daos}}

	// DAO: {{.FieldName}}
	if raw, ok := param.Dao[{{daoCollectionConst .TypeName}}]; ok {
		e.{{.FieldName}} = raw.({{.TypeName}})
	} else {
{{- if .Cold}}
		// cold DAO: initialized on demand
{{- else}}
		e.{{.FieldName}} = {{ctor .TypeName}}()
		e.{{.FieldName}}.SetId(param.StorageID())
{{- end}}
	}
	if e.{{.FieldName}} != nil {
		e.DaoManager.Set({{daoCollectionConst .TypeName}}, e.{{.FieldName}})
	}
{{- end}}

{{- range .Entity.Components}}

	// Component: {{.FieldName}}
{{- if .Cold}}
	// cold component: initialized on demand
{{- else}}
	if comp, err := entity.CreateComponent({{.CompType}}, e, param); err != nil {
		return nil, err
	} else {
		e.{{.FieldName}} = comp.({{.TypeName}})
	}
	e.ComponentManager.Set({{.CompType}}, e.{{.FieldName}})
{{- end}}
{{- end}}

{{- if .HasComps}}

	// Initialize all components in dependency order
	if err := e.ComponentManager.InitAll(param, param.IsCreate); err != nil {
		return nil, err
	}
{{- end}}

	return e, nil
}
{{- if not (hasMethod .Entity "Base")}}

{{- if .RemoteV2}}
func (e *{{.Entity.Name}}) Base() *entity.EntityBase { return &e.RemoteEntityBase.EntityBase }
{{- else}}
func (e *{{.Entity.Name}}) Base() *entity.EntityBase { return e.EntityBase }
{{- end}}
{{- end}}
{{- range .Entity.Components}}
{{- if and .GetterName (not (hasMethod $.Entity .GetterName))}}

func (e *{{$.Entity.Name}}) {{.GetterName}}() {{.GetterType}} { return e.{{.FieldName}} }
{{- end}}
{{- end}}
{{- range .Entity.Daos}}
{{- if and .GetterName (not (hasMethod $.Entity .GetterName))}}

func (e *{{$.Entity.Name}}) {{.GetterName}}() {{.TypeName}} { return e.{{.FieldName}} }
{{- end}}
{{- end}}

func (e *{{.Entity.Name}}) generatedOnClear() {
{{- if .HasComps}}
	e.ComponentManager.Clear()
{{- end}}
{{- if .HasDaos}}
	e.DaoManager.Clear()
{{- end}}
{{- range .Entity.Components}}
	e.{{.FieldName}} = nil
{{- end}}
{{- range .Entity.Daos}}
	e.{{.FieldName}} = nil
{{- end}}
}

func (e *{{.Entity.Name}}) generatedOnDestroy(reason entity.EntityDestroyReason) {
{{- if .HasComps}}
	e.ComponentManager.DestroyAll(reason)
{{- end}}
}
{{- if .RemoteV2}}

var _ entity.IRemoteCommitParticipant = (*{{.Entity.Name}})(nil)
var _ entity.IRemoteCommitChangeParticipant = (*{{.Entity.Name}})(nil)

// HasRemoteCommitLocked consults only the active Nest transaction. Sync dirty
// state is intentionally unrelated to persistence admission.
func (e *{{.Entity.Name}}) HasRemoteCommitLocked(outcome entity.RemoteTransactionOutcome) bool {
	if outcome.DeleteIntents != nil && outcome.DeleteIntents.RemoteDeleteRequested(e.GUId()) { return true }
	if outcome.PersistChanges == nil { return false }
{{- range .Entity.Daos}}
	if e.{{.FieldName}} != nil {
		if _, ok := outcome.PersistChanges.RemotePersistChangeFor(e.{{.FieldName}}); ok { return true }
	}
{{- end}}
	return false
}

// BuildRemoteCommitLocked freezes DAO state while Nest holds the entity mutex.
// The returned commit owns all byte slices and is safe for asynchronous WAL use.
func (e *{{.Entity.Name}}) BuildRemoteCommitLocked(lease entity.RemoteWriteLease, outcome entity.RemoteTransactionOutcome) (entity.RemoteCommit, error) {
	deleteRequested := outcome.DeleteIntents != nil && outcome.DeleteIntents.RemoteDeleteRequested(e.GUId())
	commit := entity.RemoteCommit{
		TransactionID: outcome.TransactionID,
		EntityID:      e.GUId(),
		Kind:          e.GetEntityKind(),
		Delete:        deleteRequested,
		BaseVersion:   lease.BaseVersion,
		NextVersion:   lease.BaseVersion + 1,
		MarkerEpoch:   lease.MarkerEpoch,
		LockFence:     lease.LockFence,
		RouteEpoch:    lease.RouteEpoch,
		Schema:        1,
		Codec:         1,
	}
	if commit.Delete {
{{- range .Entity.Daos}}
		if e.{{.FieldName}} != nil {
			commit.Deletes = append(commit.Deletes, entity.RemoteDataDelete{
				Database: e.{{.FieldName}}.DbName(), DatabaseScope: uint8(dataengine.ResolveDatabaseScope(e.{{.FieldName}})),
				Collection: e.{{.FieldName}}.CollName(), ID: e.{{.FieldName}}.Id(),
			})
		}
		commit.Invalidations = append(commit.Invalidations, entity.RemoteSnapshotKey{
			EntityID: e.GUId(), Kind: e.GetEntityKind(), Scope: entity.RemoteSnapshotScope({{daoCollectionConst .TypeName}}),
		})
{{- end}}
		return commit, nil
	}
{{- range .Entity.Daos}}
	if e.{{.FieldName}} != nil {
		if outcome.PersistChanges == nil {
			return entity.RemoteCommit{}, fmt.Errorf("{{$.Entity.Name}}: missing transaction-local remote persistence changes")
		}
		if change, ok := outcome.PersistChanges.RemotePersistChangeFor(e.{{.FieldName}}); ok {
			if change.Delete {
				return entity.RemoteCommit{}, fmt.Errorf("{{$.Entity.Name}}: DAO-level remote delete requires entity removal for {{.CollName}}")
			}
			mask := change.Mask
			data := append([]byte(nil), e.{{.FieldName}}.MarshalPersist(mask)...)
			if len(data) == 0 {
				return entity.RemoteCommit{}, fmt.Errorf("{{$.Entity.Name}}: empty remote mutation for {{.CollName}}")
			}
			mutation := entity.RemoteDataMutation{
				Database:      e.{{.FieldName}}.DbName(),
				DatabaseScope: uint8(dataengine.ResolveDatabaseScope(e.{{.FieldName}})),
				Collection:    e.{{.FieldName}}.CollName(),
				ID:            e.{{.FieldName}}.Id(),
				Version:       commit.NextVersion,
				Mask:          mask,
				Data:          data,
			}
			commit.Mutations = append(commit.Mutations, mutation)
			scope := entity.RemoteSnapshotScope(e.{{.FieldName}}.CollName())
			commit.Snapshots = append(commit.Snapshots, entity.RemoteSnapshotRecord{
				Key: entity.RemoteSnapshotKey{EntityID: e.GUId(), Kind: e.GetEntityKind(), Scope: scope},
				Schema:   entity.RemoteSnapshotSchema(e.GetEntityKind(), scope),
				Codec:    1,
				Full:     true,
				Data:     append([]byte(nil), data...),
				Checksum: entity.RemoteSnapshotChecksum(data),
			})
		}
	}
{{- end}}
	return commit, nil
}

// AcknowledgeRemoteCommit advances only DAOs present in the authoritative
// remote receipt. The operation is idempotent and allows aggregate-version
// jumps when another DAO changed in an intervening transaction.
func (e *{{.Entity.Name}}) AcknowledgeRemoteCommit(commit entity.RemoteCommit) error {
	if commit.EntityID != e.GUId() {
		return fmt.Errorf("{{.Entity.Name}}: remote acknowledgement identity mismatch")
	}
	for _, mutation := range commit.Mutations {
		switch mutation.Collection {
{{- range .Entity.Daos}}
		case {{daoCollectionConst .TypeName}}:
			if e.{{.FieldName}} != nil {
				if err := e.{{.FieldName}}.DirtyTracker().AdvanceVersion(commit.NextVersion); err != nil { return err }
			}
{{- end}}
		}
	}
	return nil
}

// RollbackRemoteCommit is a no-op: Build freezes transaction-local changes and
// does not mutate DAO persistence state before authoritative acceptance.
func (e *{{.Entity.Name}}) RollbackRemoteCommit(entity.RemoteCommit) {}
{{- end}}
{{- if .NeedsRemove}}

// PrepareDelete registers versioned tombstones in the active Nest transaction.
func (e *{{.Entity.Name}}) PrepareDelete(tx *nest.RollbackTx) error {
	if tx == nil { return nest.ErrTransactionClosed }
{{- range .Entity.Daos}}
	if e.{{.FieldName}} != nil {
		participant, ok := any(e.{{.FieldName}}).(nest.MutationParticipant)
		if !ok { return fmt.Errorf("{{$.Entity.Name}}: DAO {{.CollName}} does not implement nest.MutationParticipant") }
		if err := tx.MarkPersistDelete(participant); err != nil { return err }
	}
{{- end}}
	return nil
}
{{- end}}
`
