package entity

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// U-0124: the remote-commit guards live inside GENERATED code, so no test in
// this repository can execute them. The generator therefore emits a companion
// test into the business project for every remote-managed entity with a hot
// DAO, reconciles it on unchanged runs, and removes a stale one when the entity
// stops being remote-managed (a leftover would fail to compile).
func TestGenerateEmitsAndReconcilesRemoteGuardTests(t *testing.T) {
	entities, pkg, err := parseDir(filepath.Join("testdata", "remote"))
	if err != nil {
		t.Fatal(err)
	}
	if len(entities) != 1 {
		t.Fatalf("entities = %d", len(entities))
	}
	dir := t.TempDir()
	out := filepath.Join(dir, "guild_gen_wire.go")
	if _, err := generate(entities[0], pkg, out, true); err != nil {
		t.Fatal(err)
	}
	testFile := guardTestFileFor(out)
	raw, err := os.ReadFile(testFile)
	if err != nil {
		t.Fatalf("companion guard test was not generated: %v", err)
	}
	generated := string(raw)
	for _, required := range []string{
		"// Code generated by tool/entity. DO NOT EDIT.",
		"func TestGuildRemoteCommitGuards(t *testing.T)",
		"RegisterEntity()",
		"NewGuild(&entity.EntityCreateParam{IsCreate: true, UniqueID: 1, Kind: EntityKindGuild})",
		"missing transaction-local remote persistence changes",
		"DAO-level remote delete requires entity removal",
		"remote acknowledgement identity mismatch",
	} {
		if !strings.Contains(generated, required) {
			t.Errorf("guard test missing %q", required)
		}
	}

	// Unchanged wiring, deleted companion: a plain run restores it.
	if err := os.Remove(testFile); err != nil {
		t.Fatal(err)
	}
	changed, err := generate(entities[0], pkg, out, false)
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("restoring the companion test was not reported as a change")
	}
	if _, err := os.Stat(testFile); err != nil {
		t.Fatalf("companion test not restored on an unchanged run: %v", err)
	}

	// The entity stops being remote-managed: the stale companion is removed.
	local := entities[0]
	local.RemotePolicy = ""
	if _, err := generate(local, pkg, out, true); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(testFile); !os.IsNotExist(err) {
		t.Fatalf("stale companion test survived the entity losing remote management: %v", err)
	}
}
