// Code generated by tool/dao. DO NOT EDIT.

package testdata

import (
	"context"
	"fmt"
	"time"

	fcache "github.com/tjbdwanghaibo/roost-core/cache"
	fredis "github.com/tjbdwanghaibo/roost-core/redis"
)

const (
	RawSessionRedisDAODefaultPrefix = "roost:test:raw"
	RawSessionRedisDAOName          = "raw_session"
)

const RawSessionRedisDAODefaultTTL time.Duration = 0

type RawSessionRedisDAO interface {
	GetRawSession(ctx context.Context, key int64) (RawSession, bool, error)
	SetRawSession(ctx context.Context, value RawSession) error
	DeleteRawSession(ctx context.Context, key int64) error
	PatchRawSession(ctx context.Context, key int64, path string, value any) error
}

type rawSessionRedisDAOStore struct {
	store fcache.Store[int64, RawSession]
}

func NewLocalRawSessionRedisDAO() RawSessionRedisDAO {
	return wrapRawSessionRedisDAOStore(fcache.NewLocalStore[int64, RawSession](rawSessionRedisDAOStoreConfig()))
}

func NewRedisRawSessionRedisDAO(redis fredis.IRedis, prefix string, ttl time.Duration) RawSessionRedisDAO {
	if prefix == "" {
		prefix = RawSessionRedisDAODefaultPrefix
	}
	if ttl <= 0 {
		ttl = RawSessionRedisDAODefaultTTL
	}
	store := fcache.NewRedisRawJSONStore[int64, RawSession](redis, ttl, func(key int64) string {
		return fmt.Sprintf("%s:%v", prefix, key)
	}, rawSessionRedisDAOStoreConfig())
	return wrapRawSessionRedisDAOStore(store)
}

func NewCachedRawSessionRedisDAO(local RawSessionRedisDAO, remote RawSessionRedisDAO) RawSessionRedisDAO {
	return NewCachedRawSessionRedisDAOWithTTL(local, remote, 0)
}

func NewCachedRawSessionRedisDAOWithTTL(local RawSessionRedisDAO, remote RawSessionRedisDAO, ttl time.Duration) RawSessionRedisDAO {
	return wrapRawSessionRedisDAOStore(fcache.NewLayeredStore[int64, RawSession](
		unwrapRawSessionRedisDAOStore(local),
		unwrapRawSessionRedisDAOStore(remote),
		ttl,
		rawSessionRedisDAOStoreConfig(),
	))
}

func (s rawSessionRedisDAOStore) GetRawSession(ctx context.Context, key int64) (RawSession, bool, error) {
	if s.store == nil {
		return RawSession{}, false, nil
	}
	return s.store.Get(ctx, key)
}

func (s rawSessionRedisDAOStore) SetRawSession(ctx context.Context, value RawSession) error {
	if s.store == nil {
		return nil
	}
	return s.store.Set(ctx, value)
}

func (s rawSessionRedisDAOStore) DeleteRawSession(ctx context.Context, key int64) error {
	if s.store == nil {
		return nil
	}
	return s.store.Delete(ctx, key)
}

func (s rawSessionRedisDAOStore) PatchRawSession(ctx context.Context, key int64, path string, value any) error {
	if s.store == nil {
		return nil
	}
	current, ok, err := s.store.Get(ctx, key)
	if err != nil || !ok {
		return err
	}
	if err := fcache.PatchStructPath(&current, path, value); err != nil {
		return err
	}
	return s.store.Set(ctx, current)
}
func wrapRawSessionRedisDAOStore(store fcache.Store[int64, RawSession]) RawSessionRedisDAO {
	return rawSessionRedisDAOStore{store: store}
}

func unwrapRawSessionRedisDAOStore(dao RawSessionRedisDAO) fcache.Store[int64, RawSession] {
	if dao == nil {
		return nil
	}
	if s, ok := dao.(rawSessionRedisDAOStore); ok {
		return s.store
	}
	return rawSessionRedisDAOAdapter{dao: dao}
}

type rawSessionRedisDAOAdapter struct {
	dao RawSessionRedisDAO
}

func (s rawSessionRedisDAOAdapter) Get(ctx context.Context, key int64) (RawSession, bool, error) {
	return s.dao.GetRawSession(ctx, key)
}

func (s rawSessionRedisDAOAdapter) Set(ctx context.Context, value RawSession) error {
	return s.dao.SetRawSession(ctx, value)
}

func (s rawSessionRedisDAOAdapter) Delete(ctx context.Context, key int64) error {
	return s.dao.DeleteRawSession(ctx, key)
}

func rawSessionRedisDAOStoreConfig() fcache.StoreConfig[int64, RawSession] {
	return fcache.StoreConfig[int64, RawSession]{
		KeyOf: func(value RawSession) int64 {
			return value.RunID
		},
	}
}
