// Code generated by tool/dao. DO NOT EDIT.

package testdata

import (
	"context"
	"time"

	fcache "github.com/tjbdwanghaibo/roost-core/cache"
	fredis "github.com/tjbdwanghaibo/roost-core/redis"
)

const (
	CacheSessionRedisDAODefaultPrefix = "roost:test:session"
	CacheSessionRedisDAOName          = "cache_session"
)

const CacheSessionRedisDAODefaultTTL time.Duration = time.Duration(3600000000000)

type CacheSessionRedisDAO interface {
	GetCacheSession(ctx context.Context, key int64) (CacheSession, bool, error)
	SetCacheSession(ctx context.Context, value CacheSession) error
	DeleteCacheSession(ctx context.Context, key int64) error
	PatchCacheSession(ctx context.Context, key int64, path string, value any) error
}

type cacheSessionRedisDAOStore struct {
	store   fcache.Store[int64, CacheSession]
	patcher fcache.RefHMapPatcher[int64]
}

func NewLocalCacheSessionRedisDAO() CacheSessionRedisDAO {
	return wrapCacheSessionRedisDAOStore(fcache.NewLocalStore[int64, CacheSession](cacheSessionRedisDAOStoreConfig()), nil)
}

func NewRedisCacheSessionRedisDAO(redis fredis.IRedis, prefix string, ttl time.Duration) CacheSessionRedisDAO {
	if prefix == "" {
		prefix = CacheSessionRedisDAODefaultPrefix
	}
	if ttl <= 0 {
		ttl = CacheSessionRedisDAODefaultTTL
	}
	store := fcache.NewRedisRefHMapStore[int64, CacheSession](redis, fcache.RefHMapConfig[int64, CacheSession]{
		Prefix:      prefix,
		Name:        CacheSessionRedisDAOName,
		TTL:         ttl,
		StoreConfig: cacheSessionRedisDAOStoreConfig(),
	})
	return wrapCacheSessionRedisDAOStore(store, store)
}

func NewCachedCacheSessionRedisDAO(local CacheSessionRedisDAO, remote CacheSessionRedisDAO) CacheSessionRedisDAO {
	return NewCachedCacheSessionRedisDAOWithTTL(local, remote, 0)
}

func NewCachedCacheSessionRedisDAOWithTTL(local CacheSessionRedisDAO, remote CacheSessionRedisDAO, ttl time.Duration) CacheSessionRedisDAO {
	return wrapCacheSessionRedisDAOStore(fcache.NewLayeredStore[int64, CacheSession](
		unwrapCacheSessionRedisDAOStore(local),
		unwrapCacheSessionRedisDAOStore(remote),
		ttl,
		cacheSessionRedisDAOStoreConfig(),
	), nil)
}

func (s cacheSessionRedisDAOStore) GetCacheSession(ctx context.Context, key int64) (CacheSession, bool, error) {
	if s.store == nil {
		return CacheSession{}, false, nil
	}
	return s.store.Get(ctx, key)
}

func (s cacheSessionRedisDAOStore) SetCacheSession(ctx context.Context, value CacheSession) error {
	if s.store == nil {
		return nil
	}
	return s.store.Set(ctx, value)
}

func (s cacheSessionRedisDAOStore) DeleteCacheSession(ctx context.Context, key int64) error {
	if s.store == nil {
		return nil
	}
	return s.store.Delete(ctx, key)
}

func (s cacheSessionRedisDAOStore) PatchCacheSession(ctx context.Context, key int64, path string, value any) error {
	if s.patcher != nil {
		return s.patcher.Patch(ctx, key, path, value)
	}
	if s.store == nil {
		return nil
	}
	current, ok, err := s.store.Get(ctx, key)
	if err != nil || !ok {
		return err
	}
	if err := fcache.PatchStructPath(&current, path, value); err != nil {
		return err
	}
	return s.store.Set(ctx, current)
}
func wrapCacheSessionRedisDAOStore(store fcache.Store[int64, CacheSession], patcher fcache.RefHMapPatcher[int64]) CacheSessionRedisDAO {
	return cacheSessionRedisDAOStore{store: store, patcher: patcher}
}

func unwrapCacheSessionRedisDAOStore(dao CacheSessionRedisDAO) fcache.Store[int64, CacheSession] {
	if dao == nil {
		return nil
	}
	if s, ok := dao.(cacheSessionRedisDAOStore); ok {
		return s.store
	}
	return cacheSessionRedisDAOAdapter{dao: dao}
}

type cacheSessionRedisDAOAdapter struct {
	dao CacheSessionRedisDAO
}

func (s cacheSessionRedisDAOAdapter) Get(ctx context.Context, key int64) (CacheSession, bool, error) {
	return s.dao.GetCacheSession(ctx, key)
}

func (s cacheSessionRedisDAOAdapter) Set(ctx context.Context, value CacheSession) error {
	return s.dao.SetCacheSession(ctx, value)
}

func (s cacheSessionRedisDAOAdapter) Delete(ctx context.Context, key int64) error {
	return s.dao.DeleteCacheSession(ctx, key)
}

func cacheSessionRedisDAOStoreConfig() fcache.StoreConfig[int64, CacheSession] {
	return fcache.StoreConfig[int64, CacheSession]{
		KeyOf: func(value CacheSession) int64 {
			return value.Snapshot.InstanceRunID
		},
		Stale: fcache.VersionStale(func(value CacheSession) int64 { return int64(value.Version) }),
	}
}
