// Code generated by tool/entity. DO NOT EDIT.
package world

import (
	"fmt"
	"sync"

	db "example.com/planet/db"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var registerWorldEntityOnce sync.Once

// RegisterEntity registers every entity generated in this package
// (World). It is the package's single registry entry point;
// each entity keeps its own once-guarded registration below.
//
//roost:register phase=entity
func RegisterEntity() {
	registerWorldEntity()
}

// registerWorldEntity registers the World entity builder.
func registerWorldEntity() {
	registerWorldEntityOnce.Do(func() {
		entity.RegisterEntityBuilder(&entity.EntityBuilderParam{
			Category: entity.EntityCategoryWorld,
			Kind:     EntityKindWorld,
			Builder: func(param *entity.EntityCreateParam) (entity.IThreadSafeEntity, error) {
				return NewWorld(param)
			},
			DaoBuilders: []entity.DaoBuilderFunc{
				func() entity.DaoInterface { return db.NewWorldDao() },
			},
			NoPersist:    false,
			RemotePolicy: entity.RemotePolicyNone,
			Lifetime:     entity.EntityLifetimePersistedHotCold,
		})
	})
}

func NewWorld(param *entity.EntityCreateParam) (*World, error) {
	e := &World{}
	if err := param.NormalizeID(EntityKindWorld); err != nil {
		return nil, err
	}

	// EntityBase
	e.EntityBase = entity.NewEntityBaseWithMutex(param.Id, param.Category, false, param.Mutex, param.Kind)
	e.EntityBase.SetHooks(e.generatedOnClear, e.generatedOnDestroy)

	// ComponentManager
	e.ComponentManager = entity.NewComponentManager()

	// DaoManager
	e.DaoManager = entity.NewDaoManager()

	// DAO: dao
	if raw, ok := param.Dao[db.WorldDaoCollection]; ok {
		e.dao = raw.(*db.WorldDao)
	} else {
		e.dao = db.NewWorldDao()
		e.dao.SetId(param.StorageID())
	}
	if e.dao != nil {
		e.DaoManager.Set(db.WorldDaoCollection, e.dao)
	}

	// Component: stats
	if comp, err := entity.CreateComponent(CompTypeStats, e, param); err != nil {
		return nil, err
	} else {
		e.stats = comp.(*StatsComponent)
	}
	e.ComponentManager.Set(CompTypeStats, e.stats)

	// Component: timer
	if comp, err := entity.CreateComponent(CompTypeTimer, e, param); err != nil {
		return nil, err
	} else {
		e.timer = comp.(*TimerComponent)
	}
	e.ComponentManager.Set(CompTypeTimer, e.timer)

	// Initialize all components in dependency order
	if err := e.ComponentManager.InitAll(param, param.IsCreate); err != nil {
		return nil, err
	}

	return e, nil
}
func (e *World) Base() *entity.EntityBase { return e.EntityBase }

func (e *World) StatsComp() *StatsComponent { return e.stats }

func (e *World) TimerComp() *TimerComponent { return e.timer }

func (e *World) Dao() *db.WorldDao { return e.dao }

func (e *World) generatedOnClear() {
	e.ComponentManager.Clear()
	e.DaoManager.Clear()
	e.stats = nil
	e.timer = nil
	e.dao = nil
}

func (e *World) generatedOnDestroy(reason entity.EntityDestroyReason) {
	e.ComponentManager.DestroyAll(reason)
}

// PrepareDelete registers versioned tombstones in the active Nest transaction.
func (e *World) PrepareDelete(tx *nest.RollbackTx) error {
	if tx == nil {
		return nest.ErrTransactionClosed
	}
	if e.dao != nil {
		participant, ok := any(e.dao).(nest.MutationParticipant)
		if !ok {
			return fmt.Errorf("World: DAO world does not implement nest.MutationParticipant")
		}
		if err := tx.MarkPersistDelete(participant); err != nil {
			return err
		}
	}
	return nil
}
