package roost

import (
	"bytes"
	"path/filepath"
	"strings"
	"testing"
)

// 承诺：attribute feature 的 runtime.go 是 codegen 受控文件，必须带生成标记——
// 少了它 `project doctor` 的 project-templates 检查会把它当成应用自有文件，
// 报 "refusing to overwrite non-generated file"，整个工程的 doctor 变红。
// 旧行为：文件头写的是自造的 "Code generated by roost."，与 canOverwriteGenerated
// 认的标记对不上（U-0230 引入，随 codegen v1.15.10 发出）。
func TestAttributeRuntimeFileIsMarkedGenerated(t *testing.T) {
	body := renderAttributeRuntime("attribute")
	if !strings.HasPrefix(body, generatedHeader) {
		t.Fatalf("the attribute runtime file does not start with the generated header:\n%s", body[:min(len(body), 120)])
	}
	if !canOverwriteGenerated("game/gameplay/attribute/runtime.go", []byte(body)) {
		t.Error("doctor would refuse to overwrite the attribute runtime file")
	}
	if !strings.Contains(body, "package attribute") {
		t.Error("the rendered file has no package clause for the requested name")
	}
}

// A generated project with the feature must pass doctor's template check.
func TestGeneratedAttributeProjectPassesTheTemplateCheck(t *testing.T) {
	target := filepath.Join(t.TempDir(), "planet")
	_, root, err := NewProject(NewOptions{Name: "planet", Module: "example.com/planet", Out: target, Mods: []string{"configdata"}, Features: []string{"attribute"}})
	if err != nil {
		t.Fatal(err)
	}
	// This is what `project doctor --strict` runs for the project-templates
	// item: a file codegen owns but cannot recognise as generated fails here.
	var diff bytes.Buffer
	if err := DiffProject(root, &diff); err != nil {
		t.Fatalf("doctor's template check refuses a freshly generated project: %v", err)
	}
	if !strings.Contains(diff.String(), "summary: 0 file(s) would change") {
		t.Errorf("a freshly generated project already has stale templates:\n%s", diff.String())
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
