package roost

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"regexp"
)

var generatedComment = regexp.MustCompile(`^((//|#|--) Code generated .+ DO NOT EDIT\.|<!-- Code generated .+ DO NOT EDIT\. -->)$`)

// hasGeneratedHeader 只认真正的生成注释；业务字符串或说明文字不能夺走文件所有权。
func hasGeneratedHeader(path string, raw []byte) bool {
	return generatedBy(path, raw, "")
}

// generatedBy 区分文件分类与覆盖权限：空 producer 只分类，指定 producer 才确认所有权。
func generatedBy(path string, raw []byte, producer string) bool {
	matches := func(line []byte) bool {
		return generatedComment.Match(line) && (producer == "" || bytes.Contains(line, []byte("Code generated by "+producer+". DO NOT EDIT.")))
	}
	if filepath.Ext(path) == ".go" {
		file, err := parser.ParseFile(token.NewFileSet(), path, raw, parser.ParseComments|parser.PackageClauseOnly)
		if err != nil || !ast.IsGenerated(file) {
			return false
		}
		for _, group := range file.Comments {
			for _, comment := range group.List {
				if comment.Slash < file.Package && matches([]byte(comment.Text)) {
					return true
				}
			}
		}
		return false
	}
	for line := range bytes.Lines(raw) {
		line = bytes.TrimSpace(line)
		if matches(line) {
			return true
		}
		if len(line) > 0 && !bytes.HasPrefix(line, []byte("//")) && !bytes.HasPrefix(line, []byte("#")) && !bytes.HasPrefix(line, []byte("--")) && !bytes.HasPrefix(line, []byte("<!--")) {
			return false
		}
	}
	return false
}
