package roost

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"time"
)

const generatedHeader = "// Code generated by roost-codegen. DO NOT EDIT."

type NewOptions struct {
	Name     string
	Module   string
	Out      string
	Services []string
	Mods     []string
	Features []string
	Versions VersionSpec
	// Template is an opt-in starting shape. "game" hosts account, mail, match
	// and chat as their own processes and wires the first service to them.
	Template string
}

type SyncResult struct {
	Created   []string
	Updated   []string
	Removed   []string
	Unchanged []string
}

type plannedFile struct {
	Body  []byte
	Owned bool
}

type syncChange struct {
	rel     string
	path    string
	body    []byte
	before  []byte
	existed bool
	remove  bool
}

func NewProject(options NewOptions) (SyncResult, string, error) {
	if !validName(options.Name) {
		return SyncResult{}, "", fmt.Errorf("invalid project name %q", options.Name)
	}
	manifest := DefaultManifest(options.Name, options.Module, options.Services, options.Mods, options.Features)
	mergeVersions(&manifest.Versions, options.Versions)
	switch strings.TrimSpace(options.Template) {
	case "":
	case "game":
		if err := applyGameTemplate(&manifest, templateGameService(options)); err != nil {
			return SyncResult{}, "", err
		}
	case demoTemplateName:
		if err := applyDemoTemplate(&manifest, templateGameService(options)); err != nil {
			return SyncResult{}, "", err
		}
	default:
		return SyncResult{}, "", fmt.Errorf("unknown template %q; supported: game, %s", options.Template, demoTemplateName)
	}
	if err := manifest.Validate(); err != nil {
		return SyncResult{}, "", err
	}
	target := options.Out
	if target == "" {
		target = options.Name
	}
	absTarget, err := filepath.Abs(target)
	if err != nil {
		return SyncResult{}, "", err
	}
	if _, err := os.Stat(absTarget); err == nil {
		return SyncResult{}, "", fmt.Errorf("target %s already exists", absTarget)
	} else if !os.IsNotExist(err) {
		return SyncResult{}, "", err
	}
	parent := filepath.Dir(absTarget)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return SyncResult{}, "", err
	}
	stage, err := os.MkdirTemp(parent, ".roost-project-*")
	if err != nil {
		return SyncResult{}, "", err
	}
	defer os.RemoveAll(stage)
	manifestRaw, err := manifest.Marshal()
	if err != nil {
		return SyncResult{}, "", err
	}
	if err := writeAtomic(filepath.Join(stage, ManifestName), manifestRaw, 0o644); err != nil {
		return SyncResult{}, "", err
	}
	result, err := syncManifest(stage, manifest)
	if err != nil {
		return SyncResult{}, "", err
	}
	if err := Generate(stage, GenerateOptions{Stdout: io.Discard}); err != nil {
		return SyncResult{}, "", fmt.Errorf("generate initial artifacts: %w", err)
	}
	if err := renameProjectStage(stage, absTarget); err != nil {
		return SyncResult{}, "", fmt.Errorf("commit project: %w", err)
	}
	switch strings.TrimSpace(options.Template) {
	case "game":
		created, err := scaffoldGameTemplate(absTarget, manifest, templateGameService(options))
		result.Created = append(result.Created, created...)
		if err != nil {
			return result, absTarget, err
		}
	case demoTemplateName:
		created, err := scaffoldDemoTemplate(absTarget, manifest, templateGameService(options))
		result.Created = append(result.Created, created...)
		if err != nil {
			return result, absTarget, err
		}
	}
	return result, absTarget, nil
}

// templateGameService is the service a template builds on: the first declared
// one, which is "game" by default.
func templateGameService(options NewOptions) string {
	services := options.Services
	if len(services) == 0 {
		services = []string{"game"}
	}
	return toSnake(services[0])
}

// renameProjectStage is the project creation commit point. Windows virus
// scanners and indexers may briefly open newly generated files without delete
// sharing, causing an otherwise valid directory rename to fail with access
// denied. Retry only that transient Windows condition; existing targets and
// all other errors still fail immediately.
func renameProjectStage(stage, target string) error {
	deadline := time.Now().Add(2 * time.Second)
	delay := 10 * time.Millisecond
	for {
		err := os.Rename(stage, target)
		if err == nil {
			return nil
		}
		if runtime.GOOS != "windows" || !os.IsPermission(err) {
			return err
		}
		if _, statErr := os.Stat(target); statErr == nil || !os.IsNotExist(statErr) {
			return err
		}
		if time.Now().Add(delay).After(deadline) {
			return err
		}
		time.Sleep(delay)
		if delay < 200*time.Millisecond {
			delay *= 2
		}
	}
}

func SyncProject(root string) (SyncResult, error) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return SyncResult{}, err
	}
	manifest, err := LoadManifest(absRoot)
	if err != nil {
		return SyncResult{}, err
	}
	stage, err := os.MkdirTemp(filepath.Dir(absRoot), ".roost-sync-*")
	if err != nil {
		return SyncResult{}, err
	}
	defer os.RemoveAll(stage)
	if err := copyProject(absRoot, stage); err != nil {
		return SyncResult{}, fmt.Errorf("stage project sync: %w", err)
	}
	inputs, err := snapshotProjectInputs(stage, manifest)
	if err != nil {
		return SyncResult{}, fmt.Errorf("snapshot project inputs: %w", err)
	}
	result, err := syncManifest(stage, manifest)
	if err != nil {
		return SyncResult{}, err
	}
	if err := Generate(stage, GenerateOptions{Stdout: io.Discard}); err != nil {
		return SyncResult{}, fmt.Errorf("refresh generated artifacts: %w", err)
	}
	// An obsolete output is expressed as "absent from the staging tree";
	// planStagedProjectCommit then mirrors the deletion into the project,
	// keeping the bytes for rollback. Generators only ever write, so outputs
	// that moved have to be pruned here.
	if err := pruneLegacyKubernetesBase(stage); err != nil {
		return SyncResult{}, fmt.Errorf("prune relocated outputs: %w", err)
	}
	changes, err := planStagedProjectCommit(absRoot, stage, manifest)
	if err != nil {
		return SyncResult{}, err
	}
	mergeStagedChangesIntoResult(&result, changes)
	if err := verifyProjectInputs(absRoot, manifest, inputs); err != nil {
		return SyncResult{}, err
	}
	if err := commitSyncChanges(changes); err != nil {
		return SyncResult{}, err
	}
	return result, nil
}

// planStagedProjectCommit commits only codegen-owned templates and generated
// outputs. Application-owned source was copied into the staging tree solely so
// generators could parse it; it is never copied back implicitly.
func planStagedProjectCommit(root, stage string, manifest Manifest) ([]syncChange, error) {
	plan, err := renderProject(manifest)
	if err != nil {
		return nil, err
	}
	paths := make(map[string]bool, len(plan))
	for rel := range plan {
		paths[filepath.ToSlash(rel)] = true
	}
	if err := filepath.WalkDir(stage, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || !entry.Type().IsRegular() {
			return nil
		}
		raw, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if !bytes.Contains(raw, []byte("Code generated")) && !isGeneratedData(path) {
			return nil
		}
		rel, relErr := filepath.Rel(stage, path)
		if relErr != nil {
			return relErr
		}
		paths[filepath.ToSlash(rel)] = true
		return nil
	}); err != nil {
		return nil, err
	}
	// A generator may intentionally remove an obsolete output in the staging
	// tree. Mirror that deletion only for files that are still recognizably
	// codegen-owned in the real project, and keep their bytes for rollback.
	if err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if path != root && (entry.Name() == ".git" || entry.Name() == "bin" || entry.Name() == "dist" || entry.Name() == "log") {
				return filepath.SkipDir
			}
			return nil
		}
		if !entry.Type().IsRegular() {
			return nil
		}
		raw, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		rel = filepath.ToSlash(rel)
		if !bytes.Contains(raw, []byte("Code generated")) && !isGeneratedData(path) && !isLegacyKubernetesBase(rel, raw) {
			return nil
		}
		if _, exists := paths[rel]; exists {
			return nil
		}
		if _, statErr := os.Stat(filepath.Join(stage, filepath.FromSlash(rel))); os.IsNotExist(statErr) {
			paths[rel] = false
		} else if statErr != nil {
			return statErr
		}
		return nil
	}); err != nil {
		return nil, err
	}
	ordered := make([]string, 0, len(paths))
	for rel := range paths {
		ordered = append(ordered, rel)
	}
	sort.Strings(ordered)
	changes := make([]syncChange, 0, len(ordered))
	for _, rel := range ordered {
		stagedPath := filepath.Join(stage, filepath.FromSlash(rel))
		body, readErr := os.ReadFile(stagedPath)
		if readErr != nil {
			if os.IsNotExist(readErr) && !paths[rel] {
				target := filepath.Join(root, filepath.FromSlash(rel))
				before, targetErr := os.ReadFile(target)
				if targetErr != nil {
					return nil, targetErr
				}
				changes = append(changes, syncChange{rel: rel, path: target, before: before, existed: true, remove: true})
				continue
			}
			if os.IsNotExist(readErr) {
				continue
			}
			return nil, readErr
		}
		target := filepath.Join(root, filepath.FromSlash(rel))
		before, targetErr := os.ReadFile(target)
		switch {
		case targetErr == nil && bytes.Equal(before, body):
			continue
		case targetErr == nil:
			changes = append(changes, syncChange{rel: rel, path: target, body: body, before: before, existed: true})
		case os.IsNotExist(targetErr):
			changes = append(changes, syncChange{rel: rel, path: target, body: body})
		default:
			return nil, targetErr
		}
	}
	return changes, nil
}

func mergeStagedChangesIntoResult(result *SyncResult, changes []syncChange) {
	known := make(map[string]bool, len(result.Created)+len(result.Updated)+len(result.Removed))
	for _, rel := range result.Created {
		known[rel] = true
	}
	for _, rel := range result.Updated {
		known[rel] = true
	}
	for _, rel := range result.Removed {
		known[rel] = true
	}
	for _, change := range changes {
		for index, rel := range result.Unchanged {
			if rel == change.rel {
				result.Unchanged = append(result.Unchanged[:index], result.Unchanged[index+1:]...)
				break
			}
		}
		if known[change.rel] {
			continue
		}
		switch {
		case change.remove:
			result.Removed = append(result.Removed, change.rel)
		case change.existed:
			result.Updated = append(result.Updated, change.rel)
		default:
			result.Created = append(result.Created, change.rel)
		}
	}
	sort.Strings(result.Created)
	sort.Strings(result.Updated)
	sort.Strings(result.Removed)
}

func planExplicitStagedFiles(root, stage string, rels ...string) ([]syncChange, error) {
	changes := make([]syncChange, 0, len(rels))
	for _, rel := range rels {
		rel = filepath.ToSlash(rel)
		stagedPath := filepath.Join(stage, filepath.FromSlash(rel))
		targetPath := filepath.Join(root, filepath.FromSlash(rel))
		body, stagedErr := os.ReadFile(stagedPath)
		before, targetErr := os.ReadFile(targetPath)
		switch {
		case stagedErr == nil && targetErr == nil && bytes.Equal(body, before):
			continue
		case stagedErr == nil && targetErr == nil:
			changes = append(changes, syncChange{rel: rel, path: targetPath, body: body, before: before, existed: true})
		case stagedErr == nil && os.IsNotExist(targetErr):
			changes = append(changes, syncChange{rel: rel, path: targetPath, body: body})
		case os.IsNotExist(stagedErr) && targetErr == nil:
			changes = append(changes, syncChange{rel: rel, path: targetPath, before: before, existed: true, remove: true})
		case os.IsNotExist(stagedErr) && os.IsNotExist(targetErr):
			continue
		case stagedErr != nil:
			return nil, stagedErr
		default:
			return nil, targetErr
		}
	}
	return changes, nil
}

// isLegacyKubernetesBase recognises the Kubernetes base manifests generators
// before the base/ directory wrote straight under deploy/k8s/, without a
// generated header. They are codegen's output and must go when the base
// moves, or the tree carries two copies of every workload — but only files
// this generator demonstrably wrote qualify: the fixed names it used, or a
// manifest in the "roost" namespace. A hand-written deploy/k8s/extra.yaml
// stays. Secret examples were never owned and are left alone.
func isLegacyKubernetesBase(rel string, raw []byte) bool {
	dir, name := path.Split(rel)
	if dir != "deploy/k8s/" || !strings.HasSuffix(name, ".yaml") || strings.HasPrefix(name, "secret.") {
		return false
	}
	switch name {
	case "kustomization.yaml", "namespace.yaml", "service-account.yaml", "network-policy.yaml":
		return bytes.Contains(raw, []byte("roost"))
	}
	return bytes.Contains(raw, []byte("namespace: roost"))
}

// pruneLegacyKubernetesBase removes, from the staging tree, the Kubernetes
// base manifests that pre-base/ generators wrote straight under deploy/k8s/.
// The commit planner turns each into a removal of the real file — provided it
// recognises the real file as codegen's, which isLegacyKubernetesBase does.
func pruneLegacyKubernetesBase(stage string) error {
	entries, err := os.ReadDir(filepath.Join(stage, "deploy", "k8s"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	for _, entry := range entries {
		if !entry.Type().IsRegular() {
			continue
		}
		full := filepath.Join(stage, "deploy", "k8s", entry.Name())
		raw, err := os.ReadFile(full)
		if err != nil {
			return err
		}
		if !isLegacyKubernetesBase("deploy/k8s/"+entry.Name(), raw) {
			continue
		}
		if err := os.Remove(full); err != nil {
			return err
		}
	}
	return nil
}

func mergeSyncChanges(groups ...[]syncChange) ([]syncChange, error) {
	byPath := make(map[string]syncChange)
	for _, group := range groups {
		for _, change := range group {
			if existing, ok := byPath[change.rel]; ok {
				if existing.path != change.path || existing.existed != change.existed || existing.remove != change.remove ||
					!bytes.Equal(existing.before, change.before) || !bytes.Equal(existing.body, change.body) {
					return nil, fmt.Errorf("conflicting staged changes for %s", change.rel)
				}
				continue
			}
			byPath[change.rel] = change
		}
	}
	merged := make([]syncChange, 0, len(byPath))
	for _, change := range byPath {
		merged = append(merged, change)
	}
	return merged, nil
}

func commitSyncChanges(changes []syncChange) error {
	for index, change := range changes {
		if err := verifySyncChangeCurrent(change); err != nil {
			return errors.Join(err, rollbackSync(changes[:index]))
		}
		var err error
		if change.remove {
			err = os.Remove(change.path)
		} else {
			err = writeAtomic(change.path, change.body, 0o644)
		}
		if err != nil {
			return errors.Join(fmt.Errorf("commit %s: %w", change.rel, err), rollbackSync(changes[:index]))
		}
	}
	return nil
}

func syncManifest(root string, manifest Manifest) (SyncResult, error) {
	result, changes, err := planManifestSync(root, manifest)
	if err != nil {
		return SyncResult{}, err
	}
	if err := commitSyncChanges(changes); err != nil {
		return SyncResult{}, err
	}
	return result, nil
}

// verifySyncChangeCurrent is an optimistic concurrency guard. Planning and
// generation intentionally happen without holding an application-wide lock,
// so a developer or another codegen process may edit a target before commit.
// In that case we abort instead of silently replacing the newer content.
func verifySyncChangeCurrent(change syncChange) error {
	current, err := os.ReadFile(change.path)
	switch {
	case change.existed && err == nil && bytes.Equal(current, change.before):
		return nil
	case !change.existed && os.IsNotExist(err):
		return nil
	case err != nil && !os.IsNotExist(err):
		return fmt.Errorf("verify %s before commit: %w", change.rel, err)
	default:
		return fmt.Errorf("refusing to overwrite concurrently changed file %s; rerun the command", change.rel)
	}
}

func planManifestSync(root string, manifest Manifest) (SyncResult, []syncChange, error) {
	plan, err := renderProject(manifest)
	if err != nil {
		return SyncResult{}, nil, err
	}
	paths := make([]string, 0, len(plan))
	for path := range plan {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	var result SyncResult
	var changes []syncChange
	// Preflight the entire plan before writing anything. This prevents a late
	// ownership conflict from leaving an earlier generated file updated.
	for _, rel := range paths {
		file := plan[rel]
		path := filepath.Join(root, filepath.FromSlash(rel))
		current, readErr := os.ReadFile(path)
		switch {
		case readErr == nil && bytes.Equal(current, file.Body):
			result.Unchanged = append(result.Unchanged, rel)
		case readErr == nil && !file.Owned:
			result.Unchanged = append(result.Unchanged, rel)
		case readErr == nil:
			if !canOverwriteGenerated(rel, current) {
				return SyncResult{}, nil, fmt.Errorf("refusing to overwrite non-generated file %s", rel)
			}
			changes = append(changes, syncChange{rel: rel, path: path, body: file.Body, before: current, existed: true})
			result.Updated = append(result.Updated, rel)
		case os.IsNotExist(readErr):
			changes = append(changes, syncChange{rel: rel, path: path, body: file.Body})
			result.Created = append(result.Created, rel)
		default:
			return SyncResult{}, nil, readErr
		}
	}
	return result, changes, nil
}

func canOverwriteGenerated(rel string, current []byte) bool {
	return bytes.Contains(current, []byte("Code generated by roost-codegen")) ||
		(rel == "Dockerfile" && bytes.Contains(current, []byte("ARG GO_VERSION=1.25")) && bytes.Contains(current, []byte("gcr.io/distroless/static-debian12:nonroot"))) ||
		strings.HasPrefix(rel, ".github/") ||
		strings.HasPrefix(rel, "deploy/dev/") ||
		strings.HasPrefix(rel, "deploy/shell/") ||
		strings.HasPrefix(rel, "deploy/docker/") ||
		strings.HasPrefix(rel, "deploy/k8s/")
}

func rollbackSync(applied []syncChange) error {
	var joined error
	for index := len(applied) - 1; index >= 0; index-- {
		change := applied[index]
		current, readErr := os.ReadFile(change.path)
		if readErr != nil && !os.IsNotExist(readErr) {
			joined = errors.Join(joined, fmt.Errorf("inspect %s before rollback: %w", change.rel, readErr))
			continue
		}
		if readErr == nil && (change.remove || !bytes.Equal(current, change.body)) {
			joined = errors.Join(joined, fmt.Errorf("rollback skipped concurrently changed file %s", change.rel))
			continue
		}
		if change.existed {
			if err := writeAtomic(change.path, change.before, 0o644); err != nil {
				joined = errors.Join(joined, fmt.Errorf("rollback %s: %w", change.rel, err))
			}
			continue
		}
		if err := os.Remove(change.path); err != nil && !os.IsNotExist(err) {
			joined = errors.Join(joined, fmt.Errorf("rollback new %s: %w", change.rel, err))
		}
	}
	return joined
}

func writeAtomic(path string, data []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".roost-write-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err = tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err = tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err = tmp.Close(); err != nil {
		return err
	}
	if err = os.Chmod(tmpName, mode); err != nil {
		return err
	}
	if err = os.Rename(tmpName, path); err != nil {
		// Some Windows filesystems cannot replace an existing destination with
		// Rename. Use a unique sibling backup: a crash can leave a recoverable
		// copy, and a later run never deletes an earlier recovery artifact.
		if _, statErr := os.Stat(path); statErr != nil {
			return err
		}
		backupFile, backupErr := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".roost-backup-*")
		if backupErr != nil {
			return errors.Join(err, backupErr)
		}
		backup := backupFile.Name()
		if closeErr := backupFile.Close(); closeErr != nil {
			_ = os.Remove(backup)
			return errors.Join(err, closeErr)
		}
		if removeErr := os.Remove(backup); removeErr != nil {
			return errors.Join(err, removeErr)
		}
		if moveErr := os.Rename(path, backup); moveErr != nil {
			return err
		}
		if moveErr := os.Rename(tmpName, path); moveErr != nil {
			restoreErr := os.Rename(backup, path)
			if restoreErr != nil {
				return errors.Join(moveErr, fmt.Errorf("restore original from %s: %w", backup, restoreErr))
			}
			return moveErr
		}
		_ = os.Remove(backup)
	}
	return nil
}

func mergeVersions(target *VersionSpec, override VersionSpec) {
	if override.Core != "" {
		target.Core = override.Core
	}
	if override.Kit != "" {
		target.Kit = override.Kit
	}
	if override.Skill != "" {
		target.Skill = override.Skill
	}
	if override.Service != "" {
		target.Service = override.Service
	}
	if override.Codegen != "" {
		target.Codegen = override.Codegen
	}
}

func printSyncResult(w io.Writer, result SyncResult) {
	for _, path := range result.Created {
		fmt.Fprintf(w, "created: %s\n", path)
	}
	for _, path := range result.Updated {
		fmt.Fprintf(w, "updated: %s\n", path)
	}
	for _, path := range result.Removed {
		fmt.Fprintf(w, "removed: %s\n", path)
	}
	fmt.Fprintf(w, "summary: created=%d updated=%d removed=%d unchanged=%d\n", len(result.Created), len(result.Updated), len(result.Removed), len(result.Unchanged))
}

func projectRoot(start string) (string, error) {
	root, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(root, ManifestName)); err == nil {
			return root, nil
		}
		parent := filepath.Dir(root)
		if parent == root {
			return "", errors.New("roost.yaml not found")
		}
		root = parent
	}
}
