package roost

import (
	"fmt"
	"strings"
)

func renderDependencyUpdateCI(m Manifest) string {
	return replaceDeployTokens(`# Code generated by roost-codegen. DO NOT EDIT.
name: dependency-update

on:
  schedule:
    - cron: "23 2 * * 1"
  workflow_dispatch:

concurrency:
  group: dependency-update
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true
      - name: upgrade managed templates and dependencies
        run: |
          go run github.com/tjbdwanghaibo/roost-codegen/cmd/roost@latest project upgrade --root . -core latest -kit latest -skill latest -codegen latest
          make roost-up
          make ci
      - name: create dependency pull request
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: roost/dependency-update-${{ github.run_id }}
        run: |
          if git diff --quiet; then
            echo "dependencies are current"
            exit 0
          fi
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -b "$BRANCH"
          git add -A
          git commit -m "chore: upgrade roost framework dependencies"
          git push origin "$BRANCH"
          gh pr create --base "${GITHUB_REF_NAME}" --head "$BRANCH" --title "chore: upgrade roost framework dependencies" --body "Automated project template and dependency upgrade. All generated checks passed before this PR was opened."
`, m)
}

func renderReleaseCI(m Manifest) string {
	return replaceDeployTokens(`# Code generated by roost-codegen. DO NOT EDIT.
name: release

on:
  push:
    tags: ["v*"]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true
      - name: validate release tag and repository state
        run: |
          echo "$GITHUB_REF_NAME" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$' || { echo "release tag must be vMAJOR.MINOR.PATCH"; exit 1; }
          test -z "$(git status --porcelain)"
          if grep -Eq '^[[:space:]]*replace([[:space:]]|\()' go.mod; then echo "go.mod has a replace directive"; exit 1; fi
          go mod download
          go mod verify
          make ci

  artifacts:
    needs: verify
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true
      - name: build immutable shell artifacts
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          mkdir -p dist/package
          for arch in amd64 arm64; do
            GOOS=linux GOARCH="$arch" OUTPUT_DIR="dist/package/linux-$arch" sh deploy/shell/build.sh
            tar -C "dist/package/linux-$arch" -czf "dist/{{APP}}-${VERSION}-linux-${arch}.tar.gz" {{APP}}
          done
      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0
        with:
          path: dist/package
          format: spdx-json
          output-file: dist/{{APP}}-${{ github.ref_name }}.spdx.json
          upload-artifact: false
      - name: checksum release files
        run: |
          cd dist
          sha256sum ./*.tar.gz ./*.spdx.json > SHA256SUMS
      - uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2
        with:
          subject-path: "dist/*.tar.gz"
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: release-artifacts
          path: |
            dist/*.tar.gz
            dist/*.spdx.json
            dist/SHA256SUMS
          if-no-files-found: error
      - name: publish GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "$GITHUB_REF_NAME" dist/*.tar.gz dist/*.spdx.json dist/SHA256SUMS --verify-tag --generate-notes

  image:
    needs: verify
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - id: build
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          build-args: VERSION=${{ github.ref_name }}
          provenance: mode=max
          sbom: true
      - uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
      - uses: anchore/scan-action@1638637db639e0ade3258b51db49a9a137574c3e # v6
        with:
          image: ghcr.io/${{ github.repository }}@${{ steps.build.outputs.digest }}
          fail-build: true
          severity-cutoff: high
      - name: publish immutable image digest
        run: echo "ghcr.io/${GITHUB_REPOSITORY}@${{ steps.build.outputs.digest }}" >> "$GITHUB_STEP_SUMMARY"
`, m)
}

func renderShellDeployCI(m Manifest) string {
	return replaceDeployTokens(`# Code generated by roost-codegen. DO NOT EDIT.
name: deploy-shell

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Protected GitHub Environment
        required: true
        type: choice
        options: [staging, production]
      action:
        description: Deploy a new release or roll back to an installed release
        required: true
        type: choice
        options: [deploy, rollback]
      version:
        description: Immutable release tag, for example v1.2.0
        required: true
        type: string
      service:
        description: Service name from roost.yaml
        required: true
        type: string
      sid:
        description: Unique positive server identity
        required: true
        type: string

concurrency:
  group: shell-${{ inputs.environment }}-${{ inputs.service }}-${{ inputs.sid }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: [self-hosted, linux, roost-shell]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: validate inputs
        env:
          VERSION: ${{ inputs.version }}
          SID: ${{ inputs.sid }}
        run: |
          echo "$VERSION" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$' || { echo "invalid release version"; exit 2; }
          case "$SID" in *[!0-9]*|0|'') echo "invalid SID"; exit 2;; esac
      - name: download and verify release artifact
        if: inputs.action == 'deploy'
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ inputs.version }}
        run: |
          rm -rf dist/release
          mkdir -p dist/release
          gh release download "$VERSION" --dir dist/release --pattern "{{APP}}-${VERSION}-linux-$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" --pattern SHA256SUMS
          cd dist/release
          sha256sum -c SHA256SUMS --ignore-missing
          tar -xzf {{APP}}-*.tar.gz
          install -m 0755 {{APP}} ../{{APP}}
      - name: atomically deploy and verify readiness
        if: inputs.action == 'deploy'
        env:
          SERVICE: ${{ inputs.service }}
          SID: ${{ inputs.sid }}
          VERSION: ${{ inputs.version }}
          CONFIG_PATH: ${{ vars.ROOST_CONFIG_PATH }}
        run: sudo -E sh deploy/shell/install.sh "$SERVICE" "$SID" "$VERSION" "$CONFIG_PATH"
      - name: roll back to an installed immutable release
        if: inputs.action == 'rollback'
        env:
          SERVICE: ${{ inputs.service }}
          SID: ${{ inputs.sid }}
          VERSION: ${{ inputs.version }}
        run: sudo -E sh deploy/shell/rollback.sh "$SERVICE" "$SID" "$VERSION"
`, m)
}

func renderDockerDeployCI(m Manifest) string {
	return replaceDeployTokens(`# Code generated by roost-codegen. DO NOT EDIT.
name: deploy-docker

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options: [staging, production]
      image:
        description: Full immutable image reference including sha256 digest
        required: true
        type: string

concurrency:
  group: docker-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: [self-hosted, linux, roost-docker]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: require immutable digest
        env:
          ROOST_IMAGE: ${{ inputs.image }}
        run: echo "$ROOST_IMAGE" | grep -Eq '^ghcr\.io/.+@sha256:[0-9a-f]{64}$'
      - name: deploy compose and wait for health
        env:
          ROOST_IMAGE: ${{ inputs.image }}
          ROOST_ENV_FILE: ${{ vars.ROOST_ENV_FILE }}
        run: sh deploy/docker/deploy.sh
`, m)
}

func renderKubernetesDeployCI(m Manifest) string {
	return replaceDeployTokens(`# Code generated by roost-codegen. DO NOT EDIT.
name: deploy-k8s

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options: [staging, production]
      image:
        description: Full immutable image reference including sha256 digest
        required: true
        type: string

concurrency:
  group: k8s-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: [self-hosted, linux, roost-k8s]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: validate immutable image
        env:
          ROOST_IMAGE: ${{ inputs.image }}
        run: echo "$ROOST_IMAGE" | grep -Eq '^ghcr\.io/.+@sha256:[0-9a-f]{64}$'
      - name: render, dry-run and deploy
        env:
          ROOST_IMAGE: ${{ inputs.image }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: sh deploy/k8s/deploy.sh
`, m)
}

func renderDependabot() string {
	return `# Code generated by roost-codegen. DO NOT EDIT.
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
`
}

func renderActionlintConfig() string {
	return `# Code generated by roost-codegen. DO NOT EDIT.
self-hosted-runner:
  labels:
    - roost-shell
    - roost-docker
    - roost-k8s
`
}

func renderGeneratedSecurityCI() string {
	return `# Code generated by roost-codegen. DO NOT EDIT.
name: security

on:
  pull_request:
  push:
    branches: [main, master]
  schedule:
    - cron: "11 4 * * 4"

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  vulnerabilities:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true
      - run: go run golang.org/x/vuln/cmd/govulncheck@v1.7.0 ./...

  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/dependency-review-action@56339e523c0409420f6c2c9a2f4292bbb3c07dd3 # v4.8.0

  codeql:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: github/codeql-action/init@6f5948dfacef28e207b48d0905cf90c03365536d # v3
        with:
          languages: go,actions
      - uses: github/codeql-action/autobuild@6f5948dfacef28e207b48d0905cf90c03365536d # v3
      - uses: github/codeql-action/analyze@6f5948dfacef28e207b48d0905cf90c03365536d # v3
`
}

func renderProductionCompose(m Manifest) string {
	var b strings.Builder
	b.WriteString("# Code generated by roost-codegen. DO NOT EDIT.\nservices:\n")
	for index, service := range sortedServiceNames(m) {
		sid := 1000 + index
		fmt.Fprintf(&b, "  %s:\n", service)
		b.WriteString("    image: ${ROOST_IMAGE:?ROOST_IMAGE must be an immutable digest}\n")
		fmt.Fprintf(&b, "    container_name: %s-%s\n", m.Project.Name, service)
		fmt.Fprintf(&b, "    command: [%q, \"--sid=%d\", \"--config=/etc/roost/config.yaml\"]\n", service, sid)
		b.WriteString("    restart: unless-stopped\n    read_only: true\n    init: true\n    user: \"65532:65532\"\n    cap_drop: [ALL]\n    security_opt: [no-new-privileges:true]\n    tmpfs: [/tmp:rw,noexec,nosuid,size=64m]\n")
		b.WriteString("    stop_grace_period: 45s\n    healthcheck:\n      test: [CMD, /app/healthprobe, http://127.0.0.1:9100/readyz]\n      interval: 10s\n      timeout: 3s\n      retries: 6\n      start_period: 30s\n")
		// Long syntax with an explicit type. In short syntax a source that
		// does not begin with "/", "./" or "../" is a NAMED volume, so a
		// relative ROOST_CONFIG_ROOT made compose report "refers to undefined
		// volume" — in every generated project's CI.
		b.WriteString("    volumes:\n")
		b.WriteString("      - type: bind\n")
		fmt.Fprintf(&b, "        source: ${ROOST_CONFIG_ROOT:?ROOST_CONFIG_ROOT is required}/config.%s.yaml\n", service)
		b.WriteString("        target: /etc/roost/config.yaml\n        read_only: true\n")
		if serviceUsesPersistentWAL(m, service) {
			fmt.Fprintf(&b, "      - type: volume\n        source: %s-%s-wal\n        target: /var/lib/roost/wal\n", m.Project.Name, service)
		}
		b.WriteString("    deploy:\n      resources:\n        limits: {cpus: \"2\", memory: 2G}\n        reservations: {cpus: \"0.25\", memory: 256M}\n")
	}
	hasVolumes := false
	for _, service := range sortedServiceNames(m) {
		if !serviceUsesPersistentWAL(m, service) {
			continue
		}
		if !hasVolumes {
			b.WriteString("volumes:\n")
			hasVolumes = true
		}
		fmt.Fprintf(&b, "  %s-%s-wal: {}\n", m.Project.Name, service)
	}
	return b.String()
}
