package roost

import (
	"fmt"
	"strings"

	"github.com/tjbdwanghaibo/roost-core/codegen/internal/protocol"
)

func renderPlayerTCPConfig() string {
	return `# Code generated by roost-codegen. DO NOT EDIT.
# Reference copy. roost add transport tcp automatically adds this
# block to the owning service configs without changing unrelated YAML.
# The listener stays disabled until auth.go is implemented and the explicit
# roost config enable player-tcp command succeeds.
` + playerTCPBlockSchema().StarterYAML(nil)
}

func renderPlayerTCPAuthenticator() string {
	return `package tcp

import (
	"context"
	"net"

	"github.com/spf13/viper"
	"github.com/tjbdwanghaibo/roost-core/infra/network/gateway"
)

// applicationAuthenticator is application-owned. Validate a signed, expiring
// login token here and return a stable, non-zero PlayerID and SessionID.
// Keep the default fail-closed implementation in production until real auth is
// wired; accepting an unverified player id from the socket is unsafe.
type applicationAuthenticator struct{}

func newApplicationAuthenticator(_ *viper.Viper) (Authenticator, error) {
	// TODO: load a verifier/key reference from config or Secret storage and
	// return an authenticator with all immutable dependencies initialized.
	return applicationAuthenticator{}, nil
}

func (applicationAuthenticator) Authenticate(context.Context, string, net.Addr) (gateway.Principal, error) {
	return gateway.Principal{}, gateway.ErrUnauthenticated
}
`
}

func renderPlayerTCPProbe() string {
	return `// Code generated by roost-codegen. DO NOT EDIT.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"net"
	"os"
	"time"

	"github.com/tjbdwanghaibo/roost-core/client/wire"
)

func main() {
	addr := flag.String("addr", "127.0.0.1:7000", "player TCP address")
	timeout := flag.Duration("timeout", 5*time.Second, "connect and handshake timeout")
	flag.Parse()
	if flag.NArg() != 0 { fail("unexpected arguments: %v", flag.Args()) }
	token := os.Getenv("ROOST_PLAYER_TOKEN")
	if token == "" { fail("ROOST_PLAYER_TOKEN is empty; export a short-lived test ticket without putting it in shell history") }
	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()
	dialer := net.Dialer{}
	connection, err := dialer.DialContext(ctx, "tcp", *addr)
	if err != nil { fail("connect %s: %v", *addr, err) }
	defer connection.Close()
	deadline, _ := ctx.Deadline()
	_ = connection.SetDeadline(deadline)
	if err := writeAuth(connection, []byte(token)); err != nil { fail("write authentication frame: %v", err) }
	if err := readAck(connection); err != nil { fail("authentication failed: %v", err) }
	fmt.Printf("player TCP authentication succeeded: %s\n", *addr)
}

func writeAuth(writer io.Writer, token []byte) error {
 if len(token) == 0 || len(token) > 8192 { return fmt.Errorf("ticket size %d is outside 1..8192 bytes", len(token)) }
 return wire.Write(writer, []*wire.Packet{{MsgID:0,Seq:1,Payload:token}},8192)
}

func readAck(reader io.Reader) error {
 packet, err := wire.Read(reader,8192)
 if err != nil { return err }
 if packet.Flags != 0 || packet.MsgID != 0 || packet.Seq != 1 || len(packet.Payload) != 0 {
  return errors.New("invalid authentication acknowledgement")
 }
 return nil
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "playerprobe: "+format+"\n", args...)
	os.Exit(1)
}
`
}

func renderPlayerTCPServer(manifest Manifest) string {
	return strings.Replace(renderPlayerTCPServerSource(manifest), "@@TCP_CONFIG_DECLARATION@@", renderPlayerTCPDeclaration(), 1)
}

func renderPlayerTCPServerSource(manifest Manifest) string {
	return fmt.Sprintf(`// Code generated by roost-codegen. DO NOT EDIT.
package tcp

import (
 "context"
 "errors"
 "fmt"
 "log/slog"
 "net"
 "time"
 "github.com/spf13/viper"
 "github.com/tjbdwanghaibo/roost-core/client/wire"
 "github.com/tjbdwanghaibo/roost-core/framework/app"
 "github.com/tjbdwanghaibo/roost-core/infra/network/gateway"
 gatewiring "github.com/tjbdwanghaibo/roost-core/wiring/gate"
 accessplayer %q
 %q
)

const Name app.ModName = "access.player.tcp"
const ( defaultDispatchTimeout = 3*time.Second; defaultLoginTimeout = 2*time.Second )

@@TCP_CONFIG_DECLARATION@@

func defaultConfig() gateway.TCPConfig { return gateway.DefaultTCPConfig() }
func validateConfig(config gateway.TCPConfig) error { return gateway.ValidateTCPConfig(config) }

type Authenticator interface { Authenticate(context.Context,string,net.Addr)(gateway.Principal,error) }
// configFromViper reads player_access.tcp.* through the declaration above
// (maintainer decision A4 ①): a value of the wrong type — "enabled: on",
// "max_payload_bytes: 8k", a duration without a unit — is refused by key
// instead of being read as false / 0 (the default) / nanoseconds, every bad
// key at once, and the App checks the same declaration before any Mod Init.
// An unset key keeps its declared default (TestDeclaredDefaultsAreDefaultConfig);
// validateConfig then applies the bounds, the same ones NewServer applies to
// a Config built in code.
func configFromViper(cfg *viper.Viper) (gateway.TCPConfig, error) {
	if cfg == nil { return defaultConfig(), errors.New("player tcp: config is nil") }
	var settings tcpConfig
	if err := app.LoadConfig(cfg, &settings); err != nil { return gateway.TCPConfig{}, fmt.Errorf("player tcp: %%w", err) }
	tcp := settings.TCP
	result := gateway.TCPConfig{
		Enabled: tcp.Enabled, Addr: tcp.Addr, MaxConnections: tcp.MaxConnections,
 HeartbeatEnabled:tcp.HeartbeatEnabled,RequestRate:tcp.RequestRate,RequestBurst:tcp.RequestBurst,
		MaxConnectionsPerIP: tcp.MaxConnectionsPerIP, MaxHandshakes: tcp.MaxHandshakes,
		MaxHandshakeBytes: tcp.MaxHandshakeBytes, MaxPayloadBytes: tcp.MaxPayloadBytes,
		HandshakeTimeout: tcp.HandshakeTimeout, IdleTimeout: tcp.IdleTimeout, WriteTimeout: tcp.WriteTimeout,
		ShutdownTimeout: tcp.ShutdownTimeout, DispatchTimeout: tcp.DispatchTimeout, LoginTimeout: tcp.LoginTimeout,
	}
	// The dispatch budget follows the Nest request budget unless it is set on
	// its own: a request is at least one Nest call, and a transport deadline
	// shorter than that call's own would cut it off for no stated reason.
	if result.DispatchTimeout == 0 { result.DispatchTimeout = settings.Nest.RequestTimeout }
	if result.DispatchTimeout == 0 { result.DispatchTimeout = defaultDispatchTimeout }
	if result.LoginTimeout == 0 { result.LoginTimeout = min(defaultLoginTimeout, result.DispatchTimeout) }
	if err := validateConfig(result); err != nil { return gateway.TCPConfig{}, err }
	return result, nil
}

// ConfigSchema implements app.ModConfigSchema: the App checks these keys
// before any Mod Init, and --print-config prints them.
func (*Mod) ConfigSchema() app.ConfigSchema { return app.SchemaOf(tcpConfig{}) }

// RegistryBound is implemented by an Authenticator that needs a capability
// this process publishes — an account client to validate session tickets, a
// key store the verifier reads. Authenticators are built in Init from
// configuration alone; the Mod calls BindRegistry in Provide, after the
// process's Mods have published their capabilities and before the listener
// starts. An error stops the process: a listener whose authenticator cannot
// reach its verifier must not accept connections.
type RegistryBound interface {
	BindRegistry(registry *app.Registry) error
}

type AuthenticatorFunc func(context.Context, string, net.Addr) (gateway.Principal, error)

func (fn AuthenticatorFunc) Authenticate(ctx context.Context, token string, remote net.Addr) (gateway.Principal, error) {
	return fn(ctx, token, remote)
}

type Mod struct {
	config gateway.TCPConfig
	authenticator Authenticator
	runtime *accessplayer.Runtime
	server *gateway.TCPServer
	transportRuntime *Runtime
}

func NewMod() *Mod { return &Mod{} }
func (*Mod) Name() app.ModName { return Name }
func (*Mod) DependsOn() []app.ModName { return []app.ModName{accessplayer.Name} }

func (mod *Mod) Init(cfg *viper.Viper) error {
	parsed, err := configFromViper(cfg)
	if err != nil { return err }
	mod.config = parsed
	if mod.authenticator == nil {
		mod.authenticator, err = newApplicationAuthenticator(cfg)
		if err != nil { return fmt.Errorf("player tcp: initialize authenticator: %%w", err) }
	}
	if mod.authenticator == nil { return errors.New("player tcp: authenticator is nil") }
	return nil
}

func (mod *Mod) Provide(registry *app.Registry) error {
	if registry == nil { return errors.New("player tcp: app registry is nil") }
	runtime, ok := app.Lookup[*accessplayer.Runtime](registry, accessplayer.Name)
	if !ok || runtime == nil || runtime.Protocols == nil { return errors.New("player tcp: player access runtime is unavailable") }
	if bound, ok := mod.authenticator.(RegistryBound); ok {
		if err := bound.BindRegistry(registry); err != nil { return fmt.Errorf("player tcp: bind authenticator: %%w", err) }
	}
	mod.runtime = runtime
	mod.transportRuntime = NewRuntime(runtime.Protocols, mod.config.LoginTimeout)
	return registry.Register(Name, mod.transportRuntime)
}

func (mod *Mod) Start() error {
	if !mod.config.Enabled {
		slog.Info("player tcp listener disabled")
		return nil
	}
	server, err := NewServer(mod.config, mod.runtime, mod.authenticator)
	if err != nil { return err }
	// Before Start: a close cannot happen until the server accepts, and the
	// link has to be in place by then.
	if err := server.ConnectRuntime(mod.transportRuntime.TCPRuntime); err != nil { return err }
	if err := server.Start(); err != nil { return err }
	mod.server = server
	return nil
}

func (mod *Mod) Stop() {
	ctx, cancel := context.WithTimeout(context.Background(), mod.config.ShutdownTimeout)
	defer cancel()
	_ = mod.StopWithContext(ctx)
}

// StopBudget declares player_access.tcp.shutdown_timeout to the App
// (app.ModStopBudgetProvider): within shutdown.total_timeout the App grants
// the listener this long to drain its connections, and the generated
// total_timeout counts it (RR-20260927-05). Undeclared, the Mod only got the
// App's fixed 3s floor — below its own 10s, and no slack over the 3s a
// request already in flight may take (nest.request_timeout). 0 before Init,
// i.e. not declared.
func (mod *Mod) StopBudget() time.Duration { return mod.config.ShutdownTimeout }

// StopWithContext stops the listener and waits, within ctx, for every
// connection goroutine and then the session-close dispatcher to finish.
// A ctx that ends first returns its error and keeps the server: a handler or
// authenticator that ignores its context is still running, so a later call
// with a fresh ctx waits for it again instead of reporting a drain that did
// not happen (RR-20261005-NC-83). Session-close subscribers are waited for
// within the same ctx.
func (mod *Mod) StopWithContext(ctx context.Context) error {
	if ctx == nil { ctx = context.Background() }
	if mod.server != nil {
		if err := mod.server.Stop(ctx); err != nil { return err }
		mod.server = nil
	}
	// After the server: the closes it produced on the way down are still
	// worth delivering.
	if mod.transportRuntime != nil { return mod.transportRuntime.StopNotifications(ctx) }
	return nil
}


// Runtime 是业务接线 capability：把 ProtocolRegistry 的编码器接到唯一 TCP runtime。
// 连接表、通知、监听和收发都由 gateway 持有，生成物不复制运行状态机。
type Runtime struct { gateway.PlayerRuntime; TCPRuntime *gateway.TCPRuntime }
func NewRuntime(protocols *player_agent.ProtocolRegistry, loginTimeout time.Duration) *Runtime {
 var encode gateway.TCPEncoder
 if protocols != nil { encode = protocols.Encode }
 native := gateway.NewTCPRuntime(encode,loginTimeout)
 return &Runtime{PlayerRuntime:native,TCPRuntime:native}
}

// NewServer 是本地 Game 的协议适配；独立 Gate 接入同一个 gateway.NewTCPServer。
func NewServer(config gateway.TCPConfig,runtime *accessplayer.Runtime,authenticator Authenticator)(*gateway.TCPServer,error){
 if runtime == nil || runtime.Protocols == nil {return nil,errors.New("player tcp: player access runtime is nil")}
 return gateway.NewTCPServer(config,func(ctx context.Context,session gateway.Session,msgID,sequence uint32,kind wire.PayloadKind,payload []byte)(any,error){
  response,err := runtime.Protocols.DispatchPayload(ctx,session,msgID,sequence,kind,payload)
  // Notify 的 nil 响应必须保持 nil interface，否则 TCP 会把 typed nil 当成待写响应。
  if response == nil { return nil,err }; return response,err
 },authenticator)
}

// NewIngressMod 是部署启动 option：Game 只开放内部接入，不同时开启本地 TCP。
// dispatcher 仍调用当前 ProtocolRegistry → 生成 Sender → Nest；接线不复制网络循环。
func NewIngressMod(options gatewiring.Options) *IngressMod { return &IngressMod{options:options} }
type IngressMod struct { options gatewiring.Options; inner *gatewiring.GameIngressMod }
func (*IngressMod) Name() app.ModName { return Name }
func (mod *IngressMod) DependsOn() []app.ModName {
 names:=append([]app.ModName{accessplayer.Name,"nats"},mod.options.DependsOn...)
 if mod.options.Authenticator==nil { names=append(names,"service.account") };if mod.options.RegisterDiscovery { names=append(names,"etcd") };return names
}
func (mod *IngressMod) Init(cfg *viper.Viper) error {
 parsed,err:=configFromViper(cfg);if err!=nil{return err}
 if parsed.Enabled { return errors.New("game ingress: embedded TCP listener must be disabled") }
 return mod.options.Config.Validate()
}
func (mod *IngressMod) Provide(registry *app.Registry) error {
 if _,exists:=registry.Get(Name);exists{return errors.New("game ingress: player TCP capability already provided")}
 runtime,ok:=app.Lookup[*accessplayer.Runtime](registry,accessplayer.Name)
 if !ok||runtime==nil||runtime.Protocols==nil{return errors.New("game ingress: player access runtime unavailable")}
 dispatch:=func(ctx context.Context,session gateway.Session,id,seq uint32,kind wire.PayloadKind,payload []byte)(any,error){
  response,err:=runtime.Protocols.DispatchPayload(ctx,session,id,seq,kind,payload)
  if response==nil{return nil,err};return response,err
 }
 mod.inner=gatewiring.NewGameIngressMod(dispatch,runtime.Protocols.Encode,mod.options)
 if err:=mod.inner.Provide(registry);err!=nil{return err}
 ingress,ok:=app.Lookup[*gateway.GameIngress](registry,gatewiring.GameIngressName)
 if !ok{return errors.New("game ingress: capability missing")}
 return registry.Register(Name,&Runtime{PlayerRuntime:ingress})
}
func (mod *IngressMod) Start()error { if mod.inner==nil{return errors.New("game ingress: not provided")};return mod.inner.Start() }
func (mod *IngressMod) Stop(){if mod.inner!=nil{mod.inner.Stop()}}
func (mod *IngressMod) StopBudget()time.Duration {return max(10*time.Second,mod.options.Config.RequestTimeout+mod.options.Config.Outbound.MaxAge)}
func (mod *IngressMod) StopWithContext(ctx context.Context)error{if mod.inner==nil{return nil};return mod.inner.StopWithContext(ctx)}
func (*IngressMod) ConfigSchema()app.ConfigSchema{return app.SchemaOf(tcpConfig{})}
var _ app.Mod = (*IngressMod)(nil)

var _ app.Mod = (*Mod)(nil)
var _ app.ModStopperWithContext = (*Mod)(nil)
var _ app.ModStopBudgetProvider = (*Mod)(nil)
`, manifest.Project.Module+"/internal/access/player", manifest.Project.Module+protocol.PlayerAgentImportSuffix)
}

func renderPlayerTCPServerTests(manifest Manifest) string {
	return fmt.Sprintf(`// Code generated by roost-codegen. DO NOT EDIT.
package tcp
import (
 "bytes"
 "context"
 "errors"
 "log/slog"
 "net"
 "strings"
 "testing"
 "time"
 "github.com/spf13/viper"
 "github.com/tjbdwanghaibo/roost-core/client/wire"
 "github.com/tjbdwanghaibo/roost-core/infra/network/gateway"
 accessplayer %q
 %q
)
func TestHandlerPanicHasErrorLevelStack(t *testing.T){
 var logs bytes.Buffer;old:=slog.Default();slog.SetDefault(slog.New(slog.NewTextHandler(&logs,&slog.HandlerOptions{Level:slog.LevelInfo})));defer slog.SetDefault(old)
 wrapped:=player_agent.RecoverMiddleware(func(*player_agent.Context,any)(any,error){panic("b6 handler failure")})
 _,err:=wrapped(&player_agent.Context{PlayerID:7,MsgID:11,Seq:12},nil);if err==nil{t.Fatal("panic not recovered")}
 got:=logs.String();if !strings.Contains(got,"level=ERROR") || !strings.Contains(got,"stack=") || !strings.Contains(got,"TestHandlerPanicHasErrorLevelStack") {t.Fatalf("panic lacks visible stack: %%s",got)}
}

// A4 ①: the declared defaults are defaultConfig(): an empty config reads as
// the Config NewServer is given in code, so the default the generator and
// --print-config show is the one that runs.
func TestDeclaredDefaultsAreDefaultConfig(t *testing.T) {
	config, err := configFromViper(viper.New())
	if err != nil { t.Fatal(err) }
	if config != defaultConfig() { t.Fatalf("declared defaults %%+v, defaultConfig() %%+v", config, defaultConfig()) }
}

// RR-20260926-36: the dispatch budget follows nest.request_timeout unless it
// is set on its own, and a login budget larger than the dispatch it runs in is
// refused rather than silently cut short.
func TestDispatchBudgetFollowsTheNestRequestTimeout(t *testing.T) {
	cfg := viper.New()
	cfg.Set("nest.request_timeout", "7s")
	config, err := configFromViper(cfg)
	if err != nil { t.Fatal(err) }
	if config.DispatchTimeout != 7*time.Second || config.LoginTimeout != defaultLoginTimeout {
		t.Fatalf("dispatch=%%v login=%%v, want 7s and %%v", config.DispatchTimeout, config.LoginTimeout, defaultLoginTimeout)
	}
	cfg.Set("nest.request_timeout", "1s")
	if config, err = configFromViper(cfg); err != nil || config.DispatchTimeout != time.Second || config.LoginTimeout != time.Second {
		t.Fatalf("dispatch=%%v login=%%v err=%%v, want both 1s", config.DispatchTimeout, config.LoginTimeout, err)
	}
	cfg.Set("player_access.tcp.dispatch_timeout", "3s")
	cfg.Set("player_access.tcp.login_timeout", "5s")
	if _, err := configFromViper(cfg); err == nil {
		t.Fatal("a login budget larger than the dispatch budget was accepted")
	}
}

// A4: player_access.tcp.* is read strictly. A value of the wrong type used to
// be read as false / 0 (the default) / nanoseconds and pass every check; Init
// now refuses it and names the key, and a valid value written as a string (an
// environment override) still reads.
func TestConfigValuesOfTheWrongTypeAreRefusedByName(t *testing.T) {
	newMod := func() *Mod {
		return &Mod{authenticator: AuthenticatorFunc(func(context.Context, string, net.Addr) (gateway.Principal, error) {
			return gateway.Principal{}, nil
		})}
	}
	yamlConfig := func(t *testing.T, text string) *viper.Viper {
		t.Helper()
		cfg := viper.New()
		cfg.SetConfigType("yaml")
		if err := cfg.ReadConfig(strings.NewReader(text)); err != nil { t.Fatal(err) }
		return cfg
	}
	for _, tc := range []struct{ name, yaml, key string }{
		{"enabled_on", "player_access:\n  tcp:\n    enabled: on\n", "player_access.tcp.enabled"},
		{"payload_8k", "player_access:\n  tcp:\n    max_payload_bytes: 8k\n", "player_access.tcp.max_payload_bytes"},
		{"handshake_bytes_negative", "player_access:\n  tcp:\n    max_handshake_bytes: -1\n", "player_access.tcp.max_handshake_bytes"},
		{"connections_fraction", "player_access:\n  tcp:\n    max_connections: 1.5\n", "player_access.tcp.max_connections"},
		{"idle_unitless", "player_access:\n  tcp:\n    idle_timeout: 90\n", "player_access.tcp.idle_timeout"},
		{"handshake_word", "player_access:\n  tcp:\n    handshake_timeout: soon\n", "player_access.tcp.handshake_timeout"},
		{"nest_request_unitless", "nest:\n  request_timeout: 7\n", "nest.request_timeout"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			mod := newMod()
			err := mod.Init(yamlConfig(t, tc.yaml))
			if err == nil || !strings.Contains(err.Error(), tc.key) {
				t.Errorf("%%s: Init returned %%v, want a refusal naming %%s (parsed config: %%+v)", strings.TrimSpace(tc.yaml), err, tc.key, mod.config)
			}
		})
	}
	mod := newMod()
	valid := "player_access:\n  tcp:\n    enabled: \"true\"\n    max_payload_bytes: \"65536\"\n    max_handshake_bytes: 4096\n    idle_timeout: 30s\n"
	if err := mod.Init(yamlConfig(t, valid)); err != nil { t.Fatalf("valid config refused: %%v", err) }
	if !mod.config.Enabled || mod.config.MaxPayloadBytes != 65536 || mod.config.MaxHandshakeBytes != 4096 || mod.config.IdleTimeout != 30*time.Second {
		t.Fatalf("valid config read as %%+v", mod.config)
	}
}

// A9 (closing batch 2): a limit outside its bounds is refused by its key,
// and a limit bounded by another names that one too, so the operator knows
// which line to change. Before, every limit shared one sentence ("addr,
// limits and timeouts are outside safe bounds", and "timeouts exceed safe
// bounds" for the upper bounds of the timeouts).
func TestAnOutOfBoundsSettingIsRefusedByName(t *testing.T) {
	const key = "player_access.tcp."
	for _, tc := range []struct {
		name string
		set map[string]any
		want []string
	}{
		{"addr_without_port", map[string]any{"addr": "localhost"}, []string{key + "addr"}},
		{"connections_above_the_hard_cap", map[string]any{"max_connections": 2000000}, []string{key + "max_connections = 2000000"}},
		{"connections_negative", map[string]any{"max_connections": -1}, []string{key + "max_connections = -1"}},
		{"per_ip_above_connections", map[string]any{"max_connections": 2000, "max_connections_per_ip": 3000}, []string{key + "max_connections_per_ip = 3000", key + "max_connections = 2000"}},
		{"handshakes_above_connections", map[string]any{"max_connections": 1000, "max_handshakes": 2000}, []string{key + "max_handshakes = 2000", key + "max_connections = 1000"}},
		{"handshake_bytes_above_64k", map[string]any{"max_handshake_bytes": 100000}, []string{key + "max_handshake_bytes = 100000"}},
		{"handshake_timeout_above_a_minute", map[string]any{"handshake_timeout": "2m"}, []string{key + "handshake_timeout = 2m0s"}},
		{"idle_timeout_negative", map[string]any{"idle_timeout": "-1s"}, []string{key + "idle_timeout = -1s"}},
		{"dispatch_timeout_above_five_minutes", map[string]any{"dispatch_timeout": "10m"}, []string{key + "dispatch_timeout = 10m0s"}},
		{"login_above_dispatch", map[string]any{"dispatch_timeout": "1s", "login_timeout": "2s"}, []string{key + "login_timeout = 2s", key + "dispatch_timeout = 1s"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			cfg := viper.New()
			for name, value := range tc.set { cfg.Set(key+name, value) }
			_, err := configFromViper(cfg)
			if err == nil { t.Fatalf("%%v accepted", tc.set) }
			for _, want := range tc.want {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("%%v refused with %%q, want it to name %%q", tc.set, err, want)
				}
			}
			if strings.Contains(err.Error(), "safe bounds") {
				t.Errorf("%%v refused with the unnamed sentence: %%q", tc.set, err)
			}
		})
	}
	if _, err := configFromViper(viper.New()); err != nil { t.Fatalf("the defaults are refused: %%v", err) }
}

// RR-20260927-05: the Mod declares player_access.tcp.shutdown_timeout as its
// stop budget, so the App grants the listener that long inside
// shutdown.total_timeout instead of the 3s floor of an undeclared Mod.
func TestTheModDeclaresItsShutdownTimeoutAsTheStopBudget(t *testing.T) {
	mod := NewMod()
	provider, ok := any(mod).(interface{ StopBudget() time.Duration })
	if !ok { t.Fatal("the player tcp Mod declares no stop budget: the App gives it only the 3s floor of an undeclared Mod") }
	if got := provider.StopBudget(); got != 0 { t.Fatalf("stop budget before Init = %%v, want 0 (not declared)", got) }
	mod.authenticator = AuthenticatorFunc(func(context.Context, string, net.Addr) (gateway.Principal, error) { return gateway.Principal{}, nil })
	for _, tc := range []struct{ configured string; want time.Duration }{{"", 10 * time.Second}, {"7s", 7 * time.Second}} {
		cfg := viper.New()
		if tc.configured != "" { cfg.Set("player_access.tcp.shutdown_timeout", tc.configured) }
		if err := mod.Init(cfg); err != nil { t.Fatal(err) }
		if got := provider.StopBudget(); got != tc.want { t.Errorf("shutdown_timeout %%q: stop budget = %%v, want %%v", tc.configured, got, tc.want) }
	}
}

// RR-20261005-NC-83: the Mod keeps the server after a Stop that ran out of
// time, so the retry has something to wait for.
func TestAModStopRetryKeepsTheServerUntilItDrains(t *testing.T) {
	server, release, _, returned := stalledAuthServer(t)
	runtime := NewRuntime(nil,defaultLoginTimeout)
	mod := &Mod{config: defaultConfig(), server: server, transportRuntime: runtime}
	ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
	first := mod.StopWithContext(ctx)
	cancel()
	if !errors.Is(first, context.DeadlineExceeded) || mod.server != server {
		t.Fatalf("first StopWithContext = %%v, server kept = %%v", first, mod.server == server)
	}
	close(release)
	if err := mod.StopWithContext(context.Background()); err != nil {
		t.Fatalf("retry StopWithContext = %%v", err)
	}
	select {
	case <-returned:
	default:
		t.Fatal("retry StopWithContext reported success while the authenticator was still running")
	}
	if mod.server != nil {
		t.Fatal("the drained server is still held")
	}
}
// stalledAuthServer 使用正式 NewServer，认证回调故意忽略 ctx，以验证 Mod 在超时后保留所有权。
func stalledAuthServer(t *testing.T)(*gateway.TCPServer,chan struct{},<-chan struct{},<-chan struct{}){
 t.Helper();config:=defaultConfig();config.Addr="127.0.0.1:0";config.HandshakeTimeout=5*time.Second
 release,entered,returned:=make(chan struct{}),make(chan struct{},1),make(chan struct{})
 server,err:=NewServer(config,&accessplayer.Runtime{Protocols:player_agent.NewProtocolRegistry()},AuthenticatorFunc(func(context.Context,string,net.Addr)(gateway.Principal,error){
  entered<-struct{}{};<-release;time.Sleep(100*time.Millisecond);close(returned);return gateway.Principal{},gateway.ErrUnauthenticated
 }));if err!=nil{t.Fatal(err)}
 if err:=server.Start();err!=nil{t.Fatal(err)}
 conn,err:=net.Dial("tcp",server.Addr().String());if err!=nil{t.Fatal(err)}
 t.Cleanup(func(){_ = conn.Close()})
 if err:=wire.Write(conn,[]*wire.Packet{{MsgID:0,Seq:1,Payload:[]byte("token")}},int(config.MaxHandshakeBytes));err!=nil{t.Fatal(err)}
 select {case <-entered:case <-time.After(2*time.Second):t.Fatal("handshake did not reach authenticator")}
 return server,release,entered,returned
}

// 真实 RS v2 客户端夹具供 SDK、Sync/Lockstep 的生成消费者测试复用。
func dialAuthenticated(t *testing.T,server *gateway.TCPServer,token string)net.Conn{
 t.Helper();conn,err:=net.Dial("tcp",server.Addr().String());if err!=nil{t.Fatal(err)}
 t.Cleanup(func(){_ = conn.Close()})
 if err:=wire.Write(conn,[]*wire.Packet{{MsgID:0,Seq:1,Payload:[]byte(token)}},wire.DefaultMaxPayload);err!=nil{t.Fatal(err)}
 _ = conn.SetReadDeadline(time.Now().Add(2*time.Second))
 ack,err:=wire.Read(conn,wire.DefaultMaxPayload);if err!=nil{t.Fatal(err)}
 if ack.MsgID!=0 || ack.Seq!=1 || len(ack.Payload)!=0{t.Fatalf("unexpected auth ACK: %%+v",ack)}
 return conn
}
`, manifest.Project.Module+"/internal/access/player", manifest.Project.Module+protocol.PlayerAgentImportSuffix)
}
