package roost

// RR-20261005-NC-74（N07 第二批移交）：`roost generate` / `roost project sync` 先快照工程里的应用
// 输入，提交前再核对，有变化就拒绝（“project inputs changed while code generation was running”）。
// 快照与复制共用的跳过名单（skippedProjectDirectory）只有 .git / bin / dist / log / .testcache /
// .roost-*，而工程自己运行时会往工程目录里写：`make dev-run`（deploy/dev/run.sh）把日志写在
// `.dev/*.log`，DataEngine 的默认 WAL 目录是 `data/wal/dataengine`（生成的 config.<svc>.yaml）。
// 于是 dev-run 期间每次 generate / sync 都失败，必须先停服务；WAL 还会被整份复制进暂存树。
// 承诺：运行期输出不算应用输入、不进暂存树、也不会被提交计划当成待删的生成物；真正的应用
// 输入在生成期间被改仍然拒绝提交。不能按目录名跳过 data（configs/data 是生成器的输出）。

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// runtimeWrites stands in for a running dev-run: it appends to the dev log and
// to a WAL segment in the project, as the processes do while generation runs.
func runtimeWrites(t *testing.T, root string) {
	t.Helper()
	for _, rel := range []string{".dev/game.log", "data/wal/dataengine/000001.wal"} {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := f.WriteString("tick\n"); err != nil {
			t.Fatal(err)
		}
		if err := f.Close(); err != nil {
			t.Fatal(err)
		}
	}
}

func seedRuntimeOutput(t *testing.T, root string) {
	t.Helper()
	// A log line that quotes a generated header must not make the file look
	// like a codegen-owned output the commit plan may delete.
	writeProjectFile(t, root, ".dev/game.log", "starting\n")
	writeProjectFile(t, root, ".dev/quoted.log", "// Code generated by roost-codegen. DO NOT EDIT. (quoted in a log)\n")
	writeProjectFile(t, root, "data/wal/dataengine/000001.wal", "segment\n")
}

func assertRuntimeOutputKept(t *testing.T, root string) {
	t.Helper()
	for _, rel := range []string{".dev/game.log", ".dev/quoted.log", "data/wal/dataengine/000001.wal"} {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(rel))); err != nil {
			t.Errorf("runtime output %s did not survive: %v", rel, err)
		}
	}
}

// fakeTidyGo puts a `go` on PATH whose `go mod tidy` runs script first, so
// GenerateTransactional's only external step doubles as the concurrent writer.
func fakeTidyGo(t *testing.T, script string) {
	t.Helper()
	bin := filepath.Join(t.TempDir(), "bin")
	if err := os.Mkdir(bin, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(bin, "go"), []byte("#!/bin/sh\n"+script+"\nexit 0\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", bin+string(os.PathListSeparator)+os.Getenv("PATH"))
}

func TestGenerateAndSyncIgnoreTheProjectsRuntimeOutput(t *testing.T) {
	if _, err := os.Stat("/bin/sh"); err != nil {
		t.Skip("the stand-in go is a POSIX shell script")
	}
	t.Run("generate while dev-run writes logs and WAL", func(t *testing.T) {
		root := copyOfNewProject(t, "configdata")
		seedRuntimeOutput(t, root)
		fakeTidyGo(t, "printf 'tick\\n' >> '"+filepath.Join(root, ".dev", "game.log")+"'; printf 'tick\\n' >> '"+filepath.Join(root, "data", "wal", "dataengine", "000001.wal")+"'")
		if err := GenerateTransactional(context.Background(), root, GenerateOptions{Stdout: io.Discard}, io.Discard); err != nil {
			t.Fatalf("generate while the project runs: %v", err)
		}
		assertRuntimeOutputKept(t, root)
	})
	t.Run("sync while dev-run writes logs and WAL", func(t *testing.T) {
		root := copyOfNewProject(t, "configdata")
		seedRuntimeOutput(t, root)
		syncProjectBeforeCommit = func() { runtimeWrites(t, root) }
		t.Cleanup(func() { syncProjectBeforeCommit = nil })
		if _, err := SyncProject(root); err != nil {
			t.Fatalf("sync while the project runs: %v", err)
		}
		assertRuntimeOutputKept(t, root)
	})
	t.Run("an application input edited during generate is still refused", func(t *testing.T) {
		root := copyOfNewProject(t, "configdata")
		rel := "configs/service/config.game.yaml"
		fakeTidyGo(t, "printf '# developer edit\\n' >> '"+filepath.Join(root, filepath.FromSlash(rel))+"'")
		err := GenerateTransactional(context.Background(), root, GenerateOptions{Stdout: io.Discard}, io.Discard)
		if err == nil || !strings.Contains(err.Error(), rel) {
			t.Fatalf("generate with %s edited concurrently = %v, want the inputs-changed refusal", rel, err)
		}
	})
}
