// Code generated by tool/nest. DO NOT EDIT.

package registry

import (
	gamehandler "example.com/planet/game/handler"
)

// RegisterNestHandlers registers every generated nest handler. It runs once
// via RegisterAll, which owns the sync.Once for all static registration.
//
//roost:register phase=nest
func RegisterNestHandlers() {
	gamehandler.RegisterActivitySettledNestHandlers()
	gamehandler.RegisterAddExpNestHandlers()
	gamehandler.RegisterAddItemNestHandlers()
	gamehandler.RegisterArmActivityNestHandlers()
	gamehandler.RegisterClaimDungeonNestHandlers()
	gamehandler.RegisterClaimMailRewardNestHandlers()
	gamehandler.RegisterEnterSceneNestHandlers()
	gamehandler.RegisterEquipItemNestHandlers()
	gamehandler.RegisterFoundGuildNestHandlers()
	gamehandler.RegisterGiftDebitNestHandlers()
	gamehandler.RegisterGiftRefundNestHandlers()
	gamehandler.RegisterGrantPurchaseNestHandlers()
	gamehandler.RegisterGuildInfoNestHandlers()
	gamehandler.RegisterJoinGuildNestHandlers()
	gamehandler.RegisterMovePlayerNestHandlers()
	gamehandler.RegisterPlayerGuildNestHandlers()
	gamehandler.RegisterPlayerLevelNestHandlers()
	gamehandler.RegisterPlayerPositionNestHandlers()
	gamehandler.RegisterRecordEnterNestHandlers()
	gamehandler.RegisterRecordMatchNestHandlers()
	gamehandler.RegisterSettleActivityNestHandlers()
	gamehandler.RegisterStartGiftNestHandlers()
	gamehandler.RegisterTickWorldTimersNestHandlers()
	gamehandler.RegisterWorldStatsNestHandlers()
}
