package webroute

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateDir scans dir recursively and generates one route registration file
// for each package containing annotated handlers.
func GenerateDir(dir string, force bool) ([]string, error) {
	type packageRoutes struct {
		pkg    string
		routes []Route
	}
	packages := make(map[string]*packageRoutes)
	err := filepath.Walk(dir, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if info.IsDir() {
			base := info.Name()
			if base == "vendor" || base == "testdata" || strings.HasPrefix(base, ".") {
				return filepath.SkipDir
			}
			return nil
		}
		name := info.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == generatedFileName || strings.HasSuffix(name, generatedFileSuffix) {
			return nil
		}
		source, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		routes, pkg, err := ParseFile(path, source)
		if err != nil {
			return err
		}
		if len(routes) == 0 {
			return nil
		}
		key := filepath.Dir(path)
		item := packages[key]
		if item == nil {
			item = &packageRoutes{pkg: pkg}
			packages[key] = item
		}
		if item.pkg != pkg {
			return fmt.Errorf("webroute: mixed packages in %s", key)
		}
		item.routes = append(item.routes, routes...)
		return nil
	})
	if err != nil {
		return nil, err
	}

	dirs := make([]string, 0, len(packages))
	for dir := range packages {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)
	changed := make([]string, 0, len(dirs))
	for _, packageDir := range dirs {
		item := packages[packageDir]
		sort.Slice(item.routes, func(i, j int) bool {
			return item.routes[i].Handler < item.routes[j].Handler
		})
		if err := validateRoutes(item.routes); err != nil {
			return nil, fmt.Errorf("webroute: %s: %w", packageDir, err)
		}
		output, err := renderRoutes(item.pkg, item.routes)
		if err != nil {
			return nil, err
		}
		outFile := filepath.Join(packageDir, generatedFileName)
		current, readErr := os.ReadFile(outFile)
		if !force && readErr == nil && bytes.Equal(current, output) {
			continue
		}
		if err := os.WriteFile(outFile, output, 0644); err != nil {
			return nil, err
		}
		changed = append(changed, outFile)
	}
	return changed, nil
}

func validateRoutes(routes []Route) error {
	seen := make(map[string]struct{}, len(routes))
	for _, route := range routes {
		key := route.Method + " " + route.Path
		if _, exists := seen[key]; exists {
			return fmt.Errorf("duplicate route %s", key)
		}
		seen[key] = struct{}{}
	}
	return nil
}

func renderRoutes(pkg string, routes []Route) ([]byte, error) {
	var source bytes.Buffer
	fmt.Fprintf(&source, "// Code generated by roost webroute. DO NOT EDIT.\n\npackage %s\n\n", pkg)
	source.WriteString("import (\n")
	source.WriteString("\t\"net/http\"\n\n")
	source.WriteString("\t\"github.com/tjbdwanghaibo/roost-core/webroute\"\n")
	source.WriteString(")\n\n")
	source.WriteString("func (svc *Service) RegisterRoutes(reg webroute.Registerer) error {\n")
	for _, route := range routes {
		fmt.Fprintf(&source, "\tif err := reg.Register(%q, %q, func(w http.ResponseWriter, r *http.Request) {\n", route.Method, route.Path)
		if route.BodyMode == bodyJSON {
			fmt.Fprintf(&source, "\t\tvar request %s\n", route.RequestType)
			source.WriteString("\t\tif !webroute.DecodeJSON(w, r, &request) {\n\t\t\treturn\n\t\t}\n")
		} else {
			source.WriteString("\t\trequest, ok := webroute.ReadRaw(w, r)\n\t\tif !ok {\n\t\t\treturn\n\t\t}\n")
		}
		fmt.Fprintf(&source, "\t\tresponse, err := %s(r.Context(), svc, request)\n", route.Handler)
		source.WriteString("\t\twebroute.WriteResult(w, http.StatusOK, response, err)\n")
		source.WriteString("\t}); err != nil {\n\t\treturn err\n\t}\n")
	}
	source.WriteString("\treturn nil\n}\n")
	source.WriteString("\nfunc RegisterRoutes(reg webroute.Registerer, svc *Service) error {\n")
	source.WriteString("\treturn svc.RegisterRoutes(reg)\n}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated route source: %w", err)
	}
	return formatted, nil
}
