package dao

var nestedTemplate = `// Code generated by tool/dao. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"

	"github.com/tjbdwanghaibo/roost-core/dataengine"
	"github.com/tjbdwanghaibo/roost-core/nest"
{{- if hasMaps .Nested.Fields}}
	fmap "github.com/tjbdwanghaibo/roost-core/safemap"
{{- end}}
	"go.mongodb.org/mongo-driver/v2/bson"
)

// {{.Nested.Name}} is a nested struct with dirty propagation.
//
// The hook is excluded from every codec: it is runtime wiring, not state, and
// an exported embedded struct with no exported fields would otherwise be
// written as an empty "dirtyhook" sub-document (U-0224).
type {{.Nested.Name}} struct {
	dataengine.DirtyHook ` + "`" + `bson:"-" json:"-"` + "`" + `
	// dirtyOwner is the one place this value belongs to. Unexported, so no
	// codec sees it, and it is runtime wiring for the same reason the hook is.
	dirtyOwner daoDirtyOwner
{{- range .Nested.Fields}}
	{{fieldVar .Name}} {{fieldType .}}
{{- end}}
}

// bindDirty / unbindDirty are how a parent takes and releases this value.
//
// The parent is identified, not just remembered: a value that already belongs
// somewhere else is refused rather than silently re-pointed, because the
// notification is a single slot and re-pointing it leaves the first place
// stale on disk while memory shows both equal (RR-20260919-02). unbindDirty
// releases only its own binding, so a stale release from a place this value
// has already left cannot silence the place it is in now.
func (s *{{.Nested.Name}}) bindDirty(owner daoDirtyOwner, notify func()) {
	if s == nil {
		return
	}
	daoBindDirty(&s.DirtyHook, &s.dirtyOwner, owner, "{{.Nested.Name}}", notify)
}

func (s *{{.Nested.Name}}) unbindDirty(owner daoDirtyOwner) {
	if s == nil {
		return
	}
	daoUnbindDirty(&s.DirtyHook, &s.dirtyOwner, owner)
}

// --- wire form (persistence, rollback capture, sync) ---
//
// The fields are unexported so every mutation goes through the setters below
// — that is what makes dirty tracking and undo impossible to bypass — and the
// reflection-based codec cannot see unexported fields. {{.Nested.Name}} therefore
// has a WIRE FORM, {{lower1 .Nested.Name}}BSONDoc, with exported fields: the
// parent DAO places that into its own document and reflection encodes it
// inline, with no per-value Marshaler round trip (U-0224 and its follow-up:
// the bson.Marshaler route cost about four allocations per nested value).
// MarshalBSON / UnmarshalBSON are kept for a {{.Nested.Name}} encoded on its own.
type {{lower1 .Nested.Name}}BSONDoc struct {
{{- range .Nested.Fields}}
	{{.Name}} {{wireType .}} ` + "`" + `bson:"{{bsonKey .Name}}"` + "`" + `
{{- end}}
}

// bsonDoc is the value receiver on purpose: containers hold {{.Nested.Name}} values
// as well as pointers, and a method expression {{.Nested.Name}}.bsonDoc maps over both.
func (s {{.Nested.Name}}) bsonDoc() {{lower1 .Nested.Name}}BSONDoc {
	return {{lower1 .Nested.Name}}BSONDoc{
{{- range .Nested.Fields}}
{{- if eq .Kind 2}}
		{{.Name}}: {{toWire . (printf "s.%sRawMap()" (fieldVar .Name))}},
{{- else}}
		{{.Name}}: {{toWire . (printf "s.%s" (fieldVar .Name))}},
{{- end}}
{{- end}}
	}
}

func (s *{{.Nested.Name}}) setBSONDoc(doc {{lower1 .Nested.Name}}BSONDoc) {
{{- range .Nested.Fields}}
{{- if eq .Kind 2}}
	s.set{{.Name}}RawMap({{fromWire . (printf "doc.%s" .Name)}})
{{- else}}
	s.{{fieldVar .Name}} = {{fromWire . (printf "doc.%s" .Name)}}
{{- if hasHook .}}
	s.bind{{.Name}}()
{{- end}}
{{- end}}
{{- end}}
}

func {{lower1 .Nested.Name}}FromBSONDoc(doc {{lower1 .Nested.Name}}BSONDoc) {{.Nested.Name}} {
	var s {{.Nested.Name}}
	s.setBSONDoc(doc)
	return s
}

func {{lower1 .Nested.Name}}PtrBSONDoc(v *{{.Nested.Name}}) *{{lower1 .Nested.Name}}BSONDoc {
	if v == nil {
		return nil
	}
	doc := v.bsonDoc()
	return &doc
}

func {{lower1 .Nested.Name}}PtrFromBSONDoc(doc *{{lower1 .Nested.Name}}BSONDoc) *{{.Nested.Name}} {
	if doc == nil {
		return nil
	}
	v := {{lower1 .Nested.Name}}FromBSONDoc(*doc)
	return &v
}

func (s {{.Nested.Name}}) MarshalBSON() ([]byte, error) { return bson.Marshal(s.bsonDoc()) }

func (s *{{.Nested.Name}}) UnmarshalBSON(raw []byte) error {
	var doc {{lower1 .Nested.Name}}BSONDoc
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	s.setBSONDoc(doc)
	return nil
}
{{range .Nested.Fields}}
{{- if eq .Kind 2}}
func (s {{$.Nested.Name}}) {{fieldVar .Name}}RawMap() {{rawMapType .}} {
	if s.{{fieldVar .Name}} == nil {
		return nil
	}
	ret := make({{rawMapType .}}, s.{{fieldVar .Name}}.Len())
	s.{{fieldVar .Name}}.Range(func(key {{.MapKey}}, val {{mapValType .}}) bool {
		ret[key] = val
		return true
	})
	return ret
}

func (s *{{$.Nested.Name}}) set{{.Name}}RawMap(src {{rawMapType .}}) {
	s.{{fieldVar .Name}} = {{mapNewExpr . "len(src)"}}
	for key, val := range src {
		s.{{fieldVar .Name}}.Set(key, val)
	}
{{- if hasHook .}}
	// A restore is how a loaded document gets its children, so it is one of
	// the paths that establishes ownership (RR-20260917-05).
	s.bind{{.Name}}()
{{- end}}
}
{{end}}
{{- end}}
{{range .Nested.Fields}}
{{- if hasHook .}}
// bind{{.Name}}{{if hasDetach .}} / unbind{{.Name}}{{end}} move{{if hasDetach .}}{{else}}s{{end}} the notification ownership of
// {{.Name}}'s children and nothing else: no dirty mark, no undo record. That is
// what makes them callable from inside a rollback undo, where the transaction
// is already rolledBack and a public setter would register another undo and
// fail (RR-20260918-03). Every path that changes what the field holds — the
// setter, a restore from storage, the undo — releases what it drops and binds
// what it ends up with, so "which children notify this struct" always equals
// "which children the field holds".
func (s *{{$.Nested.Name}}) bind{{.Name}}() {
{{- if eq .Kind 2}}
	if s.{{fieldVar .Name}} == nil {
		return
	}
	s.{{fieldVar .Name}}.Range(func(key {{.MapKey}}, val {{mapValType .}}) bool {
		if val != nil {
			val.bindDirty(daoDirtyOwner{holder: s, field: {{nestedFieldOrdinal $.Nested .Name}}, key: key}, s.Mark)
		}
		return true
	})
{{- else if eq .Kind 1}}
	for index, val := range s.{{fieldVar .Name}} {
		if val != nil {
			val.bindDirty(daoDirtyOwner{holder: s, field: {{nestedFieldOrdinal $.Nested .Name}}, key: index}, s.Mark)
		}
	}
{{- else if .IsPtr}}
	if s.{{fieldVar .Name}} != nil {
		s.{{fieldVar .Name}}.bindDirty(daoDirtyOwner{holder: s, field: {{nestedFieldOrdinal $.Nested .Name}}}, s.Mark)
	}
{{- else}}
	s.{{fieldVar .Name}}.bindDirty(daoDirtyOwner{holder: s, field: {{nestedFieldOrdinal $.Nested .Name}}}, s.Mark)
{{- end}}
}
{{- if hasDetach .}}

func (s *{{$.Nested.Name}}) unbind{{.Name}}() {
{{- if eq .Kind 2}}
	if s.{{fieldVar .Name}} == nil {
		return
	}
	s.{{fieldVar .Name}}.Range(func(key {{.MapKey}}, val {{mapValType .}}) bool {
		if val != nil {
			val.unbindDirty(daoDirtyOwner{holder: s, field: {{nestedFieldOrdinal $.Nested .Name}}, key: key})
		}
		return true
	})
{{- else if eq .Kind 1}}
	for index, val := range s.{{fieldVar .Name}} {
		if val != nil {
			val.unbindDirty(daoDirtyOwner{holder: s, field: {{nestedFieldOrdinal $.Nested .Name}}, key: index})
		}
	}
{{- else}}
	if s.{{fieldVar .Name}} != nil {
		s.{{fieldVar .Name}}.unbindDirty(daoDirtyOwner{holder: s, field: {{nestedFieldOrdinal $.Nested .Name}}})
	}
{{- end}}
}
{{- end}}
{{end}}
{{- end}}
{{range .Nested.Fields}}
{{- if eq .Kind 0}}
func (s *{{$.Nested.Name}}) Get{{.Name}}() {{.TypeStr}} { return s.{{fieldVar .Name}} }
{{end}}
{{- if eq .Kind 3}}
{{- if .IsPtr}}
func (s *{{$.Nested.Name}}) Get{{.Name}}() {{.TypeStr}} { return s.{{fieldVar .Name}} }
{{- else}}
func (s *{{$.Nested.Name}}) Get{{.Name}}() *{{.TypeStr}} { return &s.{{fieldVar .Name}} }
{{- end}}
{{end}}
{{- if eq .Kind 1}}
func (s *{{$.Nested.Name}}) Get{{.Name}}(idx int) ({{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}, bool) {
	if idx < 0 || idx >= len(s.{{fieldVar .Name}}) {
		var zero {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}
		return zero, false
	}
	return s.{{fieldVar .Name}}[idx], true
}

func (s *{{$.Nested.Name}}) Range{{.Name}}(f func(idx int, val {{if .IsPtr}}*{{.SliceElem}}{{else}}{{.SliceElem}}{{end}}) bool) {
	if f == nil { return }
	for idx, val := range s.{{fieldVar .Name}} {
		if !f(idx, val) { return }
	}
}

func (s *{{$.Nested.Name}}) {{.Name}}Len() int { return len(s.{{fieldVar .Name}}) }
{{end}}
{{- if eq .Kind 2}}
func (s *{{$.Nested.Name}}) Get{{.Name}}(key {{.MapKey}}) ({{mapValType .}}, bool) {
	if s.{{fieldVar .Name}} == nil {
		var zero {{mapValType .}}
		return zero, false
	}
	return s.{{fieldVar .Name}}.Get(key)
}

func (s *{{$.Nested.Name}}) Range{{.Name}}(f func(key {{.MapKey}}, val {{mapValType .}}) bool) {
	if s.{{fieldVar .Name}} == nil || f == nil { return }
	s.{{fieldVar .Name}}.Range(f)
}

func (s *{{$.Nested.Name}}) {{.Name}}Len() int {
	if s.{{fieldVar .Name}} == nil { return 0 }
	return s.{{fieldVar .Name}}.Len()
}
{{end}}
{{end}}
{{range $idx, $field := .Nested.Fields}}
func (s *{{$.Nested.Name}}) Set{{.Name}}(v {{if eq .Kind 2}}{{rawMapType .}}{{else}}{{.TypeStr}}{{end}}) {
	if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
		old := s.{{fieldVar .Name}}
		if err := tx.RecordUndo(s, uint64({{$idx}}), func() error {
{{- if hasDetach .}}
			// The callbacks are not part of the field's value, so restoring
			// the value does not restore them (RR-20260918-03).
			s.unbind{{.Name}}()
{{- end}}
			s.{{fieldVar .Name}} = old
{{- if hasHook .}}
			s.bind{{.Name}}()
{{- end}}
			return nil
		}); err != nil {
			// A mutation without undo coverage silently breaks rollback;
			// failing loudly matches the generated DAO setters.
			panic(fmt.Errorf("{{$.Nested.Name}}: record undo: %w", err))
		}
	}
{{- if eq .Kind 0}}
	if s.{{fieldVar .Name}} != v {
		s.{{fieldVar .Name}} = v
		s.Mark()
	}
{{- else if eq .Kind 2}}
{{- if hasDetach .}}
	// The children being replaced stop reporting: a detached child marking a
	// parent it no longer belongs to is a dirty flag nobody can explain
	// (RR-20260917-05).
	s.unbind{{.Name}}()
{{- end}}
	s.{{fieldVar .Name}} = {{mapNewExpr . "len(v)"}}
	for key, val := range v {
		s.{{fieldVar .Name}}.Set(key, val)
	}
{{- if hasHook .}}
	s.bind{{.Name}}()
{{- end}}
	s.Mark()
{{- else if eq .Kind 1}}
{{- if hasDetach .}}
	s.unbind{{.Name}}()
{{- end}}
	s.{{fieldVar .Name}} = append({{.TypeStr}}(nil), v...)
{{- if hasHook .}}
	s.bind{{.Name}}()
{{- end}}
	s.Mark()
{{- else}}
{{- if hasDetach .}}
	s.unbind{{.Name}}()
{{- end}}
	s.{{fieldVar .Name}} = v
{{- if hasHook .}}
	s.bind{{.Name}}()
{{- end}}
	s.Mark()
{{- end}}
}
{{end}}`
