package dao

const redisDaoTemplate = `// Code generated by tool/dao. DO NOT EDIT.

package {{.Package}}

import (
	"context"
	{{- if isRaw .Dao.Mode }}
	"fmt"
	{{- end }}
	"time"

	fcache "github.com/tjbdwanghaibo/roost-core/cache"
	fredis "github.com/tjbdwanghaibo/roost-core/redis"
)

const (
	{{.Dao.Name}}RedisDAODefaultPrefix = {{goString .DefaultPrefix}}
	{{.Dao.Name}}RedisDAOName = {{goString .RedisName}}
)

const {{.Dao.Name}}RedisDAODefaultTTL time.Duration = {{.DefaultTTL}}

type {{.Dao.Name}}RedisDAO interface {
	Get{{.Dao.Name}}(ctx context.Context, key {{.Dao.KeyType}}) ({{.Dao.Name}}, bool, error)
	Set{{.Dao.Name}}(ctx context.Context, value {{.Dao.Name}}) error
	Delete{{.Dao.Name}}(ctx context.Context, key {{.Dao.KeyType}}) error
	Patch{{.Dao.Name}}(ctx context.Context, key {{.Dao.KeyType}}, path string, value any) error
}

type {{lower1 .Dao.Name}}RedisDAOStore struct {
	store   fcache.Store[{{.Dao.KeyType}}, {{.Dao.Name}}]
	{{- if isRefMap .Dao.Mode }}
	patcher fcache.RefHMapPatcher[{{.Dao.KeyType}}]
	{{- end }}
}

func NewLocal{{.Dao.Name}}RedisDAO() {{.Dao.Name}}RedisDAO {
	{{- if isRefMap .Dao.Mode }}
	return wrap{{.Dao.Name}}RedisDAOStore(fcache.NewLocalStore[{{.Dao.KeyType}}, {{.Dao.Name}}]({{lower1 .Dao.Name}}RedisDAOStoreConfig()), nil)
	{{- else }}
	return wrap{{.Dao.Name}}RedisDAOStore(fcache.NewLocalStore[{{.Dao.KeyType}}, {{.Dao.Name}}]({{lower1 .Dao.Name}}RedisDAOStoreConfig()))
	{{- end }}
}

func NewRedis{{.Dao.Name}}RedisDAO(redis fredis.IRedis, prefix string, ttl time.Duration) {{.Dao.Name}}RedisDAO {
	if prefix == "" {
		prefix = {{.Dao.Name}}RedisDAODefaultPrefix
	}
	if ttl <= 0 {
		ttl = {{.Dao.Name}}RedisDAODefaultTTL
	}
	{{- if isRefMap .Dao.Mode }}
	store := fcache.NewRedisRefHMapStore[{{.Dao.KeyType}}, {{.Dao.Name}}](redis, fcache.RefHMapConfig[{{.Dao.KeyType}}, {{.Dao.Name}}]{
		Prefix:      prefix,
		Name:        {{.Dao.Name}}RedisDAOName,
		TTL:         ttl,
		StoreConfig: {{lower1 .Dao.Name}}RedisDAOStoreConfig(),
	})
	return wrap{{.Dao.Name}}RedisDAOStore(store, store)
	{{- else }}
	store := fcache.NewRedisRawJSONStore[{{.Dao.KeyType}}, {{.Dao.Name}}](redis, ttl, func(key {{.Dao.KeyType}}) string {
		return fmt.Sprintf("%s:%v", prefix, key)
	}, {{lower1 .Dao.Name}}RedisDAOStoreConfig())
	return wrap{{.Dao.Name}}RedisDAOStore(store)
	{{- end }}
}

func NewCached{{.Dao.Name}}RedisDAO(local {{.Dao.Name}}RedisDAO, remote {{.Dao.Name}}RedisDAO) {{.Dao.Name}}RedisDAO {
	return NewCached{{.Dao.Name}}RedisDAOWithTTL(local, remote, 0)
}

func NewCached{{.Dao.Name}}RedisDAOWithTTL(local {{.Dao.Name}}RedisDAO, remote {{.Dao.Name}}RedisDAO, ttl time.Duration) {{.Dao.Name}}RedisDAO {
	{{- if isRefMap .Dao.Mode }}
	return wrap{{.Dao.Name}}RedisDAOStore(fcache.NewLayeredStore[{{.Dao.KeyType}}, {{.Dao.Name}}](
		unwrap{{.Dao.Name}}RedisDAOStore(local),
		unwrap{{.Dao.Name}}RedisDAOStore(remote),
		ttl,
		{{lower1 .Dao.Name}}RedisDAOStoreConfig(),
	), nil)
	{{- else }}
	return wrap{{.Dao.Name}}RedisDAOStore(fcache.NewLayeredStore[{{.Dao.KeyType}}, {{.Dao.Name}}](
		unwrap{{.Dao.Name}}RedisDAOStore(local),
		unwrap{{.Dao.Name}}RedisDAOStore(remote),
		ttl,
		{{lower1 .Dao.Name}}RedisDAOStoreConfig(),
	))
	{{- end }}
}

func (s {{lower1 .Dao.Name}}RedisDAOStore) Get{{.Dao.Name}}(ctx context.Context, key {{.Dao.KeyType}}) ({{.Dao.Name}}, bool, error) {
	if s.store == nil {
		return {{.Dao.Name}}{}, false, nil
	}
	return s.store.Get(ctx, key)
}

func (s {{lower1 .Dao.Name}}RedisDAOStore) Set{{.Dao.Name}}(ctx context.Context, value {{.Dao.Name}}) error {
	if s.store == nil {
		return nil
	}
	return s.store.Set(ctx, value)
}

func (s {{lower1 .Dao.Name}}RedisDAOStore) Delete{{.Dao.Name}}(ctx context.Context, key {{.Dao.KeyType}}) error {
	if s.store == nil {
		return nil
	}
	return s.store.Delete(ctx, key)
}

func (s {{lower1 .Dao.Name}}RedisDAOStore) Patch{{.Dao.Name}}(ctx context.Context, key {{.Dao.KeyType}}, path string, value any) error {
	{{- if isRefMap .Dao.Mode }}
	if s.patcher != nil {
		return s.patcher.Patch(ctx, key, path, value)
	}
	{{- end }}
	if s.store == nil {
		return nil
	}
	current, ok, err := s.store.Get(ctx, key)
	if err != nil || !ok {
		return err
	}
	if err := fcache.PatchStructPath(&current, path, value); err != nil {
		return err
	}
	return s.store.Set(ctx, current)
}

{{- if isRefMap .Dao.Mode }}
func wrap{{.Dao.Name}}RedisDAOStore(store fcache.Store[{{.Dao.KeyType}}, {{.Dao.Name}}], patcher fcache.RefHMapPatcher[{{.Dao.KeyType}}]) {{.Dao.Name}}RedisDAO {
	return {{lower1 .Dao.Name}}RedisDAOStore{store: store, patcher: patcher}
}
{{- else }}
func wrap{{.Dao.Name}}RedisDAOStore(store fcache.Store[{{.Dao.KeyType}}, {{.Dao.Name}}]) {{.Dao.Name}}RedisDAO {
	return {{lower1 .Dao.Name}}RedisDAOStore{store: store}
}
{{- end }}

func unwrap{{.Dao.Name}}RedisDAOStore(dao {{.Dao.Name}}RedisDAO) fcache.Store[{{.Dao.KeyType}}, {{.Dao.Name}}] {
	if dao == nil {
		return nil
	}
	if s, ok := dao.({{lower1 .Dao.Name}}RedisDAOStore); ok {
		return s.store
	}
	return {{lower1 .Dao.Name}}RedisDAOAdapter{dao: dao}
}

type {{lower1 .Dao.Name}}RedisDAOAdapter struct {
	dao {{.Dao.Name}}RedisDAO
}

func (s {{lower1 .Dao.Name}}RedisDAOAdapter) Get(ctx context.Context, key {{.Dao.KeyType}}) ({{.Dao.Name}}, bool, error) {
	return s.dao.Get{{.Dao.Name}}(ctx, key)
}

func (s {{lower1 .Dao.Name}}RedisDAOAdapter) Set(ctx context.Context, value {{.Dao.Name}}) error {
	return s.dao.Set{{.Dao.Name}}(ctx, value)
}

func (s {{lower1 .Dao.Name}}RedisDAOAdapter) Delete(ctx context.Context, key {{.Dao.KeyType}}) error {
	return s.dao.Delete{{.Dao.Name}}(ctx, key)
}

func {{lower1 .Dao.Name}}RedisDAOStoreConfig() fcache.StoreConfig[{{.Dao.KeyType}}, {{.Dao.Name}}] {
	return fcache.StoreConfig[{{.Dao.KeyType}}, {{.Dao.Name}}]{
		KeyOf: func(value {{.Dao.Name}}) {{.Dao.KeyType}} {
			return value.{{.Dao.Key}}
		},
		{{- if .Dao.Version }}
		Stale: fcache.VersionStale(func(value {{.Dao.Name}}) int64 { return int64(value.{{.Dao.Version}}) }),
		{{- end }}
	}
}
`
