package eventgen

import (
	"bytes"
	"fmt"
	"github.com/tjbdwanghaibo/roost-codegen/internal/genutil"
	"go/format"
	"sort"
	"text/template"
)

type typesTmplData struct {
	Package string
	Events  []EventDef
	Imports []string
}

func generateDefs(events []EventDef, pkg string, outFile string, force bool) (bool, error) {
	tmpl, err := template.New("defs").Parse(defsTemplate)
	if err != nil {
		return false, fmt.Errorf("template parse: %w", err)
	}

	data := typesTmplData{Package: pkg, Events: events, Imports: collectImports(events)}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return false, fmt.Errorf("template exec: %w", err)
	}

	return writeGoIfChanged(buf.Bytes(), outFile, force)
}

func generateTypes(events []EventDef, pkg string, outFile string, force bool) (bool, error) {
	tmpl, err := template.New("types").Parse(typesTemplate)
	if err != nil {
		return false, fmt.Errorf("template parse: %w", err)
	}

	data := typesTmplData{Package: pkg, Events: events}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return false, fmt.Errorf("template exec: %w", err)
	}

	return writeGoIfChanged(buf.Bytes(), outFile, force)
}

func generateTypeImpl(events []EventDef, pkg string, outFile string, force bool) (bool, error) {
	tmpl, err := template.New("type_impl").Parse(typeImplTemplate)
	if err != nil {
		return false, fmt.Errorf("template parse: %w", err)
	}

	data := typesTmplData{Package: pkg, Events: events}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return false, fmt.Errorf("template exec: %w", err)
	}

	return writeGoIfChanged(buf.Bytes(), outFile, force)
}

func writeGoIfChanged(content []byte, outFile string, force bool) (bool, error) {
	formatted, err := format.Source(content)
	if err != nil {
		return false, fmt.Errorf("format generated go: %w", err)
	}
	return writeIfChanged(formatted, outFile, force)
}

func collectImports(events []EventDef) []string {
	seen := make(map[string]struct{})
	for _, event := range events {
		for _, item := range event.Imports {
			if item == "" {
				continue
			}
			seen[item] = struct{}{}
		}
	}
	if len(seen) == 0 {
		return nil
	}
	out := make([]string, 0, len(seen))
	for item := range seen {
		out = append(out, item)
	}
	sort.Strings(out)
	return out
}

func writeIfChanged(content []byte, outFile string, force bool) (bool, error) {
	return genutil.WriteIfChanged(outFile, content, force)
}

var defsTemplate = `// Code generated by tool/eventgen. DO NOT EDIT.
package {{.Package}}

{{- if .Imports}}
import (
{{- range .Imports}}
	{{.}}
{{- end}}
)

{{- end}}
// Event definitions are declared in event/def.
{{range .Events}}
type {{.Name}} struct {
{{- range .Fields}}
	{{if .NamesText}}{{.NamesText}} {{end}}{{.Type}}{{if .Tag}} {{.Tag}}{{end}}
{{- end}}
}
{{end}}`

var typesTemplate = `// Code generated by tool/eventgen. DO NOT EDIT.
package {{.Package}}

import "github.com/tjbdwanghaibo/roost-core/event"

// EventType constants.
const (
	EventTypeInvalid event.EventType = iota
{{- range .Events}}
	{{.ConstName}}
{{- end}}
	EventTypeMaxCount
)
`

var typeImplTemplate = `// Code generated by tool/eventgen. DO NOT EDIT.
package {{.Package}}

import "github.com/tjbdwanghaibo/roost-core/event"

// Ensure EventData compliance.
var (
{{- range .Events}}
	_ event.EventData = (*{{.Name}})(nil)
{{- end}}
)
{{range .Events}}
func (e *{{.Name}}) Type() event.EventType { return {{.ConstName}} }
{{end}}`
