// Code generated by tool/dao. DO NOT EDIT.
package db

import (
	"fmt"
	"github.com/tjbdwanghaibo/roost-core/dataengine"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// MonsterDao has no collection (//roost:dao nocoll): it is never stored,
// only read and written through its entity's components, rolled back with
// the transaction and replicated through MarshalSync.
type MonsterDao struct {
	id       int64
	tracker  dataengine.Tracker
	template int32
	posX     int64
	posY     int64
	hp       int64
}

// Ensure interface compliance.
var _ entity.DaoInterface = (*MonsterDao)(nil)
var _ nest.RollbackSnapshotter = (*MonsterDao)(nil)

// MonsterDaoRegistryKey is the key this DAO is registered under in its
// entity's DaoManager. It is not a collection name: nothing is stored.
const MonsterDaoRegistryKey = "MonsterDao"

// NewMonsterDao creates a new MonsterDao instance with initialized maps/slices.
func NewMonsterDao() *MonsterDao {
	d := &MonsterDao{}
	// Wire the nested callbacks here, not only on the hydration paths. A
	// component reaches a nested value directly (dao.GetEquipment().SetX)
	// and never goes through this DAO's own setter, so an entity that was
	// CREATED rather than loaded would have an unbound nested value: the
	// change marks nothing, never enters the persist patch, and is lost
	// without a word until the entity has been stored and read back once
	// (U-0245).
	d.Init()
	return d
}

func (d *MonsterDao) Id() int64      { return d.id }
func (d *MonsterDao) SetId(id int64) { d.id = id }

// DbName is empty and CollName is the registry key: entity.DaoInterface asks
// for both, and this DAO has neither a database nor a collection.
func (d *MonsterDao) DbName() string                    { return "" }
func (d *MonsterDao) CollName() string                  { return MonsterDaoRegistryKey }
func (d *MonsterDao) Dirty() entity.IDirty              { return &d.tracker }
func (d *MonsterDao) CleanDirty()                       { d.tracker.SelfClean() }
func (d *MonsterDao) DirtyTracker() *dataengine.Tracker { return &d.tracker }

const (
	monsterDaoFieldTemplate uint64 = 1 << iota
	monsterDaoFieldPosX     uint64 = 1 << iota
	monsterDaoFieldPosY     uint64 = 1 << iota
	monsterDaoFieldHP       uint64 = 1 << iota
)

func (d *MonsterDao) markTemplateDirty() {
	d.tracker.MarkSync(monsterDaoFieldTemplate)
}

func (d *MonsterDao) markPosXDirty() {
	d.tracker.MarkSync(monsterDaoFieldPosX)
}

func (d *MonsterDao) markPosYDirty() {
	d.tracker.MarkSync(monsterDaoFieldPosY)
}

func (d *MonsterDao) markHPDirty() {
	d.tracker.MarkSync(monsterDaoFieldHP)
}

// Init wires dirty callbacks for nested structs and map values.
func (d *MonsterDao) Init() {
}

// --- Accessors ---

func (d *MonsterDao) GetTemplate() int32 { return d.template }

func (d *MonsterDao) GetPosX() int64 { return d.posX }

func (d *MonsterDao) GetPosY() int64 { return d.posY }

func (d *MonsterDao) GetHP() int64 { return d.hp }

// --- Mutators ---

// recordUndo / recordUndoToken register the inverse operation and panic when
// registration fails: continuing would let the mutation escape rollback
// coverage, silently breaking the transaction guarantee.
func (d *MonsterDao) recordUndo(tx *nest.RollbackTx, field uint64, fn func() error) {
	if err := tx.RecordUndo(d, field, fn); err != nil {
		panic(fmt.Errorf("MonsterDao: record undo: %w", err))
	}
}

func (d *MonsterDao) recordUndoToken(tx *nest.RollbackTx, field uint64, token any, fn func() error) {
	if err := tx.RecordUndoToken(d, field, token, fn); err != nil {
		panic(fmt.Errorf("MonsterDao: record undo: %w", err))
	}
}

func (d *MonsterDao) SetTemplate(v int32) {
	if d.template != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.template
			d.recordUndo(tx, monsterDaoFieldTemplate, func() error { d.template = old; return nil })
		}
		d.template = v
		d.markTemplateDirty()
	}
}

func (d *MonsterDao) SetPosX(v int64) {
	if d.posX != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.posX
			d.recordUndo(tx, monsterDaoFieldPosX, func() error { d.posX = old; return nil })
		}
		d.posX = v
		d.markPosXDirty()
	}
}

func (d *MonsterDao) SetPosY(v int64) {
	if d.posY != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.posY
			d.recordUndo(tx, monsterDaoFieldPosY, func() error { d.posY = old; return nil })
		}
		d.posY = v
		d.markPosYDirty()
	}
}

func (d *MonsterDao) SetHP(v int64) {
	if d.hp != v {
		if tx := nest.CurrentRollbackTx(); tx != nil && tx.Policy() == nest.RollbackUndo {
			old := d.hp
			d.recordUndo(tx, monsterDaoFieldHP, func() error { d.hp = old; return nil })
		}
		d.hp = v
		d.markHPDirty()
	}
}

// --- Marshal (persist fields) ---

// CaptureRollbackState is side-effect free and includes transient and
// sync-only fields. Persistence changes live in RollbackTx, not in the DAO.
func (d *MonsterDao) CaptureRollbackState() ([]byte, error) {
	type rollbackDoc struct {
		Id       int64 `bson:"_id"`
		Template int32 `bson:"template"`
		PosX     int64 `bson:"pos_x"`
		PosY     int64 `bson:"pos_y"`
		HP       int64 `bson:"hp"`
	}
	doc := rollbackDoc{
		Id:       d.id,
		Template: d.template,
		PosX:     d.posX,
		PosY:     d.posY,
		HP:       d.hp,
	}
	return bson.Marshal(doc)
}

func (d *MonsterDao) RestoreRollbackState(raw []byte) error {
	type rollbackDoc struct {
		Id       int64 `bson:"_id"`
		Template int32 `bson:"template"`
		PosX     int64 `bson:"pos_x"`
		PosY     int64 `bson:"pos_y"`
		HP       int64 `bson:"hp"`
	}
	var doc rollbackDoc
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	d.id = doc.Id
	d.template = doc.Template
	d.posX = doc.PosX
	d.posY = doc.PosY
	d.hp = doc.HP
	d.Init()
	return nil
}

// MonsterDaoSyncFields is the vocabulary for this DAO's dirty masks: which
// field each bit means, and what it is called on the wire.
//
// It exists because the bit constants themselves are unexported — a packer
// written outside this package can hand a mask to MarshalSync but cannot look
// inside it, which is fine until the game has its own client protocol and has
// to decide what changed (ARCH-06).
//
// **Bit is stable only within this generated schema.** Anything that outlives
// the build — a stored projection, a client's cached layout — keys on Name or
// WireName. The bits are not an ABI.
func MonsterDaoSyncFields() []dataengine.SyncFieldMeta {
	return []dataengine.SyncFieldMeta{
		{Name: "Template", WireName: "template", Bit: monsterDaoFieldTemplate},
		{Name: "PosX", WireName: "pos_x", Bit: monsterDaoFieldPosX},
		{Name: "PosY", WireName: "pos_y", Bit: monsterDaoFieldPosY},
		{Name: "HP", WireName: "hp", Bit: monsterDaoFieldHP},
	}
}

// SyncFields is the same table, reachable from a value — a packer holds the
// DAO, not the package.
func (d *MonsterDao) SyncFields() []dataengine.SyncFieldMeta { return MonsterDaoSyncFields() }

func (d *MonsterDao) MarshalSync(mask uint64) []byte {
	doc := bson.M{
		"_id": d.id,
	}
	if mask&monsterDaoFieldTemplate != 0 {
		doc["template"] = d.template
	}
	if mask&monsterDaoFieldPosX != 0 {
		doc["pos_x"] = d.posX
	}
	if mask&monsterDaoFieldPosY != 0 {
		doc["pos_y"] = d.posY
	}
	if mask&monsterDaoFieldHP != 0 {
		doc["hp"] = d.hp
	}
	if len(doc) == 1 {
		return nil
	}
	data, err := bson.Marshal(doc)
	if err != nil {
		// nil already means "nothing to sync"; returning it on failure would
		// silently drop a sync payload. See marshalPersistData.
		panic(fmt.Errorf("MonsterDao: marshal sync data: %w", err))
	}
	return data
}

func (d *MonsterDao) ApplySync(raw []byte) error {
	var doc bson.M
	if err := bson.Unmarshal(raw, &doc); err != nil {
		return err
	}
	if v, ok := doc["template"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V int32 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.template = wrap.V
	}
	if v, ok := doc["pos_x"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V int64 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.posX = wrap.V
	}
	if v, ok := doc["pos_y"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V int64 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.posY = wrap.V
	}
	if v, ok := doc["hp"]; ok {
		data, err := bson.Marshal(bson.M{"v": v})
		if err != nil {
			return err
		}
		var wrap struct {
			V int64 `bson:"v"`
		}
		if err := bson.Unmarshal(data, &wrap); err != nil {
			return err
		}
		d.hp = wrap.V
	}
	d.Init()
	return nil
}

// compile-time import guards
var (
	_ = dataengine.Tracker{}
	_ = bson.M{}
)
