// Code generated by tool/nest. DO NOT EDIT.
package handler

import (
	"errors"
	player "example.com/planet/game/entities/player"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"sync"
)

var (
	_ = errors.New
	_ entity.IThreadSafeEntity
)
var (
	handlerNameAddItem = nest.NewHandlerName("handlerAddItem")
)

var registerAddItemNestHandlersOnce sync.Once

func invokeAddItem(es []entity.IThreadSafeEntity, params []any, opts ...nest.HandlerOption) (ret any, err error) {
	if len(es) != 1 {
		err = nest.NewEntityCountMismatchError(handlerNameAddItem.String(), len(es), 1)
		return
	}
	e0, ok := es[0].(player.IBagEntity)
	if !ok {
		err = nest.ErrEntityTypeMismatch
		return
	}
	if len(params) != 2 {
		err = nest.NewParamCountMismatchError(handlerNameAddItem.String(), len(params), 2)
		return
	}
	p0, ok := params[0].(int64)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameAddItem.String(), 0, "int64", params[0])
		return
	}
	p1, ok := params[1].(int32)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameAddItem.String(), 1, "int32", params[1])
		return
	}
	ret, err = handlerAddItem(e0, p0, p1)
	return
}

func RegisterAddItemNestHandlers() {

	registerAddItemNestHandlersOnce.Do(func() {
		nest.MustRegisterHandlerWithMeta(handlerNameAddItem, invokeAddItem, nest.HandlerMeta{Rollback: nest.RollbackUndo, Durability: nest.DurabilityStrict})
	})
}
