// Code generated by tool/nest. DO NOT EDIT.
package handler

import (
	"errors"
	world "example.com/planet/game/entities/world"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"sync"
)

var (
	_ = errors.New
	_ entity.IThreadSafeEntity
)
var (
	handlerNameArmActivity = nest.NewHandlerName("handlerArmActivity")
)

var registerArmActivityNestHandlersOnce sync.Once

func invokeArmActivity(es []entity.IThreadSafeEntity, params []any, opts ...nest.HandlerOption) (ret any, err error) {
	if len(es) != 1 {
		err = nest.NewEntityCountMismatchError(handlerNameArmActivity.String(), len(es), 1)
		return
	}
	e0, ok := es[0].(world.ITimerEntity)
	if !ok {
		err = nest.ErrEntityTypeMismatch
		return
	}
	if len(params) != 3 {
		err = nest.NewParamCountMismatchError(handlerNameArmActivity.String(), len(params), 3)
		return
	}
	p0, ok := params[0].(string)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameArmActivity.String(), 0, "string", params[0])
		return
	}
	p1, ok := params[1].(int64)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameArmActivity.String(), 1, "int64", params[1])
		return
	}
	p2, ok := params[2].(int64)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameArmActivity.String(), 2, "int64", params[2])
		return
	}
	ret, err = handlerArmActivity(e0, p0, p1, p2)
	return
}

func RegisterArmActivityNestHandlers() {

	registerArmActivityNestHandlersOnce.Do(func() {
		nest.MustRegisterHandlerWithMeta(handlerNameArmActivity, invokeArmActivity, nest.HandlerMeta{Rollback: nest.RollbackUndo, Durability: nest.DurabilityStrict})
	})
}
