// Code generated by tool/nest. DO NOT EDIT.
package handler

import (
	"errors"
	player "example.com/planet/game/entities/player"
	world "example.com/planet/game/entities/world"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"sync"
)

var (
	_ = errors.New
	_ entity.IThreadSafeEntity
)
var (
	handlerNameClaimDungeon = nest.NewHandlerName("handlerClaimDungeon")
)

var registerClaimDungeonNestHandlersOnce sync.Once

func invokeClaimDungeon(es []entity.IThreadSafeEntity, params []any, opts ...nest.HandlerOption) (ret any, err error) {
	if len(es) != 2 {
		err = nest.NewEntityCountMismatchError(handlerNameClaimDungeon.String(), len(es), 2)
		return
	}
	e0, ok := es[0].(player.IProfileEntity)
	if !ok {
		err = nest.ErrEntityTypeMismatch
		return
	}
	e1, ok := es[1].(world.IStatsEntity)
	if !ok {
		err = nest.ErrEntityTypeMismatch
		return
	}
	if len(params) != 4 {
		err = nest.NewParamCountMismatchError(handlerNameClaimDungeon.String(), len(params), 4)
		return
	}
	p0, ok := params[0].(string)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameClaimDungeon.String(), 0, "string", params[0])
		return
	}
	p1, ok := params[1].(int64)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameClaimDungeon.String(), 1, "int64", params[1])
		return
	}
	p2, ok := params[2].(int64)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameClaimDungeon.String(), 2, "int64", params[2])
		return
	}
	p3, ok := params[3].(int64)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameClaimDungeon.String(), 3, "int64", params[3])
		return
	}
	ret, err = handlerClaimDungeon(e0, e1, p0, p1, p2, p3)
	return
}

func RegisterClaimDungeonNestHandlers() {

	registerClaimDungeonNestHandlersOnce.Do(func() {
		nest.MustRegisterHandlerWithMeta(handlerNameClaimDungeon, invokeClaimDungeon, nest.HandlerMeta{Rollback: nest.RollbackUndo, Durability: nest.DurabilityStrict})
	})
}
