// Code generated by tool/nest. DO NOT EDIT.
package handler

import (
	"errors"
	guild "example.com/planet/game/entities/guild"
	player "example.com/planet/game/entities/player"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"sync"
)

var (
	_ = errors.New
	_ entity.IThreadSafeEntity
)
var (
	handlerNameJoinGuild = nest.NewHandlerName("handlerJoinGuild")
)

var registerJoinGuildNestHandlersOnce sync.Once

func invokeJoinGuild(es []entity.IThreadSafeEntity, params []any, opts ...nest.HandlerOption) (ret any, err error) {
	if len(es) != 2 {
		err = nest.NewEntityCountMismatchError(handlerNameJoinGuild.String(), len(es), 2)
		return
	}
	e0, ok := es[0].(guild.IRosterEntity)
	if !ok {
		err = nest.ErrEntityTypeMismatch
		return
	}
	e1, ok := es[1].(player.IProfileEntity)
	if !ok {
		err = nest.ErrEntityTypeMismatch
		return
	}
	if len(params) != 2 {
		err = nest.NewParamCountMismatchError(handlerNameJoinGuild.String(), len(params), 2)
		return
	}
	p0, ok := params[0].(int64)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameJoinGuild.String(), 0, "int64", params[0])
		return
	}
	p1, ok := params[1].(int64)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameJoinGuild.String(), 1, "int64", params[1])
		return
	}
	ret, err = handlerJoinGuild(e0, e1, p0, p1)
	return
}

func RegisterJoinGuildNestHandlers() {

	registerJoinGuildNestHandlersOnce.Do(func() {
		nest.MustRegisterHandlerWithMeta(handlerNameJoinGuild, invokeJoinGuild, nest.HandlerMeta{Rollback: nest.RollbackUndo, Durability: nest.DurabilityStrict})
	})
}
