// Code generated by tool/nest. DO NOT EDIT.
package handler

import (
	"errors"
	world "example.com/planet/game/entities/world"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"sync"
)

var (
	_ = errors.New
	_ entity.IThreadSafeEntity
)
var (
	handlerNameRecordEnter = nest.NewHandlerName("handlerRecordEnter")
)

var registerRecordEnterNestHandlersOnce sync.Once

func invokeRecordEnter(es []entity.IThreadSafeEntity, params []any, opts ...nest.HandlerOption) (ret any, err error) {
	if len(es) != 1 {
		err = nest.NewEntityCountMismatchError(handlerNameRecordEnter.String(), len(es), 1)
		return
	}
	e0, ok := es[0].(world.IStatsEntity)
	if !ok {
		err = nest.ErrEntityTypeMismatch
		return
	}
	err = handlerRecordEnter(e0)
	return
}

func RegisterRecordEnterNestHandlers() {

	registerRecordEnterNestHandlersOnce.Do(func() {
		nest.MustRegisterHandlerWithMeta(handlerNameRecordEnter, invokeRecordEnter, nest.HandlerMeta{Rollback: nest.RollbackUndo, Durability: nest.DurabilityStrict})
	})
}
