// Code generated by tool/nest. DO NOT EDIT.
package handler

import (
	"errors"
	world "example.com/planet/game/entities/world"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"sync"
)

var (
	_ = errors.New
	_ entity.IThreadSafeEntity
)
var (
	handlerNameTickWorldTimers = nest.NewHandlerName("handlerTickWorldTimers")
)

var registerTickWorldTimersNestHandlersOnce sync.Once

func invokeTickWorldTimers(es []entity.IThreadSafeEntity, params []any, opts ...nest.HandlerOption) (ret any, err error) {
	if len(es) != 1 {
		err = nest.NewEntityCountMismatchError(handlerNameTickWorldTimers.String(), len(es), 1)
		return
	}
	e0, ok := es[0].(world.ITimerEntity)
	if !ok {
		err = nest.ErrEntityTypeMismatch
		return
	}
	if len(params) != 1 {
		err = nest.NewParamCountMismatchError(handlerNameTickWorldTimers.String(), len(params), 1)
		return
	}
	p0, ok := params[0].(int64)
	if !ok {
		err = nest.NewParamTypeMismatchError(handlerNameTickWorldTimers.String(), 0, "int64", params[0])
		return
	}
	ret, err = handlerTickWorldTimers(e0, p0)
	return
}

func RegisterTickWorldTimersNestHandlers() {

	registerTickWorldTimersNestHandlersOnce.Do(func() {
		nest.MustRegisterHandlerWithMeta(handlerNameTickWorldTimers, invokeTickWorldTimers, nest.HandlerMeta{Rollback: nest.RollbackUndo, Durability: nest.DurabilityStrict})
	})
}
