// Code generated by tool/nest. DO NOT EDIT.
package handler

import (
	"errors"
	world "example.com/planet/game/entities/world"
	"github.com/tjbdwanghaibo/roost-core/entity"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"sync"
)

var (
	_ = errors.New
	_ entity.IThreadSafeEntity
)
var (
	handlerNameWorldStats = nest.NewHandlerName("handlerWorldStats")
)

var registerWorldStatsNestHandlersOnce sync.Once

func invokeWorldStats(es []entity.IThreadSafeEntity, params []any, opts ...nest.HandlerOption) (ret any, err error) {
	if len(es) != 1 {
		err = nest.NewEntityCountMismatchError(handlerNameWorldStats.String(), len(es), 1)
		return
	}
	e0, ok := es[0].(world.IStatsEntity)
	if !ok {
		err = nest.ErrEntityTypeMismatch
		return
	}
	ret, err = handlerWorldStats(e0)
	return
}

func RegisterWorldStatsNestHandlers() {

	registerWorldStatsNestHandlersOnce.Do(func() {
		nest.MustRegisterHandlerWithMeta(handlerNameWorldStats, invokeWorldStats, nest.HandlerMeta{Rollback: nest.RollbackState, Durability: nest.DurabilityAsync})
	})
}
