// Code generated by tool/protocol. DO NOT EDIT.
package msgid

const (
	MsgAddItem          uint32 = 10000
	MsgAddExp           uint32 = 10001
	MsgEnterGame        uint32 = 10002
	MsgJoinQueue        uint32 = 10003
	MsgPollMatch        uint32 = 10004
	MsgWorldStats       uint32 = 10005
	MsgSendChat         uint32 = 10006
	MsgChatHistory      uint32 = 10007
	MsgListMail         uint32 = 10008
	MsgClaimMail        uint32 = 10009
	MsgEnterDungeon     uint32 = 10010
	MsgFinishDungeon    uint32 = 10011
	MsgSkillCatalog     uint32 = 10012
	MsgSendGift         uint32 = 10013
	MsgGiftStatus       uint32 = 10014
	MsgBattleInput      uint32 = 10015
	MsgRankTop          uint32 = 10016
	MsgMove             uint32 = 10017
	MsgEquip            uint32 = 10018
	MsgPurchase         uint32 = 10019
	MsgActivityStanding uint32 = 10020
	MsgFoundGuild       uint32 = 10021
	MsgJoinGuild        uint32 = 10022
	MsgGuildInfo        uint32 = 10023
	MsgSceneReady       uint32 = 10024
	MsgMatchFound       uint32 = 10100
	MsgChatMessage      uint32 = 10101
	MsgBattleFrame      uint32 = 10102
	MsgEntitySync       uint32 = 10103
)

var msgTags = map[uint32][]string{}

func MsgTags(msgID uint32) []string {
	tags := msgTags[msgID]
	if len(tags) == 0 {
		return nil
	}
	out := make([]string, len(tags))
	copy(out, tags)
	return out
}

func MsgHasTag(msgID uint32, tag string) bool {
	for _, cur := range msgTags[msgID] {
		if cur == tag {
			return true
		}
	}
	return false
}

func MsgHasAnyTag(msgID uint32, tags ...string) bool {
	if len(tags) == 0 {
		return false
	}
	for _, tag := range tags {
		if MsgHasTag(msgID, tag) {
			return true
		}
	}
	return false
}
