// Code generated by tool/entity. DO NOT EDIT.
package remote

import (
	"fmt"
	"sync"

	"github.com/tjbdwanghaibo/roost-core/dataengine"
	"github.com/tjbdwanghaibo/roost-core/entity"
)

var registerEntityOnce sync.Once

// RegisterEntity registers the Guild entity builder.
func RegisterEntity() {
	registerEntityOnce.Do(func() {
		entity.RegisterEntityBuilder(&entity.EntityBuilderParam{
			Category: entity.MustEntityCategoryOfKind(EntityKindGuild),
			Kind:     EntityKindGuild,
			Builder: func(param *entity.EntityCreateParam) (entity.IThreadSafeEntity, error) {
				return NewGuild(param)
			},
			DaoBuilders: []entity.DaoBuilderFunc{
				func() entity.DaoInterface { return NewGuildDAO() },
			},
			NoPersist:    false,
			RemotePolicy: entity.RemotePolicyManaged,
			Lifetime:     entity.EntityLifetimeRemoteManaged,
		})
		entity.MustRegisterRemoteSnapshotDecoder(
			entity.RemoteSnapshotSchema(EntityKindGuild, entity.RemoteSnapshotScope(GuildDAOCollection)),
			func(data []byte) (any, error) {
				dao := NewGuildDAO()
				decoder, ok := any(dao).(interface{ ApplySync([]byte) error })
				if !ok {
					return nil, fmt.Errorf("Guild: remote snapshot DAO guilds does not implement ApplySync")
				}
				if err := decoder.ApplySync(data); err != nil {
					return nil, err
				}
				return dao, nil
			},
		)
	})
}

func NewGuild(param *entity.EntityCreateParam) (*Guild, error) {
	e := &Guild{}
	if err := param.NormalizeID(EntityKindGuild); err != nil {
		return nil, err
	}

	// EntityBase
	e.RemoteEntityBase = entity.NewRemoteEntityBaseWithMutex(param.Id, param.Category, false, param.Mutex, param.Kind)
	e.EntityBase.SetHooks(e.generatedOnClear, e.generatedOnDestroy)

	// DaoManager
	e.DaoManager = entity.NewDaoManager()

	// DAO: dao
	if raw, ok := param.Dao[GuildDAOCollection]; ok {
		e.dao = raw.(*GuildDAO)
	} else {
		e.dao = NewGuildDAO()
		e.dao.SetId(param.StorageID())
	}
	if e.dao != nil {
		e.DaoManager.Set(GuildDAOCollection, e.dao)
	}

	return e, nil
}
func (e *Guild) Base() *entity.EntityBase { return &e.RemoteEntityBase.EntityBase }

func (e *Guild) DAO() *GuildDAO { return e.dao }

func (e *Guild) generatedOnClear() {
	e.DaoManager.Clear()
	e.dao = nil
}

func (e *Guild) generatedOnDestroy(reason entity.EntityDestroyReason) {
}

var _ entity.IRemoteCommitParticipant = (*Guild)(nil)
var _ entity.IRemoteCommitChangeParticipant = (*Guild)(nil)

// HasRemoteCommitLocked consults only the active Nest transaction. Sync dirty
// state is intentionally unrelated to persistence admission.
func (e *Guild) HasRemoteCommitLocked(outcome entity.RemoteTransactionOutcome) bool {
	if outcome.DeleteIntents != nil && outcome.DeleteIntents.RemoteDeleteRequested(e.GUId()) {
		return true
	}
	if outcome.PersistChanges == nil {
		return false
	}
	if e.dao != nil {
		if _, ok := outcome.PersistChanges.RemotePersistChangeFor(e.dao); ok {
			return true
		}
	}
	return false
}

// BuildRemoteCommitLocked freezes DAO state while Nest holds the entity mutex.
// The returned commit owns all byte slices and is safe for asynchronous WAL use.
func (e *Guild) BuildRemoteCommitLocked(lease entity.RemoteWriteLease, outcome entity.RemoteTransactionOutcome) (entity.RemoteCommit, error) {
	deleteRequested := outcome.DeleteIntents != nil && outcome.DeleteIntents.RemoteDeleteRequested(e.GUId())
	commit := entity.RemoteCommit{
		TransactionID: outcome.TransactionID,
		EntityID:      e.GUId(),
		Kind:          e.GetEntityKind(),
		Delete:        deleteRequested,
		BaseVersion:   lease.BaseVersion,
		NextVersion:   lease.BaseVersion + 1,
		MarkerEpoch:   lease.MarkerEpoch,
		LockFence:     lease.LockFence,
		RouteEpoch:    lease.RouteEpoch,
		Schema:        1,
		Codec:         1,
	}
	if commit.Delete {
		if e.dao != nil {
			commit.Deletes = append(commit.Deletes, entity.RemoteDataDelete{
				Database: e.dao.DbName(), DatabaseScope: uint8(dataengine.ResolveDatabaseScope(e.dao)),
				Collection: e.dao.CollName(), ID: e.dao.Id(),
			})
		}
		commit.Invalidations = append(commit.Invalidations, entity.RemoteSnapshotKey{
			EntityID: e.GUId(), Kind: e.GetEntityKind(), Scope: entity.RemoteSnapshotScope(GuildDAOCollection),
		})
		return commit, nil
	}
	if e.dao != nil {
		if outcome.PersistChanges == nil {
			return entity.RemoteCommit{}, fmt.Errorf("Guild: missing transaction-local remote persistence changes")
		}
		if change, ok := outcome.PersistChanges.RemotePersistChangeFor(e.dao); ok {
			if change.Delete {
				return entity.RemoteCommit{}, fmt.Errorf("Guild: DAO-level remote delete requires entity removal for guilds")
			}
			mask := change.Mask
			data := append([]byte(nil), e.dao.MarshalPersist(mask)...)
			if len(data) == 0 {
				return entity.RemoteCommit{}, fmt.Errorf("Guild: empty remote mutation for guilds")
			}
			mutation := entity.RemoteDataMutation{
				Database:      e.dao.DbName(),
				DatabaseScope: uint8(dataengine.ResolveDatabaseScope(e.dao)),
				Collection:    e.dao.CollName(),
				ID:            e.dao.Id(),
				Version:       commit.NextVersion,
				Mask:          mask,
				Data:          data,
			}
			commit.Mutations = append(commit.Mutations, mutation)
			scope := entity.RemoteSnapshotScope(e.dao.CollName())
			commit.Snapshots = append(commit.Snapshots, entity.RemoteSnapshotRecord{
				Key:      entity.RemoteSnapshotKey{EntityID: e.GUId(), Kind: e.GetEntityKind(), Scope: scope},
				Schema:   entity.RemoteSnapshotSchema(e.GetEntityKind(), scope),
				Codec:    1,
				Full:     true,
				Data:     append([]byte(nil), data...),
				Checksum: entity.RemoteSnapshotChecksum(data),
			})
		}
	}
	return commit, nil
}

// AcknowledgeRemoteCommit advances only DAOs present in the authoritative
// remote receipt. The operation is idempotent and allows aggregate-version
// jumps when another DAO changed in an intervening transaction.
func (e *Guild) AcknowledgeRemoteCommit(commit entity.RemoteCommit) error {
	if commit.EntityID != e.GUId() {
		return fmt.Errorf("Guild: remote acknowledgement identity mismatch")
	}
	for _, mutation := range commit.Mutations {
		switch mutation.Collection {
		case GuildDAOCollection:
			if e.dao != nil {
				if err := e.dao.DirtyTracker().AdvanceVersion(commit.NextVersion); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

// RollbackRemoteCommit is a no-op: Build freezes transaction-local changes and
// does not mutate DAO persistence state before authoritative acceptance.
func (e *Guild) RollbackRemoteCommit(entity.RemoteCommit) {}
