// Code generated by tool/nest. DO NOT EDIT.
package handler_sender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"time"
)

var (
	_ = time.Second
)
var (
	handlerNameActivitySettled = nest.NewHandlerName("handlerActivitySettled")
)

// ActivitySettledSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type ActivitySettledSender struct {
	client nest.Client
}

func NewActivitySettledSender(client nest.Client) *ActivitySettledSender {
	return &ActivitySettledSender{client: client}
}

func (s *ActivitySettledSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *ActivitySettledSender) Delay_ActivitySettled(ctx context.Context, delay time.Duration, id int64, activityID string) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameActivitySettled, id, nest.NewParams(activityID), nest.SendOptionWithDelay(delay))
}

func (s *ActivitySettledSender) Send_ActivitySettled(ctx context.Context, id int64, activityID string) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameActivitySettled, id, nest.NewParams(activityID))
}

func (s *ActivitySettledSender) Broadcast_ActivitySettled(ctx context.Context, ids []int64, activityID string) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.DispatchBroadcast(ctx, handlerNameActivitySettled, ids, nest.NewParams(activityID))
}
