// Code generated by tool/nest. DO NOT EDIT.
package handler_sender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"time"
)

var (
	_ = time.Second
)
var (
	handlerNameAddItem = nest.NewHandlerName("handlerAddItem")
)

// AddItemSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type AddItemSender struct {
	client nest.Client
}

func NewAddItemSender(client nest.Client) *AddItemSender {
	return &AddItemSender{client: client}
}

func (s *AddItemSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *AddItemSender) Delay_AddItem(ctx context.Context, delay time.Duration, id int64, itemID int64, count int32) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameAddItem, id, nest.NewParams(itemID, count), nest.SendOptionWithDelay(delay))
}

func (s *AddItemSender) Send_AddItem(ctx context.Context, id int64, itemID int64, count int32) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameAddItem, id, nest.NewParams(itemID, count))
}

func (s *AddItemSender) Broadcast_AddItem(ctx context.Context, ids []int64, itemID int64, count int32) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.DispatchBroadcast(ctx, handlerNameAddItem, ids, nest.NewParams(itemID, count))
}
