// Code generated by tool/nest. DO NOT EDIT.
package handler_sender

import (
	"errors"
	"testing"

	"github.com/tjbdwanghaibo/roost-core/nest"
)

// TestAddExpSenderRefusesCallsWithoutAClient pins that a sender constructed without a
// Nest client, or a nil sender, refuses with nest.ErrNestStopped instead of
// dereferencing nil on the first call.
func TestAddExpSenderRefusesCallsWithoutAClient(t *testing.T) {
	var none *AddExpSender
	if _, err := none.nestClient(); !errors.Is(err, nest.ErrNestStopped) {
		t.Fatalf("nil sender nestClient() = %v, want nest.ErrNestStopped", err)
	}
	if _, err := NewAddExpSender(nil).nestClient(); !errors.Is(err, nest.ErrNestStopped) {
		t.Fatalf("sender without client nestClient() = %v, want nest.ErrNestStopped", err)
	}
}
