// Code generated by tool/nest. DO NOT EDIT.
package handler_sender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"time"
)

var (
	_ = time.Second
)
var (
	handlerNameEnterScene = nest.NewHandlerName("handlerEnterScene")
)

// EnterSceneSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type EnterSceneSender struct {
	client nest.Client
}

func NewEnterSceneSender(client nest.Client) *EnterSceneSender {
	return &EnterSceneSender{client: client}
}

func (s *EnterSceneSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *EnterSceneSender) MultiDelay_EnterScene(ctx context.Context, delay time.Duration, target int64, area int64, spawnX int64, spawnY int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	ids := []int64{target, area}
	return client.DispatchMulti(ctx, handlerNameEnterScene, ids, nest.NewParams(spawnX, spawnY), nest.SendOptionWithDelay(delay))
}

func (s *EnterSceneSender) MultiSend_EnterScene(ctx context.Context, target int64, area int64, spawnX int64, spawnY int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	ids := []int64{target, area}
	return client.DispatchMulti(ctx, handlerNameEnterScene, ids, nest.NewParams(spawnX, spawnY))
}
