// Code generated by tool/nest. DO NOT EDIT.
package handler_sender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"time"
)

var (
	_ = time.Second
)
var (
	handlerNameEquipItem = nest.NewHandlerName("handlerEquipItem")
)

// EquipItemSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type EquipItemSender struct {
	client nest.Client
}

func NewEquipItemSender(client nest.Client) *EquipItemSender {
	return &EquipItemSender{client: client}
}

func (s *EquipItemSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *EquipItemSender) Delay_EquipItem(ctx context.Context, delay time.Duration, id int64, itemID int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameEquipItem, id, nest.NewParams(itemID), nest.SendOptionWithDelay(delay))
}

func (s *EquipItemSender) Send_EquipItem(ctx context.Context, id int64, itemID int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameEquipItem, id, nest.NewParams(itemID))
}

func (s *EquipItemSender) Broadcast_EquipItem(ctx context.Context, ids []int64, itemID int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.DispatchBroadcast(ctx, handlerNameEquipItem, ids, nest.NewParams(itemID))
}
