// Code generated by tool/nest. DO NOT EDIT.
package handler_sender

import (
	"context"
	"example.com/planet/game/gift"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"time"
)

var (
	_ = time.Second
)
var (
	handlerNameGiftRefund = nest.NewHandlerName("handlerGiftRefund")
)

// GiftRefundSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type GiftRefundSender struct {
	client nest.Client
}

func NewGiftRefundSender(client nest.Client) *GiftRefundSender {
	return &GiftRefundSender{client: client}
}

func (s *GiftRefundSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *GiftRefundSender) Delay_GiftRefund(ctx context.Context, delay time.Duration, id int64, itemID int64, count int32, step gift.NativeStep) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameGiftRefund, id, nest.NewParams(itemID, count, step), nest.SendOptionWithDelay(delay))
}

func (s *GiftRefundSender) Send_GiftRefund(ctx context.Context, id int64, itemID int64, count int32, step gift.NativeStep) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameGiftRefund, id, nest.NewParams(itemID, count, step))
}

func (s *GiftRefundSender) Broadcast_GiftRefund(ctx context.Context, ids []int64, itemID int64, count int32, step gift.NativeStep) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.DispatchBroadcast(ctx, handlerNameGiftRefund, ids, nest.NewParams(itemID, count, step))
}
