// Code generated by tool/nest. DO NOT EDIT.
package handler_sender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"time"
)

var (
	_ = time.Second
)
var (
	handlerNamePlayerGuild = nest.NewHandlerName("handlerPlayerGuild")
)

// PlayerGuildSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type PlayerGuildSender struct {
	client nest.Client
}

func NewPlayerGuildSender(client nest.Client) *PlayerGuildSender {
	return &PlayerGuildSender{client: client}
}

func (s *PlayerGuildSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *PlayerGuildSender) Delay_PlayerGuild(ctx context.Context, delay time.Duration, id int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNamePlayerGuild, id, nest.NewParams(), nest.SendOptionWithDelay(delay))
}

func (s *PlayerGuildSender) Send_PlayerGuild(ctx context.Context, id int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNamePlayerGuild, id, nest.NewParams())
}

func (s *PlayerGuildSender) Broadcast_PlayerGuild(ctx context.Context, ids []int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.DispatchBroadcast(ctx, handlerNamePlayerGuild, ids, nest.NewParams())
}
