// Code generated by tool/nest. DO NOT EDIT.
package handler_sender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"time"
)

var (
	_ = time.Second
)
var (
	handlerNameWorldStats = nest.NewHandlerName("handlerWorldStats")
)

// WorldStatsSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type WorldStatsSender struct {
	client nest.Client
}

func NewWorldStatsSender(client nest.Client) *WorldStatsSender {
	return &WorldStatsSender{client: client}
}

func (s *WorldStatsSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *WorldStatsSender) Delay_WorldStats(ctx context.Context, delay time.Duration, id int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameWorldStats, id, nest.NewParams(), nest.SendOptionWithDelay(delay))
}

func (s *WorldStatsSender) Send_WorldStats(ctx context.Context, id int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.Dispatch(ctx, handlerNameWorldStats, id, nest.NewParams())
}

func (s *WorldStatsSender) Broadcast_WorldStats(ctx context.Context, ids []int64) error {
	client, err := s.nestClient()
	if err != nil {
		return err
	}
	return client.DispatchBroadcast(ctx, handlerNameWorldStats, ids, nest.NewParams())
}
