// Code generated by tool/nest. DO NOT EDIT.
package handler_syncsender

import (
	"context"
	"example.com/planet/game/dungeon"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var ()
var (
	handlerNameClaimDungeon = nest.NewHandlerName("handlerClaimDungeon")
)

// ClaimDungeonSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type ClaimDungeonSender struct {
	client nest.Client
}

func NewClaimDungeonSender(client nest.Client) *ClaimDungeonSender {
	return &ClaimDungeonSender{client: client}
}

func (s *ClaimDungeonSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *ClaimDungeonSender) MultiSync_ClaimDungeon(ctx context.Context, target int64, stats int64, runID string, amount int64, resolvedAtUnix int64, nowUnix int64) (ret dungeon.ClaimResult, err error) {
	client, clientErr := s.nestClient()
	if clientErr != nil {
		err = clientErr
		return
	}
	ids := []int64{target, stats}
	retXXX, errXXX := client.RequestMulti(ctx, handlerNameClaimDungeon, ids, nest.NewParams(runID, amount, resolvedAtUnix, nowUnix))
	err = errXXX
	if err != nil {
		return
	}
	if retXXX == nil {
		return
	}
	var ok bool
	ret, ok = retXXX.(dungeon.ClaimResult)
	if !ok {
		err = nest.NewResultTypeMismatchError(handlerNameClaimDungeon.String(), "dungeon.ClaimResult", retXXX)
	}
	return
}
