// Code generated by tool/nest. DO NOT EDIT.
package handler_syncsender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
	"github.com/tjbdwanghaibo/roost-core/spatial"
)

var ()
var (
	handlerNameEnterScene = nest.NewHandlerName("handlerEnterScene")
)

// EnterSceneSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type EnterSceneSender struct {
	client nest.Client
}

func NewEnterSceneSender(client nest.Client) *EnterSceneSender {
	return &EnterSceneSender{client: client}
}

func (s *EnterSceneSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *EnterSceneSender) MultiSync_EnterScene(ctx context.Context, target int64, area int64, spawnX int64, spawnY int64) (ret spatial.Point, err error) {
	client, clientErr := s.nestClient()
	if clientErr != nil {
		err = clientErr
		return
	}
	ids := []int64{target, area}
	retXXX, errXXX := client.RequestMulti(ctx, handlerNameEnterScene, ids, nest.NewParams(spawnX, spawnY))
	err = errXXX
	if err != nil {
		return
	}
	if retXXX == nil {
		return
	}
	var ok bool
	ret, ok = retXXX.(spatial.Point)
	if !ok {
		err = nest.NewResultTypeMismatchError(handlerNameEnterScene.String(), "spatial.Point", retXXX)
	}
	return
}
