// Code generated by tool/nest. DO NOT EDIT.
package handler_syncsender

import (
	"context"
	guild "example.com/planet/game/entities/guild"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var ()
var (
	handlerNameFoundGuild = nest.NewHandlerName("handlerFoundGuild")
)

// FoundGuildSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type FoundGuildSender struct {
	client nest.Client
}

func NewFoundGuildSender(client nest.Client) *FoundGuildSender {
	return &FoundGuildSender{client: client}
}

func (s *FoundGuildSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *FoundGuildSender) MultiSync_FoundGuild(ctx context.Context, target int64, member int64, name string, founderID int64, nowUnix int64) (ret guild.Info, err error) {
	client, clientErr := s.nestClient()
	if clientErr != nil {
		err = clientErr
		return
	}
	ids := []int64{target, member}
	retXXX, errXXX := client.RequestMulti(ctx, handlerNameFoundGuild, ids, nest.NewParams(name, founderID, nowUnix))
	err = errXXX
	if err != nil {
		return
	}
	if retXXX == nil {
		return
	}
	var ok bool
	ret, ok = retXXX.(guild.Info)
	if !ok {
		err = nest.NewResultTypeMismatchError(handlerNameFoundGuild.String(), "guild.Info", retXXX)
	}
	return
}
