// Code generated by tool/nest. DO NOT EDIT.
package handler_syncsender

import (
	"context"
	"example.com/planet/game/gift"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var ()
var (
	handlerNameGiftDebit = nest.NewHandlerName("handlerGiftDebit")
)

// GiftDebitSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type GiftDebitSender struct {
	client nest.Client
}

func NewGiftDebitSender(client nest.Client) *GiftDebitSender {
	return &GiftDebitSender{client: client}
}

func (s *GiftDebitSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *GiftDebitSender) Sync_GiftDebit(ctx context.Context, id int64, itemID int64, count int32, step gift.NativeStep) (ret int32, err error) {
	client, clientErr := s.nestClient()
	if clientErr != nil {
		err = clientErr
		return
	}
	retXXX, errXXX := client.Request(ctx, handlerNameGiftDebit, id, nest.NewParams(itemID, count, step))
	err = errXXX
	if err != nil {
		return
	}
	if retXXX == nil {
		return
	}
	var ok bool
	ret, ok = retXXX.(int32)
	if !ok {
		err = nest.NewResultTypeMismatchError(handlerNameGiftDebit.String(), "int32", retXXX)
	}
	return
}
