// Code generated by tool/nest. DO NOT EDIT.
package handler_syncsender

import (
	"context"
	guild "example.com/planet/game/entities/guild"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var ()
var (
	handlerNameGuildInfo = nest.NewHandlerName("handlerGuildInfo")
)

// GuildInfoSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type GuildInfoSender struct {
	client nest.Client
}

func NewGuildInfoSender(client nest.Client) *GuildInfoSender {
	return &GuildInfoSender{client: client}
}

func (s *GuildInfoSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *GuildInfoSender) Sync_GuildInfo(ctx context.Context, id int64) (ret guild.Info, err error) {
	client, clientErr := s.nestClient()
	if clientErr != nil {
		err = clientErr
		return
	}
	retXXX, errXXX := client.Request(ctx, handlerNameGuildInfo, id, nest.NewParams())
	err = errXXX
	if err != nil {
		return
	}
	if retXXX == nil {
		return
	}
	var ok bool
	ret, ok = retXXX.(guild.Info)
	if !ok {
		err = nest.NewResultTypeMismatchError(handlerNameGuildInfo.String(), "guild.Info", retXXX)
	}
	return
}
