// Code generated by tool/nest. DO NOT EDIT.
package handler_syncsender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var ()
var (
	handlerNameMovePlayer = nest.NewHandlerName("handlerMovePlayer")
)

// MovePlayerSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type MovePlayerSender struct {
	client nest.Client
}

func NewMovePlayerSender(client nest.Client) *MovePlayerSender {
	return &MovePlayerSender{client: client}
}

func (s *MovePlayerSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *MovePlayerSender) MultiSync_MovePlayer(ctx context.Context, target int64, area int64, x int64, y int64) (err error) {
	client, clientErr := s.nestClient()
	if clientErr != nil {
		err = clientErr
		return
	}
	ids := []int64{target, area}
	_, errXXX := client.RequestMulti(ctx, handlerNameMovePlayer, ids, nest.NewParams(x, y))
	err = errXXX
	if err != nil {
		return
	}
	return
}
