// Code generated by tool/nest. DO NOT EDIT.
package handler_syncsender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var ()
var (
	handlerNamePlayerLevel = nest.NewHandlerName("handlerPlayerLevel")
)

// PlayerLevelSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type PlayerLevelSender struct {
	client nest.Client
}

func NewPlayerLevelSender(client nest.Client) *PlayerLevelSender {
	return &PlayerLevelSender{client: client}
}

func (s *PlayerLevelSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *PlayerLevelSender) Sync_PlayerLevel(ctx context.Context, id int64) (ret int32, err error) {
	client, clientErr := s.nestClient()
	if clientErr != nil {
		err = clientErr
		return
	}
	retXXX, errXXX := client.Request(ctx, handlerNamePlayerLevel, id, nest.NewParams())
	err = errXXX
	if err != nil {
		return
	}
	if retXXX == nil {
		return
	}
	var ok bool
	ret, ok = retXXX.(int32)
	if !ok {
		err = nest.NewResultTypeMismatchError(handlerNamePlayerLevel.String(), "int32", retXXX)
	}
	return
}
