// Code generated by tool/nest. DO NOT EDIT.
package handler_syncsender

import (
	"context"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var ()
var (
	handlerNameTickWorldTimers = nest.NewHandlerName("handlerTickWorldTimers")
)

// TickWorldTimersSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type TickWorldTimersSender struct {
	client nest.Client
}

func NewTickWorldTimersSender(client nest.Client) *TickWorldTimersSender {
	return &TickWorldTimersSender{client: client}
}

func (s *TickWorldTimersSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *TickWorldTimersSender) Sync_TickWorldTimers(ctx context.Context, id int64, nowUnixMilli int64) (ret int32, err error) {
	client, clientErr := s.nestClient()
	if clientErr != nil {
		err = clientErr
		return
	}
	retXXX, errXXX := client.Request(ctx, handlerNameTickWorldTimers, id, nest.NewParams(nowUnixMilli))
	err = errXXX
	if err != nil {
		return
	}
	if retXXX == nil {
		return
	}
	var ok bool
	ret, ok = retXXX.(int32)
	if !ok {
		err = nest.NewResultTypeMismatchError(handlerNameTickWorldTimers.String(), "int32", retXXX)
	}
	return
}
