// Code generated by tool/nest. DO NOT EDIT.
package handler_syncsender

import (
	"context"
	world "example.com/planet/game/entities/world"
	"github.com/tjbdwanghaibo/roost-core/nest"
)

var ()
var (
	handlerNameWorldStats = nest.NewHandlerName("handlerWorldStats")
)

// WorldStatsSender is an instance-scoped, strongly typed Nest client. Construct
// it once at the access boundary and inject it instead of using nest.Nest.
type WorldStatsSender struct {
	client nest.Client
}

func NewWorldStatsSender(client nest.Client) *WorldStatsSender {
	return &WorldStatsSender{client: client}
}

func (s *WorldStatsSender) nestClient() (nest.Client, error) {
	if s == nil || s.client == nil {
		return nil, nest.ErrNestStopped
	}
	return s.client, nil
}

func (s *WorldStatsSender) Sync_WorldStats(ctx context.Context, id int64) (ret world.Stats, err error) {
	client, clientErr := s.nestClient()
	if clientErr != nil {
		err = clientErr
		return
	}
	retXXX, errXXX := client.Request(ctx, handlerNameWorldStats, id, nest.NewParams())
	err = errXXX
	if err != nil {
		return
	}
	if retXXX == nil {
		return
	}
	var ok bool
	ret, ok = retXXX.(world.Stats)
	if !ok {
		err = nest.NewResultTypeMismatchError(handlerNameWorldStats.String(), "world.Stats", retXXX)
	}
	return
}
