// Code generated by tool/entity. DO NOT EDIT.
package guild

import (
	"strings"
	"testing"

	"github.com/tjbdwanghaibo/roost-core/entity"
)

// guildDeleteChangeSource reports a DAO-level delete for every
// participant, which the remote commit must refuse: a DAO cannot be deleted
// without removing the entity.
type guildDeleteChangeSource struct{}

func (guildDeleteChangeSource) RemotePersistChangeFor(any) (entity.RemotePersistChange, bool) {
	return entity.RemotePersistChange{Delete: true}, true
}

// TestGuildRemoteCommitGuards pins the remote-commit contract of the generated
// wiring where it is compiled: a commit without transaction-local persistence
// changes, a DAO-level delete, and an acknowledgement for another entity are
// each refused instead of producing a partial or misattributed commit.
func TestGuildRemoteCommitGuards(t *testing.T) {
	RegisterEntity()
	e, err := NewGuild(&entity.EntityCreateParam{IsCreate: true, UniqueID: 1, Kind: EntityKindGuild})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := e.BuildRemoteCommitLocked(entity.RemoteWriteLease{}, entity.RemoteTransactionOutcome{}); err == nil || !strings.Contains(err.Error(), "missing transaction-local remote persistence changes") {
		t.Fatalf("BuildRemoteCommitLocked without persistence changes = %v", err)
	}
	if _, err := e.BuildRemoteCommitLocked(entity.RemoteWriteLease{}, entity.RemoteTransactionOutcome{PersistChanges: guildDeleteChangeSource{}}); err == nil || !strings.Contains(err.Error(), "DAO-level remote delete requires entity removal") {
		t.Fatalf("BuildRemoteCommitLocked with a DAO-level delete = %v", err)
	}
	if err := e.AcknowledgeRemoteCommit(entity.RemoteCommit{EntityID: e.GUId() + 1}); err == nil || !strings.Contains(err.Error(), "remote acknowledgement identity mismatch") {
		t.Fatalf("AcknowledgeRemoteCommit for another entity = %v", err)
	}
}
